app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb, config/routes.rb, spec/routing/routes_spec.rb, spec/views/exchanges/hbx_profiles/show.html.erb_spec.rb
* 
* ()
* ()
```
```
*
---
---
* Created the branch from usecase#14963
=> Userstory 14965

app/views/broker_agencies/profiles/_employers.html.erb, spec/views/broker_agencies/profiles/_employers.html.erb_spec.rb
* https://devops.dchbx.org/redmine/issues/15220
* ()
* ()
```
```
*
---
---
=> User story#15220

app/models/forms/family_member.rb, app/views/insured/families/_shop_for_plans_widget.html.erb, app/views/insured/families/verification.html.erb, app/views/shared/_consumer_fields.html.erb, features/insured/individual_verification.feature, spec/models/forms/family_member_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Use case 15005

app/models/premium_table.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15075](https://devops.dchbx.org/redmine/issues/15075) |
| Start Date | 04/03/2017 |
| Due Date | 04/15/2017  |
=> 15075: Import Rating Area from SERFF Template

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> added Wells and Carousel

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Tabs and Alerts

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Breadcrumbs and Tab

app/views/uis/bootstrap3_examples/index.html.erb
It will address various buttons creation and panels list creation...
=> It will address Buttons and panels section.

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> progrees,sliders and tootltips,popovers

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Checkboxes and Radio Buttons and Text Area

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Added navigation and badges

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Bootstarp doc for Input and File Input

app/controllers/uis/bootstrap3_examples_controller.rb, app/models/effective/datatables/example_datatable.rb, app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> table examples started

app/views/uis/bootstrap3_examples/index.html.erb
It will address panel footer section and text formatting.
=> Address panel footer and formatting text

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 15183 harsha c

app/controllers/broker_agencies/profiles_controller.rb, app/models/effective/datatables/broker_agency_datatable.rb, app/views/broker_agencies/profiles/_menu.html.erb, app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb, app/views/layouts/application.html.erb
Before It was not correctly displaying view layout for broker_agencies profile creation process alone. This changes will address to display the view for broker_agencies as before master branch was displaying.
=> It will properly display view for broker_agency profile creation process

spec/views/broker_agencies/profiles/_menu.html.erb_spec.rb
It will fix the failing spec _menu.html.erb_spec file on this branch
=> Address the spec for broker_agencies views 

app/models/scheduled_event.rb, spec/controllers/application_controller_spec.rb, spec/factories/scheduled_event.rb, spec/models/scheduled_event_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> User Story #15462: Create a model for schedulable events

app/views/uis/bootstrap3_examples/index.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs 15183 fixing sizing as per comments

app/controllers/general_agencies/profiles_controller.rb, app/views/general_agencies/profiles/_menu.html.erb, app/views/layouts/application.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixed layouts in GA

app/models/carrier_profile.rb, app/models/organization.rb, spec/factories/carrier_profiles.rb, spec/models/carrier_profile_spec.rb, spec/models/organization_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14813](https://devops.dchbx.org/redmine/issues/14813) |
| Ticket Author | @jackweiner |
=> 14813: Support for carriers offering single plan only

app/models/benefit_group.rb, app/models/composite_rated_plan_cost_decorator.rb, app/models/composite_rating_tier.rb, app/models/composite_tier_contribution.rb, spec/models/composite_rated_plan_cost_decorator_spec.rb, spec/models/composite_tier_contribution_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16218](https://devops.dchbx.org/redmine/issues/16218) |
=> 16218: Create composite rating plan cost decorator

app/assets/stylesheets/application.scss.erb, app/controllers/exchanges/scheduled_events_controller.rb, app/views/exchanges/scheduled_events/_event_form.html.erb, app/views/exchanges/scheduled_events/_get_events_field.html.erb, app/views/exchanges/scheduled_events/_scheduled_events_list.html.erb, app/views/exchanges/scheduled_events/edit.html.erb, app/views/exchanges/scheduled_events/index.html.erb, app/views/exchanges/scheduled_events/list.html.erb, app/views/exchanges/scheduled_events/new.html.erb, app/views/exchanges/scheduled_events/show.html.erb, config/routes.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16239](https://devops.dchbx.org/redmine/issues/16239) |
| Ticket Author | @harshared |
=> 16239: Humanize dropdown and separate page to list events

app/models/benefit_group.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16312](https://devops.dchbx.org/redmine/issues/16312) |
=> 16312: Assign benefit group interface for refactor

app/assets/stylesheets/application.scss.erb, app/controllers/exchanges/scheduled_events_controller.rb, app/models/event_exception.rb, app/models/scheduled_event.rb, app/views/exchanges/scheduled_events/_event_form.html.erb, app/views/exchanges/scheduled_events/_get_events_field.html.erb, app/views/exchanges/scheduled_events/_scheduled_events_list.html.erb, app/views/exchanges/scheduled_events/edit.html.erb, app/views/exchanges/scheduled_events/index.html.erb, app/views/exchanges/scheduled_events/list.html.erb, app/views/exchanges/scheduled_events/new.html.erb, app/views/exchanges/scheduled_events/show.html.erb, config/routes.rb, lib/tasks/migrations/load_federal_holidays.rake, spec/controllers/exchanges/scheduled_events_controller_spec.rb, spec/lib/migrations/load_federal_holidays_spec.rb, spec/models/scheduled_event_spec.rb, spec/views/exchanges/scheduled_events/edit.html.erb_spec.rb, spec/views/exchanges/scheduled_events/index.html.erb_spec.rb, spec/views/exchanges/scheduled_events/show.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16202](https://devops.dchbx.org/redmine/issues/16202) |
=> 16202: Seed File

app/models/composite_rating_tier_factor_set.rb, app/models/employer_group_size_rating_factor_set.rb, app/models/employer_participation_rate_rating_factor_set.rb, app/models/rating_factor_entry.rb, app/models/rating_factor_set.rb, app/models/sic_code_rating_factor_set.rb, spec/models/composite_rating_tier_factor_set_spec.rb, spec/models/employer_group_size_rating_factor_set_spec.rb, spec/models/employer_participation_rate_rating_factor_set_spec.rb, spec/models/rating_factor_entry_spec.rb, spec/models/sic_code_rating_factor_set_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16222](https://devops.dchbx.org/redmine/issues/16222) |
=> 16222: Standard Industry Code Rating Factors

app/helpers/config/aca_helper.rb, app/models/plan.rb, app/views/events/hbx_enrollment/_plan.xml.haml, app/views/events/v2/employers/_elected_plan.xml.haml, config/settings.yml, spec/views/events/hbx_enrollment/policy.xml.haml_spec.rb, spec/views/events/v2/employers/_elected_plan.xml.haml_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16306](https://devops.dchbx.org/redmine/issues/16306) |
=> 16306: Extend plan model to support super group ids

app/models/benefit_group.rb, app/models/benefit_group_assignment.rb, app/models/census_employee.rb, app/models/concerns/config/aca_model_concern.rb, app/models/employer_group_size_rating_factor_set.rb, app/models/hbx_enrollment.rb, app/models/plan_year.rb, app/models/rating_factor_set.rb, config/settings.yml, spec/models/benefit_group_composite_rating_factors_spec.rb, spec/models/employer_group_size_rating_factor_set_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16017](https://devops.dchbx.org/redmine/issues/16017) |
=> 16017: Employer Group Size Calculation

app/models/benefit_group.rb, app/models/employer_group_size_rating_factor_set.rb, app/models/employer_participation_rate_rating_factor_set.rb, app/models/employer_profile.rb, app/models/plan_year.rb, app/models/rate_reference.rb, app/models/sic_code_rating_factor_set.rb, spec/models/benefit_group_composite_rating_factors_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16018](https://devops.dchbx.org/redmine/issues/16018) |
=> 16018: Participation Rate Calculation

app/models/benefit_group.rb, app/models/caches/plan_details.rb, app/models/composite_rating_base_rates_calculator.rb, app/models/composite_rating_list_bill_precalculator.rb, app/models/composite_rating_tier_factor_set.rb, app/models/composite_tier_contribution.rb, spec/models/benefit_group_composite_rating_factors_spec.rb, spec/models/composite_rating_base_rates_calculator_spec.rb, spec/models/composite_rating_list_bill_precalculator_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16023](https://devops.dchbx.org/redmine/issues/16023) |
=> 16023: Employer Composite Rating Scenarios

app/models/benefit_group.rb, app/models/census_employee.rb, app/models/composite_rating_base_rates_calculator.rb, app/models/factories/family_enrollment_renewal_factory.rb, app/models/hbx_enrollment.rb, app/models/plan_year.rb, app/models/queries/employer_monthly_enrollments.rb, spec/models/factories/family_enrollment_renewal_factory_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16024](https://devops.dchbx.org/redmine/issues/16024) |
=> 16024: Employee Composite Rating Scenarios

app/models/plan_cost_decorator.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16217](https://devops.dchbx.org/redmine/issues/16217) |
=> 16217: Extend existing plan cost decorator for DC shop to accomodate MA list-bill

app/models/caches/plan_details.rb, config/initializers/plan_details_cache.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16310](https://devops.dchbx.org/redmine/issues/16310) |
=> 16310: Create new plan premium lookup which keys on rating area as well

spec/models/plan_year_spec.rb, spec/views/employers/census_employees/show.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Spec fixes due to plan_cost_decorator sic_code_rating_factor_set

app/controllers/exchanges/hbx_profiles_controller.rb, app/models/effective/datatables/user_account_datatable.rb, app/models/effective/mongoid_datatable.rb, app/models/user.rb, app/views/exchanges/hbx_profiles/_user_account_index_datatable.html.erb, app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb, app/views/exchanges/hbx_profiles/user_account_index.js.erb, config/routes.rb, project_gems/effective_datatables-2.6.14/app/controllers/effective/datatables_controller.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16256](https://devops.dchbx.org/redmine/issues/16256) |
=> 16256: UI: Implement Admin User Auth Index 

app/controllers/exchanges/hbx_profiles_controller.rb, app/models/effective/datatables/document_datatable.rb, app/views/exchanges/hbx_profiles/_index_verification.html.erb
* User Story #16050 Employer Attestation UI - Admin
* ()
* ()
```
```
*
---
---
=> Refs#16050 Employer Attestation UI - Admin

app/models/plan_year.rb, spec/models/plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15810](https://devops.dchbx.org/redmine/issues/15810) |
=> 15810: SIC Code Plan Year Validations

app/models/concerns/config/aca_model_concern.rb, app/models/document.rb, app/models/plan_cost_decorator.rb, app/models/plan_year.rb, app/models/premium_table.rb, app/models/rate_reference.rb, config/settings.yml, spec/factories/rate_reference.rb, spec/models/plan_cost_decorator_spec.rb, spec/models/plan_year_spec.rb, spec/models/premium_table_spec.rb, spec/models/rate_reference_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16511](https://devops.dchbx.org/redmine/issues/16511) |
=> 16511: Constrain all rating area values in models to valid enumeration values

app/models/carrier_profile.rb, db/seedfiles/carriers_seed.rb, spec/controllers/employers/plan_years_controller_spec.rb, spec/models/carrier_profile_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16451](https://devops.dchbx.org/redmine/issues/16451) |
=> 16451: Allow Carrier Profiles to Support Multiple HIOS ids

app/models/hbx_enrollment.rb, spec/models/hbx_enrollment_composite_rating_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16526](https://devops.dchbx.org/redmine/issues/16526) |
=> 16526: Enrollments should know to which composite rating tier they belong

app/models/plan.rb, lib/object_builders/qhp_builder.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16450](https://devops.dchbx.org/redmine/issues/16450) |
=> 16450: Extend Plan Loading to Carrier Service Areas

app/assets/javascripts/plan_year_selection.js.erb, app/helpers/config/aca_helper.rb, app/models/employer_profile.rb, app/models/rate_reference.rb, app/views/shared/_benefit_group_fields.html.erb, app/views/shared/_reference_plans_list.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16092](https://devops.dchbx.org/redmine/issues/16092) |
| Start Date | 05/16/2017 |
| Due Date | 05/16/2017  |
=> 16092: Move the contribution categories items below plan selection on benefit groups page

app/controllers/employers/census_employees_controller.rb, app/models/census_employee.rb, app/models/effective/datatables/employee_datatable.rb, config/routes.rb, spec/factories/census_employees.rb, spec/models/census_employee_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16467](https://devops.dchbx.org/redmine/issues/16467) |
=> 16467: Update census employee to allow recording of expected enrollment behavour

app/views/broker_agencies/profiles/_families.html.erb, spec/views/broker_agencies/profiles/_families.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15100](https://devops.dchbx.org/redmine/issues/15100) |
=> 15100: Disable IVL Functionality for Broker

app/assets/javascripts/datatable_custom_filter.js, project_gems/effective_datatables-2.6.14/app/controllers/effective/datatables_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Merge custom_attributes with datatables attributes

app/assets/javascripts/employer_profile.js, app/assets/javascripts/plan_year_selection.js.erb, app/assets/stylesheets/new.scss.erb, app/controllers/employers/plan_years_controller.rb, app/models/benefit_group.rb, app/models/composite_tier_contribution.rb, app/views/shared/_benefit_group_fields.html.erb, app/views/shared/_composite_tier_contribution_fields.html.erb, app/views/shared/_reference_plans_list.html.erb
* (16093)
* ()
* ()
```
```
*
---
---
=> #16093 - Benefits Page UI for Composite Ratings

app/models/carrier_profile.rb, app/models/organization.rb, lib/tasks/carriers_sole_source_update.rake, spec/factories/carrier_profiles.rb, spec/models/carrier_profile_spec.rb, spec/models/employee_role_integration_spec.rb, spec/models/organization_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Sole source fix

app/models/benefit_group.rb, app/models/composite_rating_tier.rb, app/views/shared/_composite_tier_contribution_fields.html.erb, spec/models/benefit_group_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16093](https://devops.dchbx.org/redmine/issues/16093) |
| Start Date | 05/16/2017 |
| Due Date | 05/16/2017  |
=> 16093: Benefits Page UI

app/views/shared/brokers/_applicants_index.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16628](https://devops.dchbx.org/redmine/issues/16628) |
=> 16628: Broker Portal- broker dashboard is out of alignment

app/controllers/employers/employer_profiles_controller.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16639](https://devops.dchbx.org/redmine/issues/16639) |
=> 16639: Employer Portal- "I'm and Employer" page is blank

app/views/shared/plan_shoppings/_more_plan_details.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixed effective date

app/controllers/broker_agencies/profiles_controller.rb, app/controllers/concerns/config/aca_concern.rb, app/views/broker_agencies/profiles/_employers.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16627](https://devops.dchbx.org/redmine/issues/16627) |
=> 16627: Broker Portal- Employer listing never loads

app/views/insured/families/home.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16660](https://devops.dchbx.org/redmine/issues/16660) |
=> 16660: EE account- Medicaid and tax credits button should be removed

app/assets/javascripts/employer_profile.js, app/assets/javascripts/plan_year_selection.js.erb, app/controllers/employers/plan_years_controller.rb, app/models/benefit_group.rb, app/models/census_employee.rb, app/models/composite_rating_base_rates_calculator.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/shared/_benefit_group_fields.html.erb, spec/models/census_employee_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16681](https://devops.dchbx.org/redmine/issues/16681) |
=> 16681: Draft PY and saved edited PY show different min and max amounts

app/views/insured/families/home.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> remove medicaid for IVL and EE as well

app/views/broker_agencies/profiles/_menu.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16683](https://devops.dchbx.org/redmine/issues/16683) |
=> 16683: Remove Medicaid link from broker portal

app/views/broker_agencies/profiles/_family_datatable_entry.json.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16685](https://devops.dchbx.org/redmine/issues/16685) |
=> 16685: Broker portal- when hovering over EEs name in Families tab, text color matches table color

app/views/broker_agencies/profiles/_menu.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16695](https://devops.dchbx.org/redmine/issues/16695) |
=> 16695: Turn off broker quote tool in UAT

app/views/exchanges/hbx_profiles/_family_index_datatable.html.erb, features/admin/new_employee_paper.feature, features/step_definitions/admin_paper_phone.rb, features/step_definitions/integration_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16662](https://devops.dchbx.org/redmine/issues/16662) |
=> 16662: Admin Access to EE Paper Application

app/assets/javascripts/forms.js, app/views/devise/registrations/new.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16719](https://devops.dchbx.org/redmine/issues/16719) |
=> 16719: Captcha Error when creating an account

Gemfile.lock, app/controllers/employers/plan_years_controller.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16731](https://devops.dchbx.org/redmine/issues/16731) |
=> 16731: Saving Sole Source Plan Year Throws Error

app/models/benefit_group.rb, app/models/plan.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16736](https://devops.dchbx.org/redmine/issues/16736) |
=> 16736: Elected plans are not properly filtered by service area

app/views/devise/registrations/new.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16652](https://devops.dchbx.org/redmine/issues/16652) |
=> 16652: Password Mismatch - Email optional field is displayed

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb, app/views/exchanges/scheduled_events/_primary_nav.html.erb, app/views/exchanges/scheduled_events/index.html.erb, config/routes.rb, spec/data_migrations/change_state_for_passive_enrollment_spec.rb, spec/models/employee_role_spec.rb, spec/models/employer_profile_spec.rb, spec/models/factories/census_employee_factory_spec.rb, spec/models/factories/employer_enroll_factory_spec.rb, spec/models/factories/employment_relationship_factory_spec.rb, spec/models/factories/plan_year_renewal_factory_spec.rb, spec/models/hbx_enrollment_spec.rb, spec/models/plan_year_spec.rb, spec/models/scheduled_event_spec.rb, spec/views/exchanges/scheduled_events/index.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16767](https://devops.dchbx.org/redmine/issues/16767) |
=> 16767: Admin Portal - 

app/models/effective/datatables/employer_document_datatable.rb, app/models/employer_attestation.rb, app/models/employer_profile.rb, app/models/plan_year.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/employer_profiles/my_account/_documents.html.erb, app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb, app/views/employers/plan_years/publish.js.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Employer Attestation front changes

app/controllers/employers/plan_years_controller.rb, app/models/benefit_group.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16766](https://devops.dchbx.org/redmine/issues/16766) |
=> 16766: Employer Flow - 0.00 Premiums within Employee Cost Details Modal 

app/views/employers/plan_years/_form.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Employer Attestation verification  model

app/models/benefit_group.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16739](https://devops.dchbx.org/redmine/issues/16739) |
=> 16739: Composite Rating - Subscriber Level Premium Incorrect

spec/factories/employer_attestation.rb, spec/factories/employer_profiles.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Added spec fixes

Gemfile.lock, app/helpers/events_helper.rb, app/models/concerns/config/aca_model_concern.rb, app/models/employer_profile.rb, app/models/plan_year.rb, app/views/events/v2/employers/updated.xml.haml, config/settings.yml, spec/helpers/events_helper_spec.rb, spec/models/plan_year_publishing_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16782](https://devops.dchbx.org/redmine/issues/16782) |
=> 16782: Add feature configuration for when employer plan years should be published

app/models/aws/s3_storage.rb, app/models/effective/datatables/employer_document_datatable.rb, app/models/time_keeper.rb, config/initializers/aws.rb, config/settings.yml, spec/models/aws/s3_storage_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Attestation model

app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/shared/organizations/_entity_name_and_type_fields_autofill.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16759](https://devops.dchbx.org/redmine/issues/16759) |
=> 16759: Minor UI Changes for ER Account

spec/controllers/employers/employer_profiles_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Fixed Employer profiles Controller specs

spec/views/employers/employer_profiles/my_account/_census_employees.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixed spec employer_profiles_my_accoun_census_employees

lib/tasks/convert_composite_rating_tier_factor_keys.rake
* (Required!)
* ()
* ()
```
```
*
---
---
=> typo in rating tier

spec/views/employers/employer_profiles/my_account/employees_by_status.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> employee_by_status spec fixed

app/models/employer_group_size_rating_factor_set.rb, app/models/employer_participation_rate_rating_factor_set.rb, spec/models/employer_group_size_rating_factor_set_spec.rb, spec/models/employer_participation_rate_rating_factor_set_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16853](https://devops.dchbx.org/redmine/issues/16853) |
=> 16853: Minimum lookups for group size and participation percent don't use right values

app/views/employers/census_employees/show.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16738](https://devops.dchbx.org/redmine/issues/16738) |
=> 16738: EE added to the roster on a Sunday shows and added date of Monday

Gemfile.lock, app/assets/stylesheets/effective_datatable.scss.erb, app/assets/stylesheets/new.scss.erb, app/views/employers/employer_profiles/my_account/_documents.html.erb, app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16761](https://devops.dchbx.org/redmine/issues/16761) |
=> 16761: UI Page Alignment

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16709](https://devops.dchbx.org/redmine/issues/16709) |
| Ticket Author | @ymhari |
=> 16709: Add Warning to Create account page

app/models/concerns/config/aca_model_concern.rb, app/models/plan_year.rb, spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16856](https://devops.dchbx.org/redmine/issues/16856) |
=> 16856: Several locations in plan year don't use settings correctly

app/controllers/employers/employer_profiles_controller.rb, app/models/person.rb, spec/controllers/employers/employer_profiles_controller_spec.rb, spec/views/employers/employer_profiles/_show_profile.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16859](https://devops.dchbx.org/redmine/issues/16859) |
=> 16859: Correct bare settings usage in Person class

features/admin/edit_aptc_csr_individual_disabled.feature, features/step_definitions/edit_dob_ssn_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixing scenarios

Gemfile, Gemfile.lock, app/controllers/employers/plan_years_controller.rb, app/models/benefit_group.rb, app/models/employer_participation_rate_rating_factor_set.rb, app/models/queries/employer_plan_offering_strategies/all_available_plans.rb, app/models/queries/employer_plan_offering_strategies/for_service_area.rb, app/models/queries/employer_plan_offerings.rb, lib/tasks/parallel_coverage.rake, spec/models/benefit_group_composite_rating_factors_spec.rb, spec/models/queries/employer_plan_offerings_spec.rb, spec/spec_helper.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16876](https://devops.dchbx.org/redmine/issues/16876) |
=> 16876: Fix offered plans queries to use plugable strategy

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 16860: fixed warning message

app/models/effective/datatables/user_account_datatable.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature #16256 UI: Implement Admin User Auth Index

app/controllers/employers/census_employees_controller.rb, app/controllers/employers/premium_statements_controller.rb, app/views/employers/census_employees/edit.html.erb, app/views/employers/census_employees/new.html.erb, app/views/employers/census_employees/show.html.erb, app/views/employers/employer_profiles/edit.html.erb, app/views/employers/employer_profiles/show_profile.html.erb, app/views/employers/plan_years/edit.html.erb, app/views/employers/plan_years/new.html.erb, app/views/employers/premium_statements/show.html.erb, app/views/layouts/application.html.erb, spec/views/employers/census_employees/show.html.erb_spec.rb, spec/views/employers/employer_profiles/_primary_nav.html.erb_spec.rb, spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb, spec/views/employers/plan_years/new.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixed layouts for employer controller views

app/helpers/config/aca_helper.rb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16900](https://devops.dchbx.org/redmine/issues/16900) |
=> 16900: Cannot access benefits tab

spec/lib/migrations/load_service_area_data_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> fixed the specs

lib/v2_group_xml_generator.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16947](https://devops.dchbx.org/redmine/issues/16947) |
| Ticket Author | Sri Harsha Poosa |
=> 16947: Including helper module in v2 script

script/write_broker_files.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17002](https://devops.dchbx.org/redmine/issues/17002) |
| Ticket Author | Sheheryar Tariq |
=> 17002: Weekly Broker XML- 7/10/17

app/jobs/shop_notices_notifier_job.rb, app/models/employer_profile.rb, app/notices/notice.rb, app/notices/pdf_templates/employee_notice.rb, app/notices/pdf_templates/employer_notice.rb, app/notices/shop_employee_notice.rb, app/notices/shop_employer_notice.rb, app/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.rb, app/views/notices/shared/_logo.html.erb, app/views/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employee_notices/employee_open_enrollment_reminder_notice_spec.rb, spec/notices/shop_employee_notices/open_enrollment_notice_for_auto_renewal_spec.rb, spec/notices/shop_employee_notices/open_enrollment_notice_for_no_renewal_spec.rb, spec/notices/shop_employee_notices/open_enrollment_notice_for_unenrolled_spec.rb, spec/notices/shop_employer_notices/employer_renewal_notice_spec.rb, spec/notices/shop_employer_notices/initial_employer_denial_notice_spec.rb, spec/notices/shop_employer_notices/initial_employer_eligibility_notice_spec.rb, spec/notices/shop_employer_notices/initial_employer_invoice_available_spec.rb, spec/notices/shop_employer_notices/initial_employer_open_enrollment_begin_spec.rb, spec/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year_spec.rb, spec/notices/shop_employer_notices/renewal_employer_eligibility_notice_spec.rb, spec/notices/shop_employer_notices/zero_employees_on_roster_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16775](https://devops.dchbx.org/redmine/issues/16775) |
=> 16775: Initial ER Reminder to Publish (Deadline Extended)

app/models/aws/s3_storage.rb, app/views/broker_agencies/quotes/_upload_employee_modal.html.erb, app/views/employers/employer_profiles/_download_new_template.html.erb, app/views/employers/employer_profiles/_upload_employees.html.erb, spec/models/aws/s3_storage_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16964](https://devops.dchbx.org/redmine/issues/16964) |
=> 16964: S3 upload files into bucket

app/models/employer_profile.rb, app/views/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #16775 modifications to the template

features/admin/user_account.feature, features/admin/user_lockable.feature, features/brokers/create_broker_agency_profiles_individual_disabled.feature, features/step_definitions/employer_profile_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 16699:fixed the cucumbers

app/helpers/application_helper.rb, app/views/employers/employer_profiles/_download_new_template.html.erb, app/views/employers/employer_profiles/_upload_employees.html.erb, spec/helpers/application_helper_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Use S3 helper instead of env varaible directly

app/helpers/config/s3_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Added a valid env checking

app/views/employers/employer_attestations/_edit.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16803](https://devops.dchbx.org/redmine/issues/16803) |
=> 16803: Timekeeper Helper Method

app/models/composite_tier_contribution.rb, spec/models/composite_tier_contribution_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16895](https://devops.dchbx.org/redmine/issues/16895) |
=> 16895: CTE - Cannot Save a Sole Source benefit package with 100% contributions

app/views/employers/employer_profiles/my_account/_home_tab.html.erb, spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16882](https://devops.dchbx.org/redmine/issues/16882) |
| Ticket Author | Brian Schuetz |
=> 16882: UAT - Wrong “Member Type” list and contribution percentage values displayed on Employer Homepage for sole source

app/helpers/config/contact_center_helper.rb, app/helpers/config/site_helper.rb, app/views/notices/shared/_footer.html.erb, app/views/notices/shop_employee_notices/13_employee_open_enrollment_reminder.html.erb, app/views/notices/shop_employee_notices/16b_initial_employee_open_enrollment_begins.html.erb, app/views/notices/shop_employer_notices/0_welcome_notice_employer.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_approval_notice.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb, app/views/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.html.erb, config/settings.yml
* (16772)
* ()
* ()
```
```
*
---
---
=> #16772 - maintain usage of settings helper wrapper methods

app/controllers/employers/employer_attestations_controller.rb, app/models/document.rb, app/models/effective/datatables/employer_datatable.rb, app/models/effective/datatables/employer_document_datatable.rb, app/models/employer_attestation.rb, app/models/employer_attestation_document.rb, app/views/employers/employer_attestations/_edit.html.erb, app/views/employers/employer_attestations/_verify_attestation.html.erb, app/views/employers/employer_attestations/verify_attestation.js.erb, app/views/employers/employer_profiles/my_account/_documents.html.erb, config/routes.rb, spec/models/employer_attestation_document_spec.rb, spec/models/organization_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16943](https://devops.dchbx.org/redmine/issues/16943) |
=> 16943: Improving the verification model functionality for employer attestation

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref:16732 - last peice on after plan year rejection

app/views/employers/employer_profiles/my_account/_documents.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16797](https://devops.dchbx.org/redmine/issues/16797) |
=> 16797: Employer Attestation - Upload button on click of Cancel from the Publish Plan year  is not working

app/models/effective/datatables/employer_datatable.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16896](https://devops.dchbx.org/redmine/issues/16896) |
=> 16896: In EA CTE, superfluous characters appear appended to group legal names 

app/models/benefit_group.rb, app/models/composite_tier_contribution.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, spec/models/benefit_group_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16881](https://devops.dchbx.org/redmine/issues/16881) |
| Ticket Author | Brian Schuetz |
=> 16881: UAT - Member Type values for Sole Source on Benefit Package Detail are out of order and have grammatical errors

app/helpers/employers/employer_helper.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, features/employers/cobra.feature, features/step_definitions/employers_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16880](https://devops.dchbx.org/redmine/issues/16880) |
| Ticket Author | Brian Schuetz |
=> 16880: UAT - Lack of value under “PLANS BY” label for sole source products

lib/v2_group_xml_generator.rb
…ment
- I added key values
- Once we have proper carrier_profile.legalnames we can udpate
- This should solve the problem right now.
* (Required!)
* ()
* ()
```
```
*
---
---
=> 16897- Manual ER Group File Generation

app/views/employers/employer_profiles/_primary_nav.html.erb, spec/views/employers/employer_profiles/_primary_nav.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17080](https://devops.dchbx.org/redmine/issues/17080) |
=> 17080: Broker -  Employer's Messages tab is not displayed

app/notices/notice.rb, app/views/layouts/notice.html.erb, app/views/layouts/pdf_notice.html.erb, app/views/user_mailer/plan_shopping_completed.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17075](https://devops.dchbx.org/redmine/issues/17075) |
=> 17075: Notice is showing the DC health link in the Mail Inbox and PDF document

app/views/layouts/notice.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17338](https://devops.dchbx.org/redmine/issues/17338) |
=> 17338: "Site Short name" text is displayed on opening the PDF

spec/rails_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17339-Failed to deploy in QA server

app/models/hbx_enrollment.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:16998-Last peice on notice genartion during PY publish

app/views/layouts/notice.html.erb, app/views/layouts/pdf_notice.html.erb, app/views/user_mailer/plan_shopping_completed.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17338 Site Short name text is displayed on opening the PDF

app/views/broker_agencies/quotes/_upload_employee_modal.html.erb, app/views/employers/employer_profiles/_download_new_template.html.erb, app/views/employers/employer_profiles/_upload_employees.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> updated s3 upload file name

app/helpers/config/aca_helper.rb, app/models/composite_rating_tier_factor_set.rb, app/views/shared/_reference_plans_list.html.erb, config/cucumber.yml, config/settings.yml, features/employers/employer_attestation.feature, features/employers/step_definitions/cobra_steps.rb, features/employers/step_definitions/employer_attestation_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17016](https://devops.dchbx.org/redmine/issues/17016) |
=> 17016: UAT - Remove/Hide Vertical/Horizontal Choice from Shopping (Sole Source Config for Soft Launch 8/15)

app/models/composite_tier_contribution.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17349](https://devops.dchbx.org/redmine/issues/17349) |
=> 17349: Benefits page doesn't display estimated calculations for sole source

app/invoices/employer_invoice.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17344](https://devops.dchbx.org/redmine/issues/17344) |
=> 17344: Invoice mail generated shows the From status as "DC Health Link"

app/views/notices/shop_employee_notices/15_employee_select_plan_during_annual_open_enrollment.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #16998. CSS styling

app/notices/shop_employee_notice.rb, app/notices/shop_employee_notices/employee_select_plan_during_open_enrollment.rb, app/notices/shop_employer_notices/initial_employer_eligibility_notice.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17359](https://devops.dchbx.org/redmine/issues/17359) |
| Ticket Author | Sri Harsha Poosa |
=> 17359: Non-Discrimination attachment in notices

app/controllers/application_controller.rb, app/controllers/concerns/config/site_concern.rb, app/helpers/config/site_helper.rb, app/views/devise/registrations/new.html.erb, config/settings.yml, features/employers/step_definitions/cobra_steps.rb, features/step_definitions/employer_profile_steps.rb, features/step_definitions/integration_steps.rb, spec/controllers/application_controller_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17350](https://devops.dchbx.org/redmine/issues/17350) |
=> 17350: Sign-In Page Redirect

app/views/employers/employer_profiles/my_account/_home_tab.html.erb, features/employers/cobra.feature, features/step_definitions/employers_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref#16880 Plans_by value on the My Health Connector in Home page

app/controllers/application_controller.rb, app/controllers/concerns/config/site_concern.rb, config/settings.yml
* (Required!)
* ()
* ()
```
```
*
---
---
=> configurable sign in or sign up paths

components/transport_gateway/app/models/transport_gateway/adapters/base.rb, components/transport_gateway/app/models/transport_gateway/adapters/file_adapter.rb, components/transport_gateway/app/models/transport_gateway/adapters/sftp_adapter.rb, components/transport_gateway/app/models/transport_gateway/gateway.rb, components/transport_gateway/app/models/transport_gateway/logging_observer.rb, components/transport_gateway/app/models/transport_gateway/message.rb, components/transport_gateway/lib/tasks/install_rspec.rake, components/transport_gateway/spec/models/transport_gateway/adapters/file_adapter_spec.rb, components/transport_gateway/spec/models/transport_gateway/adapters/sftp_adapter_spec.rb, components/transport_gateway/spec/models/transport_gateway/gateway_spec.rb, components/transport_gateway/templates/spec/transport_gateway_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17227](https://devops.dchbx.org/redmine/issues/17227) |
=> 17227: Update transport gem to perform more verbose logging

app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17360](https://devops.dchbx.org/redmine/issues/17360) |
| Ticket Author | Sri Harsha Poosa |
=> 17360:  Fixing the notice template 16774

app/notices/shop_employer_notices/initial_employer_open_enrollment_completed.rb, app/views/notices/shop_employer_notices/17_initial_employer_open_enrollment_completed.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/initial_employer_open_enrollment_completed_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17044](https://devops.dchbx.org/redmine/issues/17044) |
| Due Date | 07/14/2017  |
=> 17044: MIG017 - Initial Employee Open Enrollment Successfully Completed

app/data_migrations/remove_suppressed_fallon_plans.rb, lib/object_builders/qhp_builder.rb, lib/tasks/migrations/remove_suppressed_fallon_plans.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17297](https://devops.dchbx.org/redmine/issues/17297) |
| Ticket Author | @vineelsonnathi |
=> 17297: Write a script to suppress 4 Fallon Health Plans

app/views/user_mailer/initial_employee_invitation_email.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16776](https://devops.dchbx.org/redmine/issues/16776) |
=> 16776: MIE013 - Initial Open Enrollment Period Begins - EE Notice

app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16774](https://devops.dchbx.org/redmine/issues/16774) |
=> 16774: MIG003 - Request for Clarifying Documentation - Number of FTEs or MA Business Address(DENIAL notice) 

app/views/user_mailer/initial_employee_invitation_email.html.erb, spec/support/mail_spec_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:16776 failing specs will resolve this

app/models/plan_year.rb, app/notices/shop_employer_notices/initial_employer_ineligibility_notice.rb, app/views/notices/shop_employer_notices/20_a_initial_employer_ineligibility_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/initial_employer_ineligibility_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17046](https://devops.dchbx.org/redmine/issues/17046) |
| Due Date | 07/14/2017  |
=> 17046: MIG020 - Initial Employee Open Enrollment Completed (Did Not Meet Minimum Participation Requirement or non-owner enrollee requirement)

app/models/plan_year.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17046 added proper trigger seed name

app/views/notices/shop_employer_notices/20_a_initial_employer_ineligibility_notice.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17046 added employer full name instead of legal name

app/views/notices/shop_employer_notices/17_initial_employer_open_enrollment_completed.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17044: changed full name to legal name

components/transport_gateway/app/models/transport_gateway/adapters/sftp_adapter.rb, components/transport_gateway/app/models/transport_gateway/gateway.rb, components/transport_gateway/app/models/transport_gateway/sources/tempfile_source.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17439](https://devops.dchbx.org/redmine/issues/17439) |
=> 17439: Errors with closed IO streams for tempfile sources

app/views/notices/shared/_wish_by_name.html.erb, app/views/notices/shop_employer_notices/17_initial_employer_open_enrollment_completed.html.erb, app/views/notices/shop_employer_notices/20_a_initial_employer_ineligibility_notice.html.erb, app/views/notices/shop_employer_notices/initial_employer_invoice_available_notice.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17093 changes employername

app/models/plan_year.rb, app/views/notices/shared/_address.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref 17189 : Address Modifications and Trigger transitions

app/models/plan.rb, app/views/broker_agencies/quotes/_plan_comparision.html.erb, app/views/broker_agencies/quotes/_plan_comparison_export.html.erb, app/views/employers/plan_years/plan_selection/_offered_plan.html.erb, app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/employers/plan_years/plan_selection/_single_carriers.html.erb, app/views/insured/plan_shoppings/_plan_details.html.erb, app/views/shared/_comparison.html.erb, app/views/shared/_network_data.html.erb, app/views/shared/_summary.html.erb, db/seeds.rb, lib/tasks/import_network_information.rake, lib/tasks/migrations/load_service_area_data.rake, spec/views/employers/plan_years/plan_details/plan_details.html.erb_spec.rb, spec/views/insured/plan_shoppings/_plan_details.html.erb_spec.rb, spec/views/shared/_comparison.html.erb_spec.rb, spec/views/shared/_network_data.html.erb_spec.rb, spec/views/shared/summary.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17323](https://devops.dchbx.org/redmine/issues/17323) |
| Ticket Author | @vineelsonnathi |
=> 17323: Network field not displaying correct information

app/helpers/config/site_helper.rb, app/views/employers/employer_profiles/_employer_broker_widget.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16931](https://devops.dchbx.org/redmine/issues/16931) |
=> 16931: UAT - MA SHOP UI Content Bugs

app/views/employers/census_employees/_dependents_fields.html.erb, app/views/employers/census_employees/_errors_if_any.html.erb, app/views/employers/census_employees/_form.html.erb, app/views/employers/census_employees/show.html.erb, spec/views/employers/census_employees/show.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17345](https://devops.dchbx.org/redmine/issues/17345) |
=> 17345: UAT- Dependents do not appear when clicking "Edit" on EE Roster

spec/factories/plan_years.rb, spec/models/plan_year_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Spec fails dev

app/views/layouts/pdf_notice.html.erb, app/views/notices/shared/_address.html.erb, app/views/notices/shared/_logo.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17444](https://devops.dchbx.org/redmine/issues/17444) |
| Due Date | 08/01/2017  |
=> 17444: MA Return Address Change change to Eye Street on developed P1 Notices

app/assets/stylesheets/custom.scss.erb, app/assets/stylesheets/new.scss.erb, app/views/shared/_address_fields.html.erb, app/views/shared/_address_fields_for_dependent.html.erb, app/views/shared/_benefit_group_fields.html.erb
* (15785)
* ()
* ()
```
```
*
---
---
=> #15875 - CSS Refactor inline styling

app/controllers/employers/employer_profiles_controller.rb, app/models/effective/datatables/employer_document_datatable.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17226](https://devops.dchbx.org/redmine/issues/17226) |
=> 17226: UAT - ER - Incorrect modal displays when deleting attestation

app/helpers/insured/plan_filter_helper.rb, app/views/employers/employer_profiles/my_account/_billing.html.erb, app/views/employers/employer_profiles/my_account/_broker_agency.html.erb, app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb, spec/helpers/insured/plan_filter_helper_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17284](https://devops.dchbx.org/redmine/issues/17284) |
=> 17284: MA Branded User Guides/PDFs Missing

app/assets/javascripts/plan_year_selection.js.erb, app/views/employers/plan_years/calc_offered_plan_contributions.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17363](https://devops.dchbx.org/redmine/issues/17363) |
=> 17363: Configure which plans you're offering employees error

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:16774 removed trigger event notice

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_captcha.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 16299: Fixs the Capthca Signin error due to the latest changes

app/assets/stylesheets/custom.scss.erb, app/views/employers/employer_attestations/verify_attestation.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17408](https://devops.dchbx.org/redmine/issues/17408) |
=> 17408: Admin Attestation UI

spec/views/insured/group_selection/new.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Spec failures on dev

app/views/notices/draft-ER1a.html.erb, app/views/notices/draft-ER4b.html.erb, app/views/notices/draft_er9.html.erb, app/views/notices/renewal_1b.html.erb, app/views/notices/shop_employer_notices/employer_application_denial.html.erb, app/views/user_mailer/secure_purchase_confirmation.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17386](https://devops.dchbx.org/redmine/issues/17386) |
=> 17386: Secure Enrollment Confirmation has DC Health Link Logo not Mass

app/assets/stylesheets/effective_datatable.scss.erb, app/controllers/employers/employer_attestations_controller.rb, app/controllers/employers/employer_profiles_controller.rb, app/models/effective/datatables/employer_document_datatable.rb, app/models/employer_attestation.rb, app/views/datatables/shared/_dropdown.html.erb, app/views/employers/employer_profiles/my_account/_documents.html.erb, config/routes.rb, features/employers/employer_attestation.feature, features/employers/step_definitions/employer_attestation_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17403](https://devops.dchbx.org/redmine/issues/17403) |
=> 17403: UAT - ER Cannot Delete Attestation

spec/views/insured/plan_shoppings/receipt.html.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Address specs fails

app/views/notices/shared/_address.html.erb, app/views/notices/shop_employee_notices/15_employee_select_plan_during_annual_open_enrollment.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17538](https://devops.dchbx.org/redmine/issues/17538) |
| Ticket Author | Sri Harsha Poosa |
=> 17538: Remove employer name from the changes in #17444 and fix legal name issue in #16774

app/models/plan_cost_decorator_congress.rb, features/integration/ee_then_ivl.feature, features/step_definitions/conversion_employee_steps.rb, features/step_definitions/employer_profile_steps.rb, features/step_definitions/individual_steps.rb, features/step_definitions/integration_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Cucumber fix

lib/tasks/remove_2017_minute_man_plans.rake
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17472 : Remove minuteman organization.

app/controllers/employers/employer_profiles_controller.rb, app/models/employer_profile.rb, app/models/forms/organization_signup.rb, app/views/employers/employer_profiles/_employer_contact_preferences.html.erb, app/views/employers/employer_profiles/_employer_form.html.erb, app/views/employers/employer_profiles/_form.html.erb, features/employers/employer_profile.feature, features/step_definitions/employer_profile_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17446](https://devops.dchbx.org/redmine/issues/17446) |
=> 17446: ER Portal - Add Electronic or Paper Notice Option (to prescreener page and Update Business Info page)

app/models/benefit_group.rb, app/models/composite_rated_plan_cost_decorator.rb, app/models/hbx_enrollment.rb, spec/models/composite_rated_plan_cost_decorator_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17314](https://devops.dchbx.org/redmine/issues/17314) |
=> 17314: UAT - COBRA Employee Enrolling During Initial OE has Employer Contribution

app/models/benefit_group.rb, app/models/hbx_enrollment.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref#17314 necessary cobra_status entries

features/employers/employer_attestation.feature
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17592 log out of attestation scenario

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17591 Fixed inital application publish due date setting

app/helpers/config/contact_center_helper.rb, app/views/notices/shop_employer_notices/initial_employer_invoice_available_notice.html.erb, db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17093 trigger invoice notice

app/data_migrations/remove_suppressed_fallon_plans.rb, lib/object_builders/qhp_builder.rb, lib/tasks/migrations/remove_suppressed_fallon_plans.rake
* (Required!)
* ()
* ()
```
```
*
---
---
=> Data 17297 uat

app/helpers/config/site_helper.rb, app/helpers/insured/plan_filter_helper.rb, app/views/broker_agencies/quotes/_plan_comparision.html.erb, app/views/broker_agencies/quotes/_plan_comparison_export.html.erb, app/views/shared/_comparison.html.erb, app/views/shared/plan_shoppings/_provider_directory_url.html.erb, config/settings.yml, lib/tasks/plans/import_provider_and_rx_formulary_url.rake, lib/tasks/plans/standard_plans.rake, spec/helpers/insured/plan_filter_helper_spec.rb, spec/views/shared/_comparison.html.erb_spec.rb, spec/views/shared/plan_shoppings/_provider_directory_url.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17550](https://devops.dchbx.org/redmine/issues/17550) |
| Ticket Author | Luis Vasquez |
=> 17550: Updating Provider Directory URL and Formulary Links

app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb, app/views/employers/employer_profiles/my_account/_home_tab.html.erb, features/employers/cobra.feature, features/step_definitions/employers_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16756](https://devops.dchbx.org/redmine/issues/16756) |
=> 16756: Add text to initial employer homepage reminding about document upload for ER Attestation

app/models/concerns/config/aca_model_concern.rb, app/models/plan_year.rb, app/views/employers/plan_years/_publish_modal.html.erb, app/views/employers/plan_years/publish.js.erb, features/employers/step_definitions/employer_attestation_steps.rb, spec/concerns/scheduled_event_service_spec.rb, spec/controllers/employers/plan_years_controller_spec.rb, spec/models/plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17395](https://devops.dchbx.org/redmine/issues/17395) |
=> 17395: ER Portal - Update Modal Text when ER Attempts to Publish Ineligible Application

app/assets/javascripts/employer_profile.js, app/assets/javascripts/plan_year_selection.js.erb, app/assets/stylesheets/employer.scss.erb, app/assets/stylesheets/new.scss.erb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/employer_profiles/my_account/_home_tab.html.erb, app/views/employers/plan_years/_benefit_group_summary.html.erb, app/views/shared/_composite_tier_contribution_fields.html.erb, features/employers/step_definitions/employer_attestation_steps.rb, spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17418](https://devops.dchbx.org/redmine/issues/17418) |
=> 17418: Contribution minimum enforced when dependent coverage is not offered

app/models/plan_year.rb, app/views/employers/plan_years/_publish_modal.html.erb, features/employers/employer_attestation.feature, features/employers/step_definitions/employer_attestation_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17115](https://devops.dchbx.org/redmine/issues/17115) |
| Ticket Author | Elba Mendez |
=> 17115: UAT - Employer Attestation - Remove Force Publish Button

app/views/notices/shop_employee_notices/15_employee_select_plan_during_annual_open_enrollment.html.erb, app/views/notices/shop_employee_notices/notification_to_employee_due_to_initial_employer_ineligibility.html.erb, app/views/notices/shop_employer_notices/0_welcome_notice_employer.html.erb, app/views/notices/shop_employer_notices/17_initial_employer_open_enrollment_completed.html.erb, app/views/notices/shop_employer_notices/20_a_initial_employer_ineligibility_notice.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_approval_notice.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb, app/views/notices/shop_employer_notices/initial_employer_invoice_available_notice.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17602](https://devops.dchbx.org/redmine/issues/17602) |
=> 17602: Links from the Notices are not working in QA

app/assets/stylesheets/new.scss.erb, app/models/effective/datatables/employer_document_datatable.rb, features/employers/step_definitions/employer_attestation_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17558](https://devops.dchbx.org/redmine/issues/17558) |
=> 17558: ER - Remove Bulk Action Drop Down from Employer Attestation View

app/helpers/config/contact_center_helper.rb, app/views/employers/employer_profiles/my_account/_billing.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17555](https://devops.dchbx.org/redmine/issues/17555) |
=> 17555: Update "Pay by Mail" Address

app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, spec/controllers/exchanges/agents_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> "Refs #17677 change google analytics to ENV variable"

app/helpers/config/contact_center_helper.rb, app/helpers/config/site_helper.rb, app/models/employer_profile.rb, app/notices/pdf_templates/plan_year.rb, app/notices/shop_employer_notices/low_enrollment_notice.rb, app/views/notices/shop_employer_notices/low_enrollment_notice_for_employer.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/low_enrollment_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17086](https://devops.dchbx.org/redmine/issues/17086) |
| Due Date | 07/17/2017  |
=> 17086: MAG015-Low Enrollment Notice

app/models/forms/employer_profile.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17665](https://devops.dchbx.org/redmine/issues/17665) |
=> 17665: Paper and Electronic Communications Option is not persisting after account creation in the update business info page

app/models/effective/datatables/employer_document_datatable.rb, app/models/employer_attestation.rb, app/models/employer_attestation_document.rb, app/views/employers/employer_attestations/_verify_attestation.html.erb, app/views/employers/employer_profiles/my_account/_documents.html.erb, features/employers/employer_attestation.feature, features/employers/step_definitions/employer_attestation_steps.rb, spec/models/employer_attestation_document_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17368](https://devops.dchbx.org/redmine/issues/17368) |
=> 17368: Employer Attestation - Allow multiple document upload and approval

app/models/census_employee_import.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17714](https://devops.dchbx.org/redmine/issues/17714) |
=> 17714: QA - Employee Roster Upload selecting the Owner checkbox 

app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/employers/plan_years/recommend_dates.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17407](https://devops.dchbx.org/redmine/issues/17407) |
=> 17407: ER - Open Enrollment Period Business Rules Not Enforced 

app/models/employer_profile.rb, app/models/plan_year.rb, spec/data_migrations/create_new_initial_plan_year_using_another_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Use case 16774

app/models/census_employee_import.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref:17450 parse boolean

app/helpers/config/aca_helper.rb, app/views/shared/_reference_plans_list.html.erb, config/settings.yml, features/employers/cobra_sole_source.feature, features/employers/create_employer.feature, features/employers/employer_attestation.feature, features/employers/employer_attestation_sole_source.feature, features/employers/step_definitions/cobra_steps.rb, features/employers/step_definitions/employer_attestation_steps.rb, features/step_definitions/employers_steps.rb, features/step_definitions/integration_steps.rb, features/step_definitions/shop_plans_steps.rb, features/support/env.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Sole source cucumber refactored

app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/employers/plan_years/recommend_dates.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17588](https://devops.dchbx.org/redmine/issues/17588) |
=> 17588: Error While Saving Plan Year after Giving Open Enrollment Start date Greater Than End date And trying To Save plan Year With Correct dates

app/views/employers/plan_years/_publish_modal.html.erb
* (17395)
* ()
* ()
```
```
*
---
---
=> refs #17395 fix text

features/employers/employer_attestation.feature, features/employers/step_definitions/employer_attestation_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17115 address cucumber fail on employer attesttion

app/helpers/config/site_helper.rb, app/models/plan_year.rb, app/views/employers/plan_years/_publish_modal.html.erb, config/settings.yml, features/employers/employer_attestation.feature, features/employers/step_definitions/employer_attestation_steps.rb, spec/models/plan_year_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Bug 17115 final uat

app/views/shared/_carrier_contact_information.html.erb, spec/factories/carrier_profiles.rb, spec/views/shared/_carrier_contact_information.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17586](https://devops.dchbx.org/redmine/issues/17586) |
| Due Date | 08/04/2017  |
| Ticket Author | Kenneth Taylor |
=> 17586: Formulary Links, RX Links, and Carrier Contact Info (Soft Launch)

db/seedfiles/security_questions_seed.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17725](https://devops.dchbx.org/redmine/issues/17725) |
=> 17725: Seed Security Questions

app/helpers/config/site_helper.rb, app/views/notices/shop_employer_notices/0_welcome_notice_employer.html.erb, config/settings.yml
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref 17602 Checking in Mozilla Firefox

app/controllers/application_controller.rb, app/helpers/config/site_helper.rb, app/views/devise/shared/_links.html.erb, config/settings.yml, config/settings/test.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17764](https://devops.dchbx.org/redmine/issues/17764) |
| Due Date | 08/14/2017  |
| Ticket Author | @ipublic |
=> 17764: Remember last sign-in role

app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb, app/views/insured/employee_roles/privacy.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17752](https://devops.dchbx.org/redmine/issues/17752) |
=> 17752: Update MA Links 

app/views/shared/_summary.html.erb, spec/views/shared/summary.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17586](https://devops.dchbx.org/redmine/issues/17586) |
| Due Date | 08/04/2017  |
| Ticket Author | Kenneth Taylor |
=> 17586: Formulary Links, Provider Directory, and Carrier Contact Info (Soft Launch)

app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/views/user_mailer/broker_application_confirmation.html.erb, app/views/user_mailer/broker_invitation_email.html.erb, app/views/user_mailer/broker_pending_completed_training_missing_carrier.html.erb, app/views/user_mailer/broker_pending_missing_training_and_carrier.html.erb, features/step_definitions/brokers_steps.rb, features/step_definitions/general_agency_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17351](https://devops.dchbx.org/redmine/issues/17351) |
=> 17351: UAT - Update Broker Notification Emails

app/controllers/application_controller.rb, spec/controllers/exchanges/hbx_profiles_controller_spec.rb
* (17764)
* ()
* ()
```
```
*
---
---
=> ref#17764 add broker profile controller show action to update url

app/assets/stylesheets/custom.scss.erb, app/views/exchanges/hbx_profiles/shared/_nav_link.html.erb, app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
* (17583)
* ()
* ()
```
```
*
---
---
=> 17583 - Correcting nav bar style, better icons

app/models/plan_year.rb, app/notices/shop_employee_notices/initial_employee_plan_selection_confirmation.rb, app/views/layouts/application.html.erb, app/views/notices/shop_employee_notices/initial_employee_plan_selection_confirmation.html.erb, config/environments/production.rb, config/environments/test.rb, db/seedfiles/notice_triggers_seed.rb, spec/controllers/exchanges/agents_controller_spec.rb, spec/notices/shop_employee_notices/initial_employee_plan_selection_confirmation_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17118](https://devops.dchbx.org/redmine/issues/17118) |
| Due Date | 07/21/2017  |
| Ticket Author | Chloe Berger |
=> 17118: MIE070 - Employee Plan Selection Confirmation (New Groups Open enrollment – Confirmation of Enrollment)

app/controllers/employers/broker_agency_controller.rb, app/helpers/config/site_helper.rb, app/notices/pdf_templates/broker_notice.rb, app/notices/shop_broker_notice.rb, app/notices/shop_broker_notices/broker_hired_notice.rb, app/views/notices/shop_broker_notices/broker_hired_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_broker_notices/broker_hired_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17149](https://devops.dchbx.org/redmine/issues/17149) |
| Ticket Author | Chloe Berger |
=> 17149: MB0045- Broker Hired (notice to broker) - include date of appointment/termination

app/models/plan_year.rb, app/notices/shop_employer_notices/initial_employer_denial_notice.rb, app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/initial_employer_denial_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17791](https://devops.dchbx.org/redmine/issues/17791) |
=> 17791: Ticket 16774 Scenario Fix

app/helpers/config/site_helper.rb, app/notices/shop_employer_notices/zero_employees_on_roster.rb, app/views/notices/shop_employer_notices/notice_for_employers_with_zero_employees_on_roster.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/zero_employees_on_roster_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17085](https://devops.dchbx.org/redmine/issues/17085) |
| Due Date | 07/15/2017  |
=> 17085: MAG008-Zero Employees on Roster

app/models/aws/s3_storage.rb, lib/tasks/migrations/load_rating_factors.rake, spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb, spec/data_migrations/create_new_initial_plan_year_using_another_spec.rb, spec/factories/carrier_profiles.rb, spec/factories/rating_factor_sets.rb, spec/models/aws/s3_storage_spec.rb
…operly create composite_tier_factor_sets for carrier profiles
* (Required!)
* ()
* ()
```
```
*
---
---
=> Fix CompositeRatingTierFactorSet warning outputs

app/views/shared/_carrier_contact_information.html.erb, spec/factories/carrier_profiles.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17799](https://devops.dchbx.org/redmine/issues/17799) |
| Ticket Author | Kenneth Taylor |
=> 17799: Carrier Contact Info Not Displaying Correctly

app/reports/hbx_reports/edi_enrollment_termination_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_edi_enrollment_termination_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employee_terminations_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_export.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_poc_pending_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_roster_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employers_failing_participation_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_shop_brokers_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_shop_brokers_with_admin_url_report.rb, components/transport_profiles/db/seedfiles/well_known_endpoint_seed.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17878](https://devops.dchbx.org/redmine/issues/17878) |
=> 17878: Use standard endpoint names for shop reporting

app/controllers/insured/employee_roles_controller.rb, app/helpers/config/contact_center_helper.rb, app/helpers/config/site_helper.rb, app/mailers/user_mailer.rb, app/views/user_mailer/employee_ineligibility_notice.html.erb, config/settings.yml, spec/controllers/insured/employee_roles_controller_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17092](https://devops.dchbx.org/redmine/issues/17092) |
| Due Date | 07/19/2017  |
=> 17092: MAE009 - Employee ineligibility Notice

app/models/employer_profile.rb
* https://devops.dchbx.org/redmine/issues/16775
* ()
* ()
```
```
*
---
---
=> refs #16775 Fix logic for the trigger.

app/helpers/config/site_helper.rb, app/views/notices/shop_employee_notices/15_employee_select_plan_during_annual_open_enrollment.html.erb, app/views/notices/shop_employee_notices/notification_to_employee_due_to_initial_employer_ineligibility.html.erb, app/views/notices/shop_employer_notices/0_welcome_notice_employer.html.erb, app/views/notices/shop_employer_notices/17_initial_employer_open_enrollment_completed.html.erb, app/views/notices/shop_employer_notices/20_a_initial_employer_ineligibility_notice.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_approval_notice.html.erb, app/views/notices/shop_employer_notices/2_initial_employer_denial_notice.html.erb, app/views/notices/shop_employer_notices/initial_employer_invoice_available_notice.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17728](https://devops.dchbx.org/redmine/issues/17728) |
=> 17728: Mozilla Browser - Links from the Notices are not working in QA

app/helpers/config/site_helper.rb, app/views/notices/shop_employee_notices/14_employee_open_enrollment_reminder.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employee_notices/employee_open_enrollment_reminder_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16777](https://devops.dchbx.org/redmine/issues/16777) |
=> 16777: MAE014 - EE Reminder that Open Enrollment is Ending 

app/helpers/config/site_helper.rb, app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17087](https://devops.dchbx.org/redmine/issues/17087) |
| Due Date | 07/17/2017  |
=> 17087: MAE034-OE Begins for new hires P1.4

app/controllers/employers/broker_agency_controller.rb, app/helpers/config/site_helper.rb, app/jobs/shop_notices_notifier_job.rb, app/notices/pdf_templates/broker_notice.rb, app/notices/shop_broker_agency_notice.rb, app/notices/shop_broker_agency_notices/broker_agency_hired_notice.rb, app/views/notices/shop_broker_agency_notices/broker_agency_hired_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_broker_agency_notices/shop_broker_agency_hired_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17517](https://devops.dchbx.org/redmine/issues/17517) |
=> 17517: MY0044 - Broker Agency Hired Notice P1.4

app/controllers/insured/employee_roles_controller.rb, app/helpers/config/contact_center_helper.rb, app/helpers/config/site_helper.rb, app/mailers/user_mailer.rb, app/views/user_mailer/employee_ineligibility_notice.html.erb, config/settings.yml, spec/controllers/insured/employee_roles_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Support 17092

app/controllers/employers/broker_agency_controller.rb, app/helpers/config/site_helper.rb, app/notices/pdf_templates/broker.rb, app/notices/shop_employer_notice.rb, app/notices/shop_employer_notices/broker_hired_confirmation_notice.rb, app/views/notices/shop_employer_notices/broker_hired_confirmation_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/broker_hired_confirmation_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17150](https://devops.dchbx.org/redmine/issues/17150) |
| Ticket Author | Chloe Berger |
=> 17150: MAG046 - Confirmation of Broker Hired - Sent to Employer P1.4

app/views/notices/shop_employer_notices/low_enrollment_notice_for_employer.html.erb, db/seedfiles/notice_triggers_seed.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17086](https://devops.dchbx.org/redmine/issues/17086) |
| Due Date | 07/17/2017  |
=> 17086: MAG015-Low Enrollment Notice  P1.3

app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17088](https://devops.dchbx.org/redmine/issues/17088) |
| Due Date | 07/14/2017  |
=> 17088: MAE035-New hire notice, date of hire in the future P1.4

app/controllers/insured/plan_shoppings_controller.rb, app/jobs/shop_notices_notifier_job.rb, app/notices/pdf_templates/enrollment.rb, app/notices/shop_employee_notices/employee_waiver_confirm_notice.rb, app/views/notices/shop_employee_notices/employee_waiver_confirmation_notification.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employee_notices/employee_waiver_confirm_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17506](https://devops.dchbx.org/redmine/issues/17506) |
=> 17506: MA Notice Development - MAE029 Waiver Confirmation  P1.3

app/controllers/employers/employer_profiles_controller.rb, app/models/caches/sic_codes_cache.rb, app/models/concerns/sic_concern.rb, spec/concerns/sic_concern_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17827](https://devops.dchbx.org/redmine/issues/17827) |
=> 17827: SIC Tree Controller

app/views/notices/shop_employer_notices/low_enrollment_notice_for_employer.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 17086 new

app/models/aws/s3_storage.rb, spec/models/aws/s3_storage_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Spec failures

app/controllers/employers/broker_agency_controller.rb, app/jobs/shop_notices_notifier_job.rb, app/models/broker_agency_profile.rb, app/models/employer_profile.rb, app/notices/pdf_templates/broker_notice.rb, app/notices/shop_broker_agency_notice.rb, app/notices/shop_broker_agency_notices/broker_agency_fired_notice.rb, app/notices/shop_broker_agency_notices/broker_agency_hired_notice.rb, app/views/notices/shop_broker_agency_notices/broker_agency_fired_notice.html.erb, app/views/notices/shop_broker_agency_notices/broker_agency_hired_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_broker_agency_notices/shop_broker_agency_fired_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17518](https://devops.dchbx.org/redmine/issues/17518) |
=> 17518: MY0047 - Broker Agency Fired P1.4

app/controllers/insured/plan_shoppings_controller.rb, app/jobs/shop_notices_notifier_job.rb, app/notices/shop_employee_notices/employee_waiver_confirm_notice.rb, app/views/notices/shop_employee_notices/employee_waiver_confirmation_notification.html.erb, db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #15026 recommended changes

app/models/publishers/legacy/edi_enrollment_termination_report_publisher.rb, app/models/publishers/legacy/employee_termination_report_publisher.rb, app/models/publishers/legacy/employer_export_publisher.rb, app/models/publishers/legacy/employer_poc_pending_report_publisher.rb, app/models/publishers/legacy/employer_report_publisher.rb, app/models/publishers/legacy/employer_roster_report_publisher.rb, app/models/publishers/legacy/employers_failing_participation_report_publisher.rb, app/models/publishers/legacy/shop_brokers_report_publisher.rb, app/models/publishers/legacy/shop_brokers_with_admin_url_report_publisher.rb, app/reports/hbx_reports/edi_enrollment_termination_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_edi_enrollment_termination_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employee_terminations_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_export.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_poc_pending_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employer_roster_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_employers_failing_participation_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_shop_brokers_report.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_shop_brokers_with_admin_url_report.rb, components/transport_profiles/spec/models/transport_profiles/processes/legacy/push_employer_report_spec.rb, lib/tasks/employers_failing_minimum_participation.rake, lib/tasks/export_employers.rake, lib/tasks/hbx_reports/brokers.rake, lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake, lib/tasks/hbx_reports/employee_terminations.rake, lib/tasks/hbx_reports/employer_poc_pending_report.rake, lib/tasks/hbx_reports/employer_roster_report.rake, lib/tasks/hbx_reports/employers.rake, spec/reports/hbx_reports/edi_enrollment_termination_report_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17777](https://devops.dchbx.org/redmine/issues/17777) |
=> 17777: Transition legacy shop reports to new Transport Gateway

app/models/employer_profile.rb, app/notices/pdf_templates/broker_notice.rb, app/notices/shop_broker_notices/broker_fired_notice.rb, app/views/notices/shop_broker_notices/broker_fired_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_broker_notices/broker_fired_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17519](https://devops.dchbx.org/redmine/issues/17519) |
=> 17519: Broker Fired Notification  P1.4

app/controllers/insured/employee_roles_controller.rb, spec/controllers/insured/employee_roles_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17521

app/notices/shop_employee_notices/employee_termination_notice.rb, spec/notices/shop_employee_notices/employee_termination_notice_spec.rb
* https://devops.dchbx.org/redmine/issues/17520
* ()
* ()
```
```
*
---
---
=> User story 17520

app/views/user_mailer/invite_future_employee_for_open_enrollment.html.erb
* https://devops.dchbx.org/redmine/issues/17087
* https://devops.dchbx.org/redmine/issues/17088
* ()
```
```
*
---
---
=> refs #17088 Fix the template.

app/views/user_mailer/invite_future_employee_for_open_enrollment.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17088 update template text

app/notices/shop_broker_notice.rb
* https://devops.dchbx.org/redmine/issues/17149
* ()
* ()
```
```
*
---
---
=> Support 17149

app/notices/shop_broker_notice.rb, app/notices/shop_broker_notices/broker_fired_notice.rb, spec/notices/shop_broker_notices/broker_fired_notice_spec.rb
* https://devops.dchbx.org/redmine/issues/17519
* ()
* ()
```
```
*
---
---
=> User story 17519

app/views/user_mailer/employee_ineligibility_notice.html.erb, app/views/user_mailer/invite_future_employee_for_open_enrollment.html.erb, app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17533 address spec failures on development

app/notices/shop_broker_agency_notice.rb, app/views/notices/shared/_address.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17518 changed builder to display broker agency name

app/helpers/config/site_helper.rb, app/mailers/user_mailer.rb, app/models/eligibility/census_employee.rb, app/views/user_mailer/invite_future_employee_for_open_enrollment.html.erb, app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17088 fix broken links using helpers

app/views/user_mailer/shared/_non_discrimination.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17533 address broken links using helpers

app/models/queries/employer_monthly_enrollments.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17314 address benefit_group

lib/object_builders/qhp_rate_builder.rb, lib/tasks/hbx_import/qhp/parsers/plan_rate_group_list_parser.rb, lib/tasks/plans/qhp_plan_and_rate_import.rake, spec/lib/object_builders/qhp_rate_builder_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17452](https://devops.dchbx.org/redmine/issues/17452) |
=> 17452: Load 2018 Plan Data

app/controllers/broker_agencies/profiles_controller.rb, app/models/phone.rb, spec/controllers/broker_agencies/profiles_controller_spec.rb, spec/models/phone_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18013](https://devops.dchbx.org/redmine/issues/18013) |
=> 18013: Prod - Broker cannot update agency address

app/assets/javascripts/employer_profile.js, app/assets/javascripts/plan_year_selection.js.erb, app/controllers/employers/plan_years_controller.rb, app/helpers/application_helper.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18080](https://devops.dchbx.org/redmine/issues/18080) |
=> 18080: We are sorry message displayed when two benefit packages are added

app/helpers/config/site_helper.rb, app/views/notices/shop_employee_notices/employee_matches_employer_rooster_notification.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref 17521 : Updated Business Resource Center Links

app/models/employer_profile.rb, app/views/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.html.erb, spec/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #16775 updated the trigger and added hyperlinks

app/models/hbx_enrollment.rb, app/notices/employee_terminating_coverage.rb, app/notices/pdf_templates/employer_notice.rb, app/notices/pdf_templates/enrollment.rb, app/views/notices/employee_terminating_coverage.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/models/hbx_enrollment_spec.rb, spec/notices/employee_terminating_coverage_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17808](https://devops.dchbx.org/redmine/issues/17808) |
=> 17808: MAG039 - Notice of Employee Terminating coverage - P2.2

app/models/employer_profile.rb, app/notices/pdf_templates/broker.rb, app/notices/shop_employer_notices/employer_broker_fired_notice.rb, app/views/notices/shop_employer_notices/employer_broker_fired_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/models/employer_profile_spec.rb, spec/notices/shop_employer_notices/employer_broker_fired_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17746](https://devops.dchbx.org/redmine/issues/17746) |
=> 17746: MAG049 - Notification of broker fired sent to employer - P2.1

features/step_definitions/conversion_employee_steps.rb, spec/factories/benefit_groups.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref: address failing cucumber on file employee_plan_shopping.feature:5

app/models/hbx_enrollment.rb, app/notices/shop_employer_notices/initial_shop_application_approval_notice.rb, app/views/notices/shop_employer_notices/initial_shop_application_approval_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, lib/tasks/notices/shop_employer_notice.rake, spec/notices/shop_employer_notices/initial_shop_application_approval_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17647](https://devops.dchbx.org/redmine/issues/17647) |
=> 17647: Notice that Initial SHOP Application is Approved after Request for Clarifying Documentation - P2.2

spec/models/special_enrollment_period_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17649 address failing spec

app/controllers/broker_agencies/profiles_controller.rb, app/models/phone.rb, spec/controllers/broker_agencies/profiles_controller_spec.rb, spec/models/phone_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Bug 18013 master

app/helpers/config/site_helper.rb, app/models/hbx_enrollment.rb, app/notices/pdf_templates/enrollment.rb, app/notices/shop_employee_notices/employee_terminating_coverage.rb, app/views/notices/shop_employee_notices/employee_terminating_coverage.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/models/hbx_enrollment_spec.rb, spec/notices/shop_employee_notices/employee_terminating_coverage_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17809](https://devops.dchbx.org/redmine/issues/17809) |
=> 17809: MAE040 - Employee Terminating coverage - notice to EE that confirming choice to terminate coverage P2.2

app/models/employer_profile.rb, app/notices/shop_employee_notices/termination_of_employers_health_coverage.rb, app/views/devise/sessions/new.html.erb, app/views/notices/shop_employee_notices/termination_of_employers_health_coverage.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/models/employer_profile_spec.rb, spec/notices/shop_employee_notices/termination_of_employers_health_coverage_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17807](https://devops.dchbx.org/redmine/issues/17807) |
=> 17807: MIE059 - Notice to EEs that ER’s plan year will not be written - P2.1

app/notices/shop_employer_notices/group_advance_termination_confirmation.rb, app/views/notices/shop_employer_notices/group_advance_termination_confirmation.html.erb, db/seedfiles/notice_triggers_seed.rb, lib/tasks/migrations/terminate_employer_accounts.rake, spec/notices/shop_employer_notices/group_advance_termination_confirmation_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17650](https://devops.dchbx.org/redmine/issues/17650) |
=> 17650: Notice Confirmation - Group will be terminated due to ER advance request - P2.1

app/notices/shop_employer_notices/initial_shop_application_is_denied_after_request_for_clarifying_documentation.rb, app/views/notices/shop_employer_notices/initial_shop_application_is_denied_after_request_for_clarifying_documentation.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/notices/shop_employer_notices/initial_shop_application_is_denied_after_request_for_clarifying_documentation_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17648](https://devops.dchbx.org/redmine/issues/17648) |
=> 17648: Notice Initial SHOP Application is Denied after Request for Clarifying Documentation P2.2

app/models/publishers/legacy/new_people_application_report_publisher.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_new_people_application_report.rb, components/transport_profiles/spec/models/transport_profiles/processes/legacy/push_new_people_application_report_spec.rb, lib/tasks/hbx_reports/newly_registered_persons_data_report.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16826](https://devops.dchbx.org/redmine/issues/16826) |
| Due Date | 09/01/2017  |
| Ticket Author | @ap-dc |
=> 16826: Automate the applications extract generation for MA

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #16775 fixing the trigger date

app/assets/javascripts/register.js, app/assets/stylesheets/forms.scss.erb, app/assets/stylesheets/signup.scss.erb, app/controllers/users/passwords_controller.rb, app/controllers/users_controller.rb, app/data_migrations/define_permissions.rb, app/models/effective/datatables/user_account_datatable.rb, app/models/permission.rb, app/policies/user_policy.rb, app/views/devise/passwords/edit.html.erb, app/views/users/_reset_password.html.erb, app/views/users/reset_password.js.erb, config/routes.rb, features/admin/reset_password.feature, features/admin/user_lockable.feature, features/step_definitions/edit_dob_ssn_steps.rb, features/step_definitions/integration_steps.rb, features/step_definitions/lockable_steps.rb, lib/tasks/define_permissions.rake, spec/controllers/users_controller_spec.rb, spec/factories/permission.rb, spec/routing/user_routing_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16688](https://devops.dchbx.org/redmine/issues/16688) |
=> 16688: Automated Password Generation

features/admin/questions.feature
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17583: fixed failing tests

app/controllers/users/passwords_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> syntax error in password controller

components/transport_profiles/Gemfile, components/transport_profiles/app/models/transport_profiles/artifact_transport_request.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_glue_enrollment_report.rb, components/transport_profiles/app/models/transport_profiles/steps/route_to.rb, components/transport_profiles/app/models/transport_profiles/subscribers/transport_artifact_subscriber.rb, components/transport_profiles/app/models/transport_profiles/well_known_endpoint.rb, components/transport_profiles/db/seedfiles/well_known_endpoint_seed.rb, components/transport_profiles/spec/models/transport_profiles/artifact_transport_request_spec.rb, components/transport_profiles/spec/models/transport_profiles/subscribers/transport_artifact_subscriber_spec.rb, components/transport_profiles/transport_profiles.gemspec, config/application.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18132](https://devops.dchbx.org/redmine/issues/18132) |
=> 18132: Create Inter-application transport layer for transport_gateway transmission

components/transport_gateway/app/models/transport_gateway/adapters/s3_adapter.rb, components/transport_gateway/spec/models/transport_gateway/adapters/s3_adapter_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18133](https://devops.dchbx.org/redmine/issues/18133) |
=> 18133: Create reporting process and adapter for reception of glue data extracts by transport gateway

app/controllers/insured/families_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17649 Address failiing enque job

app/controllers/insured/plan_shoppings_controller.rb, app/helpers/config/contact_center_helper.rb, app/helpers/config/site_helper.rb, app/jobs/shop_notices_notifier_job.rb, app/notices/notice.rb, app/notices/pdf_templates/employee_notice.rb, app/notices/pdf_templates/special_enrollment_period.rb, app/notices/shop_employee_notice.rb, app/notices/shop_employee_notices/employee_sep_qle_accept_notice.rb, app/views/layouts/pdf_notice.html.erb, app/views/notices/shared/_cover.html.erb, app/views/notices/shop_employee_notices/notification_to_employee_due_to_sep.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, lib/tasks/plans/standard_plans.rake, spec/controllers/insured/plan_shoppings_controller_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17811](https://devops.dchbx.org/redmine/issues/17811) |
=> 17811: MAE032 - EE SEP Requested (Accepted) - P2.3

app/views/notices/shop_employer_notices/initial_shop_application_is_denied_after_request_for_clarifying_documentation.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17648 template change

app/views/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.html.erb, db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #16775 changing title

app/controllers/employers/census_employees_controller.rb, app/models/eligibility/employee_benefit_packages.rb, spec/controllers/employers/census_employees_controller_spec.rb, spec/models/special_enrollment_period_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16920](https://devops.dchbx.org/redmine/issues/16920) |
=> 16920: Cobra and fire/rehire functionality does not behave correctly in datatables

lib/tasks/hbx_reports/brokers.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18112](https://devops.dchbx.org/redmine/issues/18112) |
| Ticket Author | Jennifer Nelson-Samuel |
=> 18112: Broker SHOP repot not working when broker doesn't have primary office location

db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17810 : Change in MPI Indicator

app/controllers/application_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:15183 address code deployment issue

app/views/notices/shared/header_with_page_numbers.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18198](https://devops.dchbx.org/redmine/issues/18198) |
=> 18198: Page number issue in the notices

app/views/notices/shop_employee_notices/notice_to_employees_that_active_er_is_terminated_from_shop.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs 17651 Typo

app/assets/javascripts/qle.js.erb, app/controllers/insured/families_controller.rb, app/notices/shop_employee_notices/sep_request_denial_notice.rb, spec/controllers/insured/families_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17649: fixed the dates

app/controllers/exchanges/hbx_profiles_controller.rb, app/models/effective/datatables/employer_datatable.rb, app/models/employer_profile.rb, app/views/datatables/employers/_bulk_actions_column.html.haml, project_gems/effective_datatables-2.6.14/app/assets/javascripts/effective_datatables/bulk_actions.js.coffee, project_gems/effective_datatables-2.6.14/app/views/effective/datatables/_bulk_actions_column.html.haml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18139](https://devops.dchbx.org/redmine/issues/18139) |
=> 18139: MA Admin button to initiate "Binder Paid" state transition is not behaving as designed

app/controllers/exchanges/hbx_profiles_controller.rb, app/helpers/application_helper.rb, app/models/plan_year.rb, app/notices/shop_employee_notices/initial_employee_plan_selection_confirmation.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17118](https://devops.dchbx.org/redmine/issues/17118) |
| Due Date | 07/21/2017  |
| Ticket Author | Chloe Berger |
=> 17118: MIE070 - Employee Plan Selection Confirmation (New Groups Open enrollment – Confirmation of Enrollment)  P1.3

app/helpers/application_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17118 typo

app/notices/shop_employee_notices/sep_request_denial_notice.rb, spec/notices/shop_employee_notices/sep_request_denial_notice_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17649: date changed in template

app/views/user_mailer/employee_ineligibility_notice.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17092](https://devops.dchbx.org/redmine/issues/17092) |
| Due Date | 07/19/2017  |
=> 17092: MAE009 - Employee ineligibility Notice P1.3

app/views/notices/shop_broker_notices/broker_hired_notice.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17149 : Minor Text Change

app/views/notices/shop_employer_notices/initial_shop_application_is_denied_after_request_for_clarifying_documentation.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17648 change legal name

app/controllers/insured/plan_shoppings_controller.rb, app/helpers/application_helper.rb, app/models/hbx_enrollment.rb, app/notices/shop_employee_notices/employee_terminating_dental_coverage.rb, app/views/notices/shop_employee_notices/employee_terminating_dental_coverage.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/controllers/insured/plan_shoppings_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/hbx_enrollment_spec.rb, spec/notices/shop_employee_notices/employee_terminating_coverage_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17809 including dental

app/views/employers/employer_profiles/my_account/_billing.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17970](https://devops.dchbx.org/redmine/issues/17970) |
| Ticket Author | Kevin McDevitt |
=> 17970: Update to payment portal link

app/models/benefit_group.rb, lib/tasks/export_employers.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17310](https://devops.dchbx.org/redmine/issues/17310) |
| Start Date | 07/24/2017 |
| Due Date | 08/04/2017  |
=> 17310: Extend data extract for additional MA fields

app/helpers/config/site_helper.rb, app/views/broker_agencies/broker_roles/_new_broker_agency_form.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17727](https://devops.dchbx.org/redmine/issues/17727) |
=> 17727: Broker Registration Page - Add link to terms & conditions page

app/models/plan_year.rb, spec/models/plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18088](https://devops.dchbx.org/redmine/issues/18088) |
=> 18088: CTE - Employer Plan Year Error

app/notices/pdf_templates/plan_year.rb, app/notices/shop_employee_notices/sep_request_denial_notice.rb, app/views/notices/shop_employee_notices/sep_request_denial_notice.html.erb, spec/notices/shop_employee_notices/sep_request_denial_notice_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17649: typo in template

lib/tasks/hbx_reports/brokers.rake
* (Required!)
* ()
* ()
```
```
*
---
---
=> 18112: rebuilt the branch

app/notices/shop_employee_notices/employee_terminating_coverage.rb, app/notices/shop_employee_notices/employee_terminating_dental_coverage.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17809 picking the correct aasm_state

spec/notices/shop_employee_notices/employee_terminating_coverage_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref: 17809 address failing spec

Gemfile, Gemfile.lock
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17404 addresss failing deployment

app/notices/shop_employee_notices/sep_request_denial_notice.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 17649: small change in the dates

app/notices/shop_employee_notices/employee_terminating_coverage.rb, app/notices/shop_employee_notices/employee_terminating_dental_coverage.rb, spec/notices/shop_employee_notices/employee_terminating_coverage_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17809 picking the correct termination date

app/views/employers/employer_profiles/my_account/_billing.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17970 updates the billing URL's

app/views/notices/shop_employee_notices/employee_terminating_coverage.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs 17809 changed broker text

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb, config/routes.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 17404 latest

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref:17404 address code changes

Gemfile, Gemfile.lock, app/models/effective/datatables/notices_datatable.rb, components/notifier/app/assets/javascripts/notifier/application.js, components/notifier/app/controllers/notifier/notice_kinds_controller.rb, components/notifier/app/models/notifier/notice_kind.rb, components/notifier/app/views/notifier/notice_kinds/index.html.erb, components/notifier/config/routes.rb, components/notifier/notifier.gemspec, config/initializers/assets.rb, config/initializers/non_digest_assets.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 17404

app/views/notices/shop_employee_notices/employee_waiver_confirmation_notification.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> refs #17506 added link for business resource

app/views/employers/employer_profiles/my_account/accounts/_pay_my_bill.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:17970 address as per development code

app/controllers/insured/employee_roles_controller.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18388](https://devops.dchbx.org/redmine/issues/18388) |
=> 18388: Prod - Error message when linking EE to ER

Gemfile.lock, components/notifier/app/controllers/notifier/notice_kinds_controller.rb, components/notifier/app/models/notifier/notice_kind.rb, components/notifier/app/views/notifier/notice_kinds/index.html.erb, components/notifier/config/routes.rb, components/notifier/notifier.gemspec
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17404 code updates

lib/tasks/notices/shop_broker_agency_notice.rake, lib/tasks/notices/shop_employer_notice.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18308](https://devops.dchbx.org/redmine/issues/18308) |
=> 18308: Trigger Notice MY0044

app/helpers/config/site_helper.rb, app/views/layouts/_header.html.erb, config/settings.yml, features/hbx/layout_header.feature, features/hbx/step_definitions/layout_header_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17871](https://devops.dchbx.org/redmine/issues/17871) |
=> 17871: Prod - CCA Logo Link

app/helpers/config/contact_center_helper.rb, app/models/census_employee.rb, app/models/hbx_enrollment.rb, app/notices/pdf_templates/enrollment.rb, app/notices/shop_employee_notices/employee_dependent_termination_notice.rb, app/views/notices/shop_employee_notices/employee_dependent_termination_notice.html.erb, config/settings.yml, db/seedfiles/notice_triggers_seed.rb, spec/models/census_employee_spec.rb, spec/notices/shop_employee_notices/employee_dependent_termination_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17814](https://devops.dchbx.org/redmine/issues/17814) |
=> 17814: MAE081 - Notify EE of DPT Termination due to age-off - P2.3

app/views/employers/plan_years/reference_plan_summary.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18040](https://devops.dchbx.org/redmine/issues/18040) |
| Ticket Author | Maria Joy |
=> 18040: Less Details button

app/controllers/users/passwords_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref#17927 fix reset password controller check identity

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Shop notices 16775 new

app/assets/javascripts/qle.js.erb, app/controllers/insured/families_controller.rb, app/helpers/config/contact_center_helper.rb, app/models/special_enrollment_period.rb, app/notices/pdf_templates/employee_notice.rb, app/notices/pdf_templates/enrollment.rb, app/notices/pdf_templates/plan_year.rb, app/notices/pdf_templates/qualifying_life_event_kind.rb, app/notices/shop_employee_notices/sep_request_denial_notice.rb, app/views/notices/shop_employee_notices/sep_request_denial_notice.html.erb, db/seedfiles/notice_triggers_seed.rb, spec/controllers/insured/families_controller_spec.rb, spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb, spec/models/special_enrollment_period_spec.rb, spec/notices/shop_employee_notices/sep_request_denial_notice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17649](https://devops.dchbx.org/redmine/issues/17649) |
=> 17649: Notice EE SEP Requested Outside of 30 day window - Denial P2.1

components/notifier/app/helpers/notifier/application_helper.rb, components/notifier/app/views/layouts/notifier/_footer.html.erb, components/notifier/app/views/layouts/notifier/_header.html.erb, components/notifier/app/views/layouts/notifier/single_column.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17404 Pushed url fixes

config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18250](https://devops.dchbx.org/redmine/issues/18250) |
=> 18250: In EA CTF and CPR please enable vertical carrier choice

app/mailers/user_mailer.rb, app/views/user_mailer/broker_pending_missing_training_completed_carrier.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17821](https://devops.dchbx.org/redmine/issues/17821) |
=> 17821: Incorrect broker notification triggered

app/helpers/config/aca_helper.rb, app/views/broker_agencies/profiles/_menu.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17798](https://devops.dchbx.org/redmine/issues/17798) |
=> 17798: Broker Portal - Hide "Brokers" Tab

app/models/effective/datatables/family_data_table.rb, app/models/queries/family_datatable_query.rb, spec/models/queries/family_datatable_query_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18205](https://devops.dchbx.org/redmine/issues/18205) |
=> 18205: QA- Families Dashboard- subfilters are not working

components/transport_gateway/app/models/transport_gateway/adapters/s3_adapter.rb, components/transport_gateway/spec/models/transport_gateway/adapters/s3_adapter_spec.rb, components/transport_profiles/Gemfile, components/transport_profiles/app/models/transport_profiles/artifact_transport_request.rb, components/transport_profiles/app/models/transport_profiles/processes/legacy/push_glue_enrollment_report.rb, components/transport_profiles/app/models/transport_profiles/steps/route_to.rb, components/transport_profiles/app/models/transport_profiles/subscribers/transport_artifact_subscriber.rb, components/transport_profiles/app/models/transport_profiles/well_known_endpoint.rb, components/transport_profiles/db/seedfiles/well_known_endpoint_seed.rb, components/transport_profiles/spec/models/transport_profiles/artifact_transport_request_spec.rb, components/transport_profiles/spec/models/transport_profiles/subscribers/transport_artifact_subscriber_spec.rb, components/transport_profiles/transport_profiles.gemspec, config/application.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18145](https://devops.dchbx.org/redmine/issues/18145) |
=> 18145: Create updated endpoint config for transport_gateway

app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/shared/_benefit_group_fields.html.erb, app/views/shared/_dental_reference_plans_list.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18248](https://devops.dchbx.org/redmine/issues/18248) |
=> 18248: Once a benefit group is saved, upon editing you cannot add a dental plan to the group

lib/tasks/hbx_reports/newly_registered_persons_data_report.rake
* (Required!)
* ()
* ()
```
```
*
---
---
=> apparently the report is supposed to be cumulative

app/views/shared/_plan_year_fields.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18202](https://devops.dchbx.org/redmine/issues/18202) |
=> 18202: ER Portal - Add/Edit Plan Year Page - Text Correction Needed for earliest PY start date

components/notifier/app/views/layouts/notifier/pdf_layout.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17404 Added font size fix for broker widget

app/views/events/individuals/_individual.xml.haml, spec/factories/generative_employer_profile.rb, spec/views/events/individuals/created.xml.haml_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18749](https://devops.dchbx.org/redmine/issues/18749) |
| Ticket Author | @saimekala07  |
=> 18749: Update broker cv template in enroll

app/controllers/concerns/config/site_concern.rb, app/controllers/session_timeout_controller.rb, app/helpers/config/site_helper.rb, app/views/devise/sessions/session_expiration_warning.js.erb, app/views/devise/sessions/sign_out_user.js.erb, app/views/layouts/_header.html.erb, config/initializers/devise.rb, lib/custom_failure_app.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17948](https://devops.dchbx.org/redmine/issues/17948) |
=> 17948: user timeout redirect path should be configured in settings

lib/tasks/notices/shop_employer_notice_for_all_inputs.rake, spec/lib/tasks/notices/shop_employer_notice_for_all_inputs_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18534](https://devops.dchbx.org/redmine/issues/18534) |
=> 18534: Trigger Notice MAG046

app/assets/javascripts/security_question.js.coffee, app/controllers/users/security_question_responses_controller.rb, app/views/users/security_question_responses/_edit_modal.html.erb, app/views/users/security_question_responses/_filter_security_questions.html.erb, config/routes.rb, features/employee/conversion_employee.feature, features/step_definitions/security_question_step.rb, spec/controllers/users/security_question_responses_controller_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18124](https://devops.dchbx.org/redmine/issues/18124) |
=> 18124: Same Security Question is triggerred multiple times

app/helpers/config/site_helper.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18821](https://devops.dchbx.org/redmine/issues/18821) |
=> 18821: Update "Create Account" Button URL in PRODUCTION ONLY

app/helpers/config/site_helper.rb, app/views/notices/shop_employee_notices/termination_of_employers_health_coverage.html.erb, lib/tasks/notices/shop_employer_notice_for_all_inputs.rake, spec/lib/tasks/notices/shop_employer_notice_for_all_inputs_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18661](https://devops.dchbx.org/redmine/issues/18661) |
| Ticket Author | Elba Mendez |
=> 18661: Notice content cut off 

app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Google tag manager new

app/helpers/config/site_helper.rb, app/views/user_mailer/generic_notice_alert.html.erb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18820](https://devops.dchbx.org/redmine/issues/18820) |
=> 18820: Update URL in "You have a new secure message" email - 

app/helpers/broker_agencies/quote_helper.rb, app/helpers/config/aca_helper.rb, app/helpers/employers/employer_helper.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/employer_profiles/my_account/_home_tab.html.erb, app/views/layouts/application.html.erb, app/views/shared/_reference_plans_list.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/settings.yml, features/step_definitions/employers_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18978](https://devops.dchbx.org/redmine/issues/18978) |
=> 18978: ER Choice Titles & Corresponding Benefit Package UI

app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/insured/plan_shoppings/show.html.erb, app/views/products/qhp/summary.js.erb, spec/views/employers/plan_years/plan_details/plan_details.html.erb_spec.rb, spec/views/insured/plan_shoppings/show.html.erb_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18976](https://devops.dchbx.org/redmine/issues/18976) |
=> 18976: CMS Plan Shopping Notifications

app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/insured/plan_shoppings/show.html.erb, app/views/products/qhp/summary.js.erb, spec/views/insured/plan_shoppings/show.html.erb_spec.rb, spec/views/products/qhp/summary.js.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Ref:18976 address when benefit_group is sole_source

app/helpers/employers/employer_helper.rb, features/step_definitions/employers_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:18751 address plan text when it is sole_source

spec/models/importers/mhc/conversion_employer_plan_year_create_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18643](https://devops.dchbx.org/redmine/issues/18643) |
=> 18643: Add conversion script to load conversion employers

app/helpers/insured/employee_roles_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:Time keeper adjustment

app/controllers/products/qhp_controller.rb, spec/controllers/products/qhp_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> 18976: Fixed Spec failures

app/models/carrier_profile.rb, app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Revert refactor on development

app/helpers/broker_agencies/quote_helper.rb, app/helpers/config/aca_helper.rb, app/helpers/employers/employer_helper.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/employer_profiles/my_account/_home_tab.html.erb, app/views/shared/_reference_plans_list.html.erb, config/settings.yml, features/step_definitions/employers_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Release ma 1

app/controllers/products/qhp_controller.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/insured/plan_shoppings/show.html.erb, app/views/products/qhp/summary.js.erb, spec/controllers/products/qhp_controller_spec.rb, spec/views/employers/plan_years/plan_details/plan_details.html.erb_spec.rb, spec/views/insured/plan_shoppings/show.html.erb_spec.rb, spec/views/products/qhp/summary.js.erb_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Enhancement 18976 1

app/controllers/events/brokers_controller.rb, app/views/events/brokers/_individual.xml.haml, app/views/events/brokers/created.xml.haml, app/views/events/individuals/_individual.xml.haml, spec/controllers/events/brokers_controller_spec.rb, spec/views/events/brokers/created.xml.haml_spec.rb, spec/views/events/individuals/created.xml.haml_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Updating template 18749

app/models/carrier_profile.rb, app/models/carrier_service_area.rb, app/models/employer_profile.rb, app/models/importers/mhc/conversion_employer_plan_year.rb, spec/models/importers/mhc/conversion_employer_plan_year_create_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Flickeringtest

app/models/observers/notice_observer.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18961](https://devops.dchbx.org/redmine/issues/18961) |
| Due Date | 10/16/2017  |
=> 18961: MRG006 / MPI Code SHOP_M006 - Generate Notice when Renewal Employer publishes their renewal plan year - P3.2

app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, components/notifier/app/models/notifier/merge_data_models/plan_year.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18944](https://devops.dchbx.org/redmine/issues/18944) |
| Due Date | 10/16/2017  |
=> 18944: MRG019 / MPI Code SHOP_M019 - Renewal Failed Minimum Requirement - P3.1

app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, components/notifier/app/models/notifier/merge_data_models/plan_year.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18942](https://devops.dchbx.org/redmine/issues/18942) |
| Due Date | 10/16/2017  |
=> 18942: MRG004 / MPI Code SHOP_M004 - Group Renewal Benefit Package Available P3.1

app/helpers/config/aca_helper.rb, app/views/shared/_edit_reference_plans_list.html.erb, app/views/shared/_reference_plans_list.html.erb, config/settings.yml
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref: address reference plans carrier loading

app/models/observers/observer.rb, components/notifier/app/models/notifier/notice_builder.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17404](https://devops.dchbx.org/redmine/issues/17404) |
| Ticket Author | @ipublic |
=> 17404: Refactor notice generation into an engine

app/controllers/employers/plan_years_controller.rb, app/models/benefit_group.rb, app/models/carrier_profile.rb, app/models/carrier_service_area.rb, app/models/employer_profile.rb, app/models/importers/mhc/conversion_employer_plan_year.rb, app/models/importers/mhc/conversion_employer_plan_year_create.rb, app/models/queries/employer_plan_offering_strategies/for_service_area.rb, spec/factories/carrier_service_area.rb, spec/models/carrier_profile_spec.rb, spec/models/carrier_service_area_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 18643

app/models/queries/employer_plan_offering_strategies/for_service_area.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:19145 ticket fix after merging into dev

app/views/events/brokers/_individual.xml.haml, app/views/events/brokers/created.xml.haml, spec/controllers/events/brokers_controller_spec.rb, spec/views/events/brokers/created.xml.haml_spec.rb, spec/views/events/individuals/created.xml.haml_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Updating template 18749 new

app/models/carrier_service_area.rb, app/models/employer_profile.rb, app/models/organization.rb, spec/models/carrier_profile_spec.rb, spec/models/organization_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> carrier plan discrepancy fixes

app/assets/javascripts/plan_year_selection.js.erb, app/views/employers/plan_years/calc_employer_contributions.js.erb, app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/employers/plan_years/reference_plans.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19322](https://devops.dchbx.org/redmine/issues/19322) |
=> 19322: Issue With Selecting Change Reference Plan

app/models/benefit_group.rb, spec/models/benefit_group_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19353](https://devops.dchbx.org/redmine/issues/19353) |
| Ticket Author | @harshaellanki |
=> 19353: Bronze plans  in One carrier 

app/views/employers/employer_profiles/my_account/_benefits.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19351](https://devops.dchbx.org/redmine/issues/19351) |
=> 19351: Messaging around 1/1/18 Benefit Package Creation

app/helpers/config/aca_helper.rb, app/views/shared/_reference_plans_list.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19354](https://devops.dchbx.org/redmine/issues/19354) |
=> 19354: ER Edit/Create PY Page - Update Description of Choice Models to Align with MA-specific policies

spec/models/model_events/renewal_application_submitted_notification_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #18961 #19352. Addressed the spec failure

app/assets/javascripts/application.js.erb, app/assets/javascripts/plan_year_selection.js.erb, app/assets/stylesheets/new.scss.erb, app/controllers/employers/plan_years_controller.rb, app/helpers/config/aca_helper.rb, app/models/benefit_group.rb, app/models/carrier_profile.rb, app/models/carrier_service_area.rb, app/models/employer_profile.rb, app/models/organization.rb, app/models/queries/employer_plan_offering_strategies/for_service_area.rb, app/views/employers/plan_years/_carriers_list.html.erb, app/views/employers/plan_years/_form.html.erb, app/views/employers/plan_years/calc_employer_contributions.js.erb, app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/employers/plan_years/generate_health_carriers_and_plans.js.erb, app/views/employers/plan_years/plan_selection/_plan_details.html.erb, app/views/employers/plan_years/recommend_dates.js.erb, app/views/employers/plan_years/reference_plans.js.erb, app/views/shared/_dental_reference_plans_list.html.erb, app/views/shared/_reference_plans_list.html.erb, config/routes.rb, config/settings.yml, spec/controllers/employers/plan_years_controller_spec.rb, spec/factories/benefit_groups.rb, spec/factories/carrier_service_area.rb, spec/models/carrier_profile_spec.rb, spec/models/carrier_service_area_spec.rb, spec/models/organization_spec.rb
* (19322)
* ()
* ()
```
```
*
---
---
=> Bug 19322 master

spec/factories/benefit_groups.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:assign address SIC code factor set value plan creation

app/models/factories/plan_year_renewal_factory.rb, app/models/importers/conversion_employer.rb, app/models/importers/conversion_employer_set.rb, app/models/importers/mhc/conversion_employer.rb, app/models/importers/mhc/conversion_employer_set.rb, spec/models/importers/conversion_employer_set_spec.rb, spec/models/importers/conversion_employer_update_spec.rb, spec/models/importers/mhc/conversion_employer_create_spec.rb, spec/models/importers/mhc/conversion_employer_plan_year_create_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 18643 new

app/models/benefit_group.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref#19068 ref#17314 conflict resolved

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17583 updated primary nav links

app/assets/javascripts/register.js, app/assets/stylesheets/forms.scss.erb, app/assets/stylesheets/signup.scss.erb, app/controllers/users/passwords_controller.rb, app/controllers/users_controller.rb, app/data_migrations/define_permissions.rb, app/models/effective/datatables/user_account_datatable.rb, app/models/permission.rb, app/policies/user_policy.rb, app/views/devise/passwords/edit.html.erb, app/views/users/_reset_password.html.erb, app/views/users/reset_password.js.erb, config/routes.rb, features/admin/reset_password.feature, features/admin/user_lockable.feature, features/step_definitions/edit_dob_ssn_steps.rb, features/step_definitions/integration_steps.rb, features/step_definitions/lockable_steps.rb, lib/tasks/define_permissions.rake, spec/controllers/users_controller_spec.rb, spec/factories/permission.rb, spec/routing/user_routing_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> User story 16688 master

app/assets/javascripts/plan_year_selection.js.erb, app/assets/stylesheets/new.scss.erb, app/controllers/employers/plan_years_controller.rb, app/helpers/config/aca_helper.rb, app/models/benefit_group.rb, app/models/carrier_profile.rb, app/models/carrier_service_area.rb, app/models/organization.rb, app/models/queries/employer_plan_offering_strategies/for_service_area.rb, app/views/employers/plan_years/_benefit_group_summary.html.erb, app/views/employers/plan_years/_carriers_list.html.erb, app/views/employers/plan_years/_form.html.erb, app/views/employers/plan_years/calc_offered_plan_contributions.js.erb, app/views/employers/plan_years/generate_health_carriers_and_plans.js.erb, app/views/employers/plan_years/reference_plans.js.erb, app/views/shared/_dental_reference_plans_list.html.erb, app/views/shared/_reference_plans_list.html.erb, config/routes.rb, config/settings.yml, spec/controllers/employers/plan_years_controller_spec.rb, spec/models/benefit_group_spec.rb, spec/models/carrier_profile_spec.rb, spec/models/organization_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Carrier name restrictions new

app/assets/javascripts/plan_year_selection.js.erb, app/models/organization.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Qa cleanlog with master

app/models/concerns/observable.rb, app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, app/models/observers/observer.rb, app/models/time_keeper.rb, spec/models/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18950](https://devops.dchbx.org/redmine/issues/18950) |
| Due Date | 11/22/2017  |
=> 18950: MRG025 / MPI Code SHOP_M025 - Employer Reminder to Publish (2 days prior to final hard system deadline of the 15th)- P3.2

db/seedfiles/notice_triggers_seed.rb
This reverts commit 050e1b90bf768400b906e479e0f478233aa31446.
* (Required!)
* ()
* ()
```
```
*
---
---
=> Revert "Refs #17809. Removed duplicate SHOP_M040 trigger seed"

db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Missing trigger

db/seedfiles/notice_triggers_seed.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Missing trigger1

lib/tasks/notices/shop_employee_notice_for_all_inputs.rake, spec/lib/tasks/notices/shop_employee_notice_for_all_inputs_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19185](https://devops.dchbx.org/redmine/issues/19185) |
=> 19185: Trigger Notice MAE029 

app/models/observers/notice_observer.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> removed the typo

app/models/concerns/observable.rb, app/models/observers/notice_observer.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #18950 Fix for observable concern

app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, spec/models/model_events/plan_year_auto_published_notification_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18952](https://devops.dchbx.org/redmine/issues/18952) |
| Due Date | 11/29/2017  |
=> 18952: MRG007 / MPI Code SHOP_M007 - Generate Notice when Employer plan year is auto-published - P3.3

app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, app/models/observers/observer.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Notice 18949 new

spec/models/model_events/plan_year_auto_published_notification_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #18952. fixed the failing spec

app/models/importers/mhc/conversion_employee_set.rb, app/models/importers/mhc/conversion_employer_plan_year.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20148](https://devops.dchbx.org/redmine/issues/20148) |
=> 20148: 2/1 TUFTS Premier Data Load

app/models/observers/notice_observer.rb, spec/models/model_events/employee_renewal_enrollment_confirmation_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18951](https://devops.dchbx.org/redmine/issues/18951) |
| Due Date | 11/22/2017  |
=> 18951: MRE071 / MPI Code SHOP_M071 - Employee Plan Enrollment Confirmation (Renewal Group Open Enrollment – Confirmation of Enrollment) P3.3

components/notifier/app/models/notifier/builders/employer_profile.rb, components/notifier/app/models/notifier/merge_data_models/employer_profile.rb, components/notifier/app/models/notifier/merge_data_models/token_builder.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:add missing template element

app/models/importers/mhc/conversion_employer_plan_year.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 20148 new

app/helpers/config/site_helper.rb, app/views/notices/shop_employer_notices/low_enrollment_notice_for_employer.html.erb, config/settings.yml
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17086. Used proper helper

Gemfile.lock, app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, components/notifier/app/controllers/notifier/notice_kinds_controller.rb, components/notifier/app/models/notifier/builders/employee_profile.rb, components/notifier/app/models/notifier/notice_builder.rb, script/cobra_enrollment_report.rb, spec/models/model_events/employee_renewal_enrollment_confirmation_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 18751 new 1

Gemfile.lock, app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, script/cobra_enrollment_report.rb, spec/models/model_events/plan_year_auto_published_notification_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Feature 18952 new

app/data_migrations/upload_notice_to_employer_account.rb, lib/tasks/upload_notice_to_employer_account.rake, spec/data_migrations/upload_notice_to_employer_account_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19579](https://devops.dchbx.org/redmine/issues/19579) |
| Due Date | 12/05/2017  |
| Ticket Author | Nina Dubuisson |
=> 19579: Prod - Upload ER Denial Notice

app/models/model_events/plan_year.rb, app/models/observers/notice_observer.rb, spec/models/model_events/employee_renewal_enrollment_confirmation_spec.rb
Conflicts:
app/models/observers/notice_observer.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:18951 added trigger to generate notice to emoloyees

app/models/plan_year.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs 17118 removed unwanted transition

app/models/plan.rb, spec/models/plan_spec.rb
Conflicts:
app/models/plan.rb conflicts on line 66-73, kept the branch changes
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:19028 added attributes to plan model as per ticket

app/data_migrations/update_plan_year_conversion_flag.rb, lib/tasks/migrations/populate_conversion_flag.rake, lib/tasks/migrations/update_conversion_flag.rake, lib/tasks/migrations/update_conversion_flag_on_plan_year.rake, spec/data_migrations/update_conversion_flag_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19898](https://devops.dchbx.org/redmine/issues/19898) |
=> 19898: Add Conversion Flag to 1/1/2018 Tufts Premier Conversion Groups Already Existing in EA

app/models/factories/family_enrollment_renewal_factory.rb, app/models/factories/plan_year_renewal_factory.rb, app/models/plan.rb, app/models/renewal_plan_mapping.rb, spec/models/plan_spec.rb, spec/models/renewal_plan_mapping_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19809](https://devops.dchbx.org/redmine/issues/19809) |
=> 19809: Passive Renewal Query Update

app/models/factories/family_enrollment_renewal_factory.rb, app/models/factories/plan_year_renewal_factory.rb, app/models/plan.rb, app/models/renewal_plan_mapping.rb, lib/tasks/tufts_renewal_plan_mapping.rake, spec/models/plan_spec.rb, spec/models/renewal_plan_mapping_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20252](https://devops.dchbx.org/redmine/issues/20252) |
=> 20252: Plan Mapping Rake

app/notices/notice.rb, app/notices/pdf_templates/employer_notice.rb, app/notices/shop_employer_notice.rb, app/notices/shop_employer_notices/initial_employer_reminder_to_publish_plan_year.rb, lib/tasks/notices/shop_employer_notice.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18529](https://devops.dchbx.org/redmine/issues/18529) |
=> 18529: Trigger notice MIG028 

app/data_migrations/upload_notice_to_employer_account.rb, lib/tasks/upload_notice_to_employer_account.rake, spec/data_migrations/upload_notice_to_employer_account_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Support 19579 new

spec/models/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb, spec/models/model_events/renewal_plan_year_first_reminder_before_soft_deadline_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #18950, Refs #18955. db:truncation except translations

app/models/hbx_enrollment.rb, app/models/model_events/hbx_enrollment.rb, app/models/observers/notice_observer.rb, features/step_definitions/conversion_employee_steps.rb, features/step_definitions/integration_steps.rb, spec/models/model_events/employee_plan_coverage_selected_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18941](https://devops.dchbx.org/redmine/issues/18941) |
| Due Date | 11/22/2017  |
=> 18941: MAE069/MPI SHOP_M069 - Employee Plan Selection Confirmation (New hires and SEPs) P3.1

features/employers/step_definitions/employer_attestation_steps.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #15183. addressed the pending cucumber

config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20585](https://devops.dchbx.org/redmine/issues/20585) |
=> 20585: Enrollments prematurely sent to HPHC before go live

app/data_migrations/delete_single_invoice_with_fein.rb, lib/tasks/migrations/delete_single_invoice_with_fein.rake, spec/data_migrations/delete_single_invoice_with_fein_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20142](https://devops.dchbx.org/redmine/issues/20142) |
=> 20142: Remove January 2018 Invoice from ER Account- HKD Treatment Options

app/invoices/employer_invoice.rb, app/models/employer_profile.rb, spec/factories/organizations.rb, spec/invoices/employer_invoice_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20593](https://devops.dchbx.org/redmine/issues/20593) |
=> 20593: Trigger Update - MIG022 (17093) - Do Not Trigger "Invoice Available" notice for conversion employers with a renewal plan year

app/helpers/config/site_helper.rb, app/invoices/employer_invoice.rb, app/invoices/invoice_helper.rb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20591](https://devops.dchbx.org/redmine/issues/20591) |
=> 20591: Invoice (MIG031 - 17220) includes Incorrect Text and Due Date for Conversion ERs

spec/models/hbx_enrollment_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> hbx_enrollment spec fix

app/controllers/employers/employer_profiles_controller.rb, spec/controllers/employers/employer_profiles_controller_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19546](https://devops.dchbx.org/redmine/issues/19546) |
| Ticket Author | @ymhari |
=> 19546: ER- Revert Plan Year "Renew Enrollment Status" column  issue in employee roster.

app/helpers/config/site_helper.rb
This reverts commit 1e35c6f5201a03e565299a316f9e16076dea21e6.
* (Required!)
* ()
* ()
```
```
*
---
---
=> Revert "ref#18821 use site_registration_path if AWS_ENV is prod"

app/helpers/config/site_helper.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Refs #17764. Removed duplicate helper commit: dfe6eb3

app/assets/javascripts/security_question.js.coffee, app/controllers/users/security_question_responses_controller.rb, app/views/users/security_question_responses/_edit_modal.html.erb, app/views/users/security_question_responses/_filter_security_questions.html.erb, config/routes.rb, features/employee/conversion_employee.feature, features/step_definitions/security_question_step.rb, spec/controllers/users/security_question_responses_controller_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> ref:18124 rebased with UAT_Release Same Security Question is triggerred multiple times

app/controllers/application_controller.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> set default header

components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals_controller.rb, components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_proposal.rb, components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/publish_quote.html.erb, components/sponsored_benefits/config/routes.rb, components/sponsored_benefits/spec/models/sponsored_benefits/organizations/plan_design_proposal_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20112](https://devops.dchbx.org/redmine/issues/20112) |
| Ticket Author | Raymond Lam |
=> 20112: Publish Quote

app/data_migrations/update_user_or_person_records.rb, spec/data_migrations/update_user_or_person_records_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20403](https://devops.dchbx.org/redmine/issues/20403) |
=> 20403: MA User Name Rake Error

app/models/forms/broker_agency_profile.rb, lib/tasks/migrations/add_phones_to_people.rake, spec/models/forms/broker_agency_profile_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19985](https://devops.dchbx.org/redmine/issues/19985) |
| Ticket Author | Heather Cloran |
=> 19985: Broker Can't Login

spec/models/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb, spec/models/model_events/renewal_plan_year_first_reminder_before_soft_deadline_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Flickering spec 15183 new

lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19903](https://devops.dchbx.org/redmine/issues/19903) |
=> 19903: Broker Magic URL Report - Wrong domain for magic URLs

config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20255](https://devops.dchbx.org/redmine/issues/20255) |
=> 20255: Update Effective Date Availability Business Rule

app/data_migrations/migrate_plan_year.rb, lib/tasks/migrations/migrate_plan_year.rake, spec/data_migrations/migrate_plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20841](https://devops.dchbx.org/redmine/issues/20841) |
=> 20841: MA 1-1-2018 Groups that did not renew

app/helpers/config/aca_helper.rb, app/views/employers/employer_profiles/my_account/_benefits.html.erb, app/views/employers/plan_years/_claim_quote_modal.html.erb, components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals_controller.rb, components/sponsored_benefits/app/models/sponsored_benefits/benefit_applications/benefit_application.rb, components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_proposal.rb, components/sponsored_benefits/config/routes.rb, config/routes.rb, config/settings.yml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20116](https://devops.dchbx.org/redmine/issues/20116) |
| Ticket Author | Raymond Lam |
=> 20116: Claim Quote 

config/settings.yml
* (Required!)
* ()
* ()
```
```
*
---
---
=> added missing site helpers in uat

app/data_migrations/move_employer_staff_role_between_two_people.rb, app/data_migrations/move_user_account_between_two_people_accounts.rb, lib/tasks/migrations/move_employer_staff_role_between_two_people.rake, lib/tasks/move_user_account_between_two_people_accounts.rake, spec/data_migrations/move_employer_staff_role_between_two_people_spec.rb, spec/data_migrations/move_user_account_between_two_people_accounts_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20707](https://devops.dchbx.org/redmine/issues/20707) |
=> 20707: Merge User Records - Rake task

app/models/employer_profile.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20217](https://devops.dchbx.org/redmine/issues/20217) |
| Ticket Author | @harshaellanki |
=> 20217: Auto publish Plan Year

app/assets/javascripts/employer_profile.js, app/views/employers/plan_years/calc_offered_plan_contributions.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20626](https://devops.dchbx.org/redmine/issues/20626) |
| Ticket Author | Heather Cloran |
=> 20626: Cannot get feb rates and jan are displayed

project_gems/effective_datatables-2.6.14/app/views/effective/datatables/_bulk_actions_column.html.haml
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20549](https://devops.dchbx.org/redmine/issues/20549) |
=> 20549:  PVT - Notice Engine functionality is not working, it throws “We are sorry“ message.

app/models/employer_profile.rb, app/models/plan_year.rb, app/models/queries/named_policy_queries.rb, app/models/queries/shop_monthly_enrollments.rb, config/settings.yml, script/shop_sep_query.rb, spec/models/plan_year_spec.rb, spec/models/queries/shop_monthly/monthly_quiet_period_enrollments_query_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> Enhancement 20201 new

app/data_migrations/cancel_plan_year.rb, lib/tasks/cancel_plan_year.rake, spec/data_migrations/cancel_plan_year_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21211](https://devops.dchbx.org/redmine/issues/21211) |
=> 21211: MA 1-1-2018  Initial Groups That New Plan Year Transitioned to Cancelled 

app/views/shared/_my_portal_links.html.erb, db/seedfiles/english_translations_seed.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21720](https://devops.dchbx.org/redmine/issues/21720) |
| Ticket Author | SM Kelley |
=> 21720: BQT: Mary Jane Lenhardt 

app/views/notices/shared/_address.html.erb, app/views/user_mailer/employee_ineligibility_notice.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18677](https://devops.dchbx.org/redmine/issues/18677) |
| Ticket Author | Jennifer Nelson-Samuel |
=> 18677: Notices- "Notice No." needs to be removed from all notices

app/views/devise/registrations/new.html.erb, features/employers/cobra.feature, features/employers/step_definitions/cobra_steps.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18718](https://devops.dchbx.org/redmine/issues/18718) |
| Ticket Author | @ymhari |
=> 18718: QA- UAT Email(Optional) field is missing in Signup page 

config/settings.yml, spec/factories/organizations.rb, spec/factories/plan_years.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21514](https://devops.dchbx.org/redmine/issues/21514) |
=> 21514: OE_Start on System Setting Change

components/sponsored_benefits/app/views/sponsored_benefits/census_members/plan_design_census_employees/_member_fields.html.erb, components/sponsored_benefits/app/views/sponsored_benefits/census_members/plan_design_census_employees/new.js.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21778](https://devops.dchbx.org/redmine/issues/21778) |
=> 21778: Prod - BQT EE Census DOBs Incorrect

app/data_migrations/change_enrollment_details.rb, app/data_migrations/change_renewing_plan_year_aasm_state.rb, app/data_migrations/update_benefit_group_finalize_composite_rate.rb, app/data_migrations/update_conversion_flag.rb, app/models/hbx_enrollment.rb, lib/tasks/migrations/change_enrollment_details.rake, lib/tasks/migrations/change_renewing_plan_year_aasm_state.rake, lib/tasks/migrations/update_benefit_group_finalize_composite_rate.rake, spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb, spec/data_migrations/change_enrollment_details_spec.rb, spec/data_migrations/update_benefit_group_finalize_composite_rate_spec.rb, spec/data_migrations/update_conversion_flag_spec.rb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20657](https://devops.dchbx.org/redmine/issues/20657) |
=> 20657: Transition 1/1/2018 Groups to "Renewing_Enrolling"

app/models/employer_profile.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> employer transmit setting fix

app/helpers/l10n_helper.rb, app/views/insured/families/_shop_for_plans_widget.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21827](https://devops.dchbx.org/redmine/issues/21827) |
=> 21827: Admin: Family Tab - Employee "Code Appears"

app/views/shared/_my_portal_links.html.erb
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22010](https://devops.dchbx.org/redmine/issues/22010) |
=> 22010: BQT - Broker Error Messages

spec/models/model_events/renewal_plan_year_first_reminder_before_soft_deadline_spec.rb
* (Required!)
* ()
* ()
```
```
*
---
---
=> jenkins spec fix.
