health-connector/enroll

db/seedfiles/notice_triggers_seed.rb

* (Required!)
* ()
* ()
```
```
*
---
---

removed the duplicate trigger seed

---

db/seedfiles/notice_triggers_seed.rb

* (Required!)
* ()
* ()
```
```
*
---
---

removed duplicate code from trigger seed

---

app/models/plan_year.rb

* (Required!)
* ()
* ()
```
```
*
---
---

removed initial_employee_plan_selection_confirmation method

---

app/controllers/insured/employee_roles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21786](https://devops.dchbx.org/redmine/issues/21786) |

21786: Admin: Family tab - New Employee Paper Application link - 'We're sorry, but something went wrong.' issue

---

config/settings.yml
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22100](https://devops.dchbx.org/redmine/issues/22100) |

22100: Settings Update: OE_Start on System Setting Change

---

components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22083](https://devops.dchbx.org/redmine/issues/22083) |

22083: BQT - One Plan Quote won't save

---

components/sponsored_benefits/app/controllers/sponsored_benefits/census_members/plan_design_census_employees_controller.rb
components/sponsored_benefits/app/models/effective/datatables/plan_design_employee_datatable.rb
components/sponsored_benefits/app/models/sponsored_benefits/forms/census_employee_import.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21834](https://devops.dchbx.org/redmine/issues/21834) |

21834: Date display issues in BQT roster

---

app/data_migrations/change_er_to_applicant_state.rb
lib/tasks/change_er_to_applicant_state.rake
spec/data_migrations/change_er_to_applicant_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21784](https://devops.dchbx.org/redmine/issues/21784) |

21784: ERs did not renew

---

components/transport_profiles/app/models/transport_profiles/processes/legacy/transfer_payment_processor_reports.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22308](https://devops.dchbx.org/redmine/issues/22308) |

22308: Endpoints defined in 18811 reference incorrect endpoints

---

app/models/plan_year.rb
config/settings.yml
spec/models/model_events/ineligible_renewal_application_submitted_notification_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22252](https://devops.dchbx.org/redmine/issues/22252) |

22252: Settings Update 2: OE_start on System Date Change

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Changed renewing application quiet period end date setting

---

app/helpers/application_helper.rb
app/models/hbx_enrollment.rb
app/notices/shop_employee_notices/employee_select_plan_during_open_enrollment.rb
spec/helpers/application_helper_spec.rb
spec/models/hbx_enrollment_spec.rb
spec/notices/shop_employee_notices/employee_select_plan_during_open_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22204](https://devops.dchbx.org/redmine/issues/22204) |

22204: Employee unable purchase Plan  or  Waive coverage 

---

config/cucumber.yml
features/employers/cobra.feature
features/employers/cobra_sole_source.feature
features/employers/employer_attestation.feature
features/employers/employer_attestation_sole_source.feature

* (Required!)
* ()
* ()
```
```
*
---
---

Temp attestation fix

---

lib/tasks/datafix_update_broker_role_to_exisiting_user.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22201](https://devops.dchbx.org/redmine/issues/22201) |

22201: Link Broker Account to HBX ID 101802

---

app/models/concerns/config/aca_model_concern.rb
app/models/plan_year.rb
config/cucumber.yml
config/settings.yml
features/employers/cobra.feature
features/employers/cobra_sole_source.feature
features/employers/employer_attestation.feature
features/employers/employer_attestation_sole_source.feature
spec/data_migrations/create_new_initial_plan_year_using_another_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21648](https://devops.dchbx.org/redmine/issues/21648) |

21648: Revert OE System Setting Change

---

spec/models/hbx_enrollment_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Sink 1.0 uat

---

spec/models/hbx_enrollment_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Sink 3.0.3

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/shared/_pdp_plan_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/show.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22298](https://devops.dchbx.org/redmine/issues/22298) |

22298: BQT - Quote Download Link not working on Published Quote page

---

app/views/shared/plan_shoppings/_sbc_link.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/shared/_pdp_plan_details.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22499](https://devops.dchbx.org/redmine/issues/22499) |

22499: View SBC link on quotes does not work 

---

script/shop_sep_query.rb
spec/script/shop_sep_query_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22643](https://devops.dchbx.org/redmine/issues/22643) |
| Ticket Author | @joseph-kramer |

22643: Enrollments are trying to be transmitted before PY is sent to carrier in MA

---

app/controllers/broker_agencies/profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22447](https://devops.dchbx.org/redmine/issues/22447) |

22447: Sort commission statements within year in descending order (newest first)

---

app/data_migrations/update_benefit_group_finalize_composite_rate.rb
spec/data_migrations/update_benefit_group_finalize_composite_rate_spec.rb
spec/models/factories/enrollment_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22315](https://devops.dchbx.org/redmine/issues/22315) |

22315: Group Throws Error when Accessed - OPPURE OIL FEIN: 46-2608718

---

app/models/benefit_group.rb
lib/tasks/export_employers.rake

This reverts commit ad6df685c8e1856004b89b70887131216ab58458, reversing
changes made to 4428a6a05f58b7ce76da8c3bd49be66fd00f3223.

Revert "Merge branch 'use-case-17310_new' into release"

---

app/helpers/config/aca_helper.rb
app/views/shared/_office_location_fields.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23100](https://devops.dchbx.org/redmine/issues/23100) |

23100: When Zip code is entered it shows the "Zip code outside of DC" text

---

app/helpers/config/aca_helper.rb
app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23152](https://devops.dchbx.org/redmine/issues/23152) |

23152: Calendar

---

app/helpers/config/aca_helper.rb
app/models/concerns/config/aca_model_concern.rb
app/views/exchanges/hbx_profiles/_family_index_datatable.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23145](https://devops.dchbx.org/redmine/issues/23145) |

23145: Employee Paper Application Link from Family page

---

app/helpers/employers/employer_helper.rb
app/models/concerns/config/aca_model_concern.rb
app/models/employer_profile.rb
app/views/shared/organizations/_entity_name_and_type_fields_autofill.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23099](https://devops.dchbx.org/redmine/issues/23099) |

23099: SIC link is displayed while creating the Employer

---

app/controllers/users/sessions_controller.rb
app/helpers/config/aca_helper.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23153](https://devops.dchbx.org/redmine/issues/23153) |

23153: Recaptcha

---

app/helpers/config/aca_helper.rb
app/views/exchanges/hbx_profiles/_configuration_index.html.erb
app/views/layouts/application.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23150](https://devops.dchbx.org/redmine/issues/23150) |

23150: Security Questions

---

app/data_migrations/upload_notice_to_employer_account.rb
lib/tasks/upload_notice_for_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22876](https://devops.dchbx.org/redmine/issues/22876) |
| Ticket Author | Chad Morton |

22876: MASSACHUSETTS Upload Termination Notice to Employer Secured Message Inbox in EA- March 2018

---

app/helpers/config/aca_helper.rb
app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23151](https://devops.dchbx.org/redmine/issues/23151) |

23151: User Accounts

---

app/helpers/config/aca_helper.rb
app/models/concerns/config/aca_model_concern.rb
app/models/effective/datatables/employer_datatable.rb
app/models/plan_year.rb
app/views/employers/employer_profiles/my_account/_documents.html.erb
app/views/employers/plan_years/_publish_modal.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23147](https://devops.dchbx.org/redmine/issues/23147) |

23147: Employer Attestation

---

app/controllers/employers/plan_years_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23305](https://devops.dchbx.org/redmine/issues/23305) |

23305:  Plan Year - "We are sorry message" in ER, EE and IVL Flows 

---

app/helpers/config/aca_helper.rb
app/views/broker_agencies/applicants/_bank_information.html.erb
app/views/broker_agencies/broker_roles/_new_broker_agency_form.html.erb
app/views/broker_agencies/profiles/_menu.html.erb
app/views/broker_agencies/profiles/edit.html.erb
config/settings.yml
db/seedfiles/translations/en/broker_agencies.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23097](https://devops.dchbx.org/redmine/issues/23097) |

23097: On Broker Registration page - ACH Routing Information is displayed

---

app/models/concerns/config/aca_model_concern.rb
app/models/office_location.rb
app/views/employers/employer_profiles/_employer_form.html.erb
app/views/shared/_employer_profile_fields.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Refs 23176 - Remove Communication Pref extra form and fix employer saving

---

spec/models/model_events/renewal_plan_year_first_reminder_before_soft_deadline_spec.rb

fix fickering notice spec

---

app/data_migrations/update_conversion_flag.rb
app/models/employer_attestation.rb
app/models/employer_attestation_document.rb
lib/tasks/migrations/update_conversion_flag.rake
spec/data_migrations/update_conversion_flag_spec.rb
spec/models/employer_attestation_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23013](https://devops.dchbx.org/redmine/issues/23013) |

23013: 4/1 MA enrollment issue

---

app/data_migrations/change_renewing_plan_year_aasm_state.rb
lib/tasks/migrations/change_renewing_plan_year_aasm_state.rake
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23334](https://devops.dchbx.org/redmine/issues/23334) |

23334: Force Publish 4/1 Group - KAM PIZZA

---

app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb
app/views/employers/plan_years/_recommend_dates.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23382](https://devops.dchbx.org/redmine/issues/23382) |

23382: Update DC application dead line to take DC settings.

---

lib/tasks/plans/import_provider_and_rx_formulary_url.rake

* (Required!)
* ()
* ()
```
```
*
---
---

Fix rake task that updates plan attributes from master xml.

---

app/controllers/users/registrations_controller.rb
app/helpers/portal_header_helper.rb
config/locales/devise.en.yml
db/seedfiles/translations/en/welcome_index.rb
features/step_definitions/security_question_step.rb
spec/mailers/user_mailer_spec.rb
spec/models/plan_year_spec.rb
spec/notices/shop_employer_notices/initial_employer_denial_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23339](https://devops.dchbx.org/redmine/issues/23339) |

23339: should disable all MA flash messages and notices template as well. 

---

db/seedfiles/notice_triggers_seed.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix conflict issue

---

lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23140](https://devops.dchbx.org/redmine/issues/23140) |
| Ticket Author | Saadi Mirza |

23140: Create a report to compare SHOP anniversary EA enrollments with EDI outbound

---

app/views/broker_agencies/profiles/_menu.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23306](https://devops.dchbx.org/redmine/issues/23306) |

23306: Admin - Broker Agency - "Assign" tab and "Quoting Tool" tabs are missing

---

app/views/broker_agencies/profiles/_menu.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23467](https://devops.dchbx.org/redmine/issues/23467) |

23467: Broker account page  - "Brokers", "Agency Mail" links should be disabled 

---

app/views/insured/families/_apply_for_medicaid_widget.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23299](https://devops.dchbx.org/redmine/issues/23299) |

23299: Employee Plan shopping page HTML issues 

---

app/helpers/config/aca_helper.rb
app/models/concerns/config/aca_model_concern.rb
app/models/effective/datatables/employee_datatable.rb
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
components/sponsored_benefits/app/models/effective/datatables/plan_design_employee_datatable.rb
config/settings.yml
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23503](https://devops.dchbx.org/redmine/issues/23503) |

23503: Add missing Plan Matching Tool to Census Employee Roster and Remove Est Participation column

---

app/models/effective/datatables/employer_datatable.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23495](https://devops.dchbx.org/redmine/issues/23495) |

23495: "View Username and Email" button does not work for admin

---

db/seedfiles/admins_seed.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23552](https://devops.dchbx.org/redmine/issues/23552) |
| Ticket Author | @antonioschaffert |

23552: Fix Dev Seed for IVL Market 2018

---

app/data_migrations/update_all_plan_options.rb
lib/tasks/update_plan_offerings_at_carrier_level.rake
spec/data_migrations/update_all_plan_options_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23511](https://devops.dchbx.org/redmine/issues/23511) |
| Ticket Author | Sheheryar Tariq |

23511: Update is_vertical and is_horizontal fields in Plan Model for DC plans

---

app/helpers/config/aca_helper.rb
app/invoices/employer_invoice.rb
app/models/organization.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23497](https://devops.dchbx.org/redmine/issues/23497) |

23497: Invoiced indication does not work when admin generate invoice for employers

---

components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23514](https://devops.dchbx.org/redmine/issues/23514) |

23514: Issues with Broker selection

---

app/assets/stylesheets/modules.scss.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23448](https://devops.dchbx.org/redmine/issues/23448) |

23448: On consumer Documents view is not displaying properly

---

lib/object_builders/qhp_rate_builder.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23554](https://devops.dchbx.org/redmine/issues/23554) |

23554: Populate plan premium tables

---

app/views/insured/employee_roles/_select_employer.html.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23520](https://devops.dchbx.org/redmine/issues/23520) |

23520: Enroll as individual button missing for new registration employee

---

app/views/insured/group_selection/terminate_confirm.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23522](https://devops.dchbx.org/redmine/issues/23522) |
| Ticket Author | @nisanthyaganti9 |

23522: IVL market should not have 14 day rule when terminating policy.

---

app/assets/javascripts/employer_profile.js.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23572](https://devops.dchbx.org/redmine/issues/23572) |

23572: Text changes under Employer Plan selection

---

app/models/concerns/config/aca_model_concern.rb
app/models/employer_profile.rb
spec/models/concerns/config/aca_model_concern_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23413](https://devops.dchbx.org/redmine/issues/23413) |

23413: Move employer monthly transmission settings into concerns

---

app/helpers/config/aca_helper.rb
app/views/employers/employer_profiles/my_account/_billing.html.erb
config/settings.yml
spec/views/employers/employer_profiles/_billing.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23489](https://devops.dchbx.org/redmine/issues/23489) |

23489: Employer with active plan year "Billing" page 

---

app/views/shared/engines/_broker_menu.html.erb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/broker_agency_profiles_controller.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23468](https://devops.dchbx.org/redmine/issues/23468) |

23468: when broker click "employers" button should see general agency selection section

---

app/models/concerns/config/aca_model_concern.rb
app/models/employer_profile.rb
config/settings.yml
spec/models/concerns/config/aca_model_concern_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Refs 23413. corrected class methods name

---

app/assets/javascripts/plan_year_selection.js.erb
app/views/employers/plan_years/calc_offered_plan_contributions.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23575](https://devops.dchbx.org/redmine/issues/23575) |

23575: Issues with Dental Plans-Benefit package 

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23470](https://devops.dchbx.org/redmine/issues/23470) |

23470: Broker page should disable "Add Prospect Employer" button

---

app/assets/stylesheets/_variables.scss.erb
app/assets/stylesheets/insured.scss.erb
app/assets/stylesheets/text_styles.scss.erb
app/views/insured/families/_qle_detail.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23585](https://devops.dchbx.org/redmine/issues/23585) |

23585: Text & Color changes - IVL/EE account

---

config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23592](https://devops.dchbx.org/redmine/issues/23592) |
| Ticket Author | @nisanthyaganti9 |

23592: 500 error when admin clicked on call hub on documents tab.

---

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23476](https://devops.dchbx.org/redmine/issues/23476) |

23476: Outstanding verification's link under Families tab

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23622](https://devops.dchbx.org/redmine/issues/23622) |
| Ticket Author | @nisanthyaganti9 |

23622: Admin actions - Add SEP, Edit DOB/SSN, View Username and Email should be disabled under Families tab in MA

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23622](https://devops.dchbx.org/redmine/issues/23622) |
| Ticket Author | @nisanthyaganti9 |

23622: Admin actions - Add SEP, View Username and Email should be disabled under Families tab in MA

---

app/models/concerns/config/aca_model_concern.rb
app/models/employer_profile.rb
config/settings.yml
spec/models/concerns/config/aca_model_concern_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Sink 3.0.10

---

app/controllers/broker_agencies/profiles_controller.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23027](https://devops.dchbx.org/redmine/issues/23027) |
| Ticket Author | Julie Manuszak |

23027: Information updates not saving under MA Broker Agency account

---

app/views/insured/plan_shoppings/_plan_details.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23603](https://devops.dchbx.org/redmine/issues/23603) |

23603: DC PVT -  IVL and EE - Network and Deductible Alignment issues

---

app/helpers/portal_header_helper.rb
db/seedfiles/translations/en/welcome_index.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23092](https://devops.dchbx.org/redmine/issues/23092) |

23092: MA Logo, MA Admin Tool Format, Colors 

---

app/assets/javascripts/plan_year_selection.js.erb
app/controllers/employers/plan_years_controller.rb
app/views/employers/plan_years/generate_health_carriers_and_plans.js.erb
app/views/shared/_reference_plans_list.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23621](https://devops.dchbx.org/redmine/issues/23621) |

23621: Plans not loading when Employer add multiple benefit groups

---

app/views/employers/census_employees/_enrollment_details.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19187](https://devops.dchbx.org/redmine/issues/19187) |

19187: ER Per-Member Premium Display

---

app/models/concerns/config/bank_holidays_helper.rb
app/models/plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23571](https://devops.dchbx.org/redmine/issues/23571) |

23571: Issue with payment deadline

---

app/models/benefit_group.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23641](https://devops.dchbx.org/redmine/issues/23641) |

23641: We are sorry error on creating plan year with meta level plans

---

app/models/importers/conversion_employer_plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23532](https://devops.dchbx.org/redmine/issues/23532) |

23532: New hire coverage policy should apply on 6/1 conversion employer

---

app/controllers/insured/employee_roles_controller.rb

* (Required!)
* ()
* ()
```
```
*
---
---

rescue fix

---

app/models/observers/observer.rb
components/notifier/app/models/notifier/application_event_mapper.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22857](https://devops.dchbx.org/redmine/issues/22857) |
| Ticket Author | @Battula |

22857: Add new resources to Application Event Mapper in Notice Engine

---

app/views/employers/employer_profiles/_download_new_template.html.erb
app/views/employers/employer_profiles/_upload_employees.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23692](https://devops.dchbx.org/redmine/issues/23692) |

23692: We are sorry error with Employee roster template upload

---

app/models/observers/observer.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23691](https://devops.dchbx.org/redmine/issues/23691) |
| Ticket Author | Sheheryar Tariq |

23691: NO Group Files Dropping in DC PVT 

---

app/helpers/config/aca_helper.rb
app/helpers/config/site_helper.rb
app/views/employers/employer_profiles/my_account/_broker_agency.html.erb
app/views/shared/_benefit_group_fields.html.erb
app/views/shared/_plan_year_fields.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23561](https://devops.dchbx.org/redmine/issues/23561) |

23561: Issue on Employer account

---

app/views/employers/plan_years/calc_offered_plan_contributions.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23639](https://devops.dchbx.org/redmine/issues/23639) |

23639: Dental Benefits Tab showing up without selecting under Plan year page

---

app/models/hbx_enrollment.rb
features/step_definitions/new_hire_steps.rb
features/step_definitions/renewal_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14986](https://devops.dchbx.org/redmine/issues/14986) |

14986: Minimum Participation - Remove Invalid Waiver Reason ("I do not have coverage")

---

app/invoices/employer_invoice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23661](https://devops.dchbx.org/redmine/issues/23661) |

23661: Generated Incorrect Employer Invoice 

---

app/models/employer_profile.rb
spec/models/employer_profile_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23626](https://devops.dchbx.org/redmine/issues/23626) |
| Ticket Author | Saadi Mirza |

23626: Binder paid status is being set without invoking state transition

---

app/helpers/application_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/helpers/application_helper_spec.rb

This reverts commit f713b190e6ffbba2b6839bb0dda2c9a2c454fe57, reversing
changes made to 0a358ac29e7858fe6f387d30de06272d7a0833b4.

Revert "Merge branch 'feature-22964' into qa_rebuild"

---

app/helpers/config/aca_helper.rb
app/helpers/employers/employer_helper.rb
app/models/benefit_group.rb
app/models/concerns/config/aca_model_concern.rb
app/models/plan.rb
app/views/shared/_edit_reference_plans_list.html.erb
app/views/shared/_reference_plans_list.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/carriers/_carriers_list.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_selections/_carrier_options.html.erb
config/settings.yml
spec/controllers/employers/plan_years_controller_spec.rb
spec/models/plan_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21447](https://devops.dchbx.org/redmine/issues/21447) |

21447: ER Plan Year Setup - Employee Detail Costs for One Carrier offering incorrectly includes Bronze plans in EE Cost Ranges

---

app/helpers/application_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/helpers/application_helper_spec.rb

This reverts commit e281590721e2dc9fa3ab2eab6271b3f8dc9982df, reversing
changes made to 6b8d87c05ac669bc797d1efb70ec4971aa278bf0.

Revert "Merge branch 'revert_22964' into qa_rebuild"

---

app/helpers/config/aca_helper.rb
app/reports/hbx_reports/edi_enrollment_termination_report.rb
lib/tasks/employers_failing_minimum_participation.rake
lib/tasks/export_employers.rake
lib/tasks/hbx_reports/brokers.rake
lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake
lib/tasks/hbx_reports/edi_enrollment_termination_report.rake
lib/tasks/hbx_reports/employee_terminations.rake
lib/tasks/hbx_reports/employer_poc_pending_report.rake
lib/tasks/hbx_reports/employer_roster_report.rake
lib/tasks/hbx_reports/employers.rake
lib/tasks/hbx_reports/newly_registered_persons_data_report.rake
spec/reports/hbx_reports/edi_enrollment_termination_report_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21723](https://devops.dchbx.org/redmine/issues/21723) |
| Ticket Author | @ap-dc |

21723: Follow requested file naming convention for SFTP data transfer

---

app/models/importers/mhc/conversion_employer_plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23681](https://devops.dchbx.org/redmine/issues/23681) |

23681: TUFTS Direct - 6/1 Conversion Data Load

---

app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/clear_assign_for_employer.js.erb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/broker_agency_profiles_controller.rb
components/sponsored_benefits/app/models/effective/datatables/broker_agency_employer_datatable.rb
components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb
components/sponsored_benefits/spec/models/sponsored_benefits/organizations/plan_design_organization_spec.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb
spec/factories/favorite_general_agencies.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23717](https://devops.dchbx.org/redmine/issues/23717) |

23717: General agency column missing under Broker account--Employers tab

---

app/assets/stylesheets/_variables.scss.erb
app/assets/stylesheets/custom.scss.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23918](https://devops.dchbx.org/redmine/issues/23918) |
| Ticket Author | Sarah Bagge |

23918: Font change in PVT

---

app/views/insured/families/_qle_detail_for_existing_sep.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23890](https://devops.dchbx.org/redmine/issues/23890) |
| Ticket Author | Grizelda Mejia |

23890: Error on consumers account after adding SEP 

---

app/views/employers/employer_profiles/_employer_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23537](https://devops.dchbx.org/redmine/issues/23537) |

23537: Communication Preferences Doubled

---

app/models/census_employee.rb
app/models/plan_year.rb
spec/models/census_employee_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23439](https://devops.dchbx.org/redmine/issues/23439) |
| Ticket Author | Raymond Lam |

23439: Bug Ticket - Plan Year is Moving to Enroll State Instead of Application Ineligible 

---

app/models/consumer_role.rb
spec/models/consumer_role_spec.rb
spec/models/general_agency_profile_spec.rb
spec/models/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb
spec/rails_helper.rb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Flickering spec ma

---

app/controllers/employers/plan_years_controller.rb
app/helpers/application_helper.rb
app/helpers/insured/group_selection_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
app/views/employers/plan_years/_form.html.erb
app/views/insured/group_selection/new.html.erb
app/views/shared/_signup_progress.html.haml
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_form.html.erb
config/routes.rb
features/step_definitions/employers_steps.rb
spec/controllers/employers/plan_years_controller_spec.rb
spec/factories/plans.rb
spec/helpers/application_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

This reverts commit e5f1daedbad0d471ad13338f802c0e34eae7a7f1, reversing
changes made to d0ec53abd26a8dd4ac8b8f17bbd440c5a24d6211.
Conflicts:
app/views/employers/employer_profiles/_employer_form.html.erb removed the branch changes(duplicate)
config/settings.yml kept the HEAD changes
* (Required!)
* ()
* ()
```
```
*
---
---

Revert "Merge branch 'feature-22966' into release_ma"

---

app/data_migrations/change_username.rb
spec/data_migrations/change_username_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22172](https://devops.dchbx.org/redmine/issues/22172) |

22172: User Name Change Rake

---

app/models/importers/mhc/conversion_employer_plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24108](https://devops.dchbx.org/redmine/issues/24108) |

24108: Tufts Health Direct mapping to match conversion files

---

config/cucumber.yml
config/settings.yml
features/employers/cobra.feature
features/employers/cobra_sole_source.feature
features/employers/employer_attestation.feature
features/employers/employer_attestation_sole_source.feature
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24030](https://devops.dchbx.org/redmine/issues/24030) |

24030: Temporary ER Shopping Start_on Configuration Change

---

app/controllers/employers/plan_years_controller.rb
app/helpers/application_helper.rb
app/helpers/insured/group_selection_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
app/views/employers/plan_years/_form.html.erb
app/views/insured/group_selection/new.html.erb
app/views/shared/_signup_progress.html.haml
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_form.html.erb
config/routes.rb
config/settings.yml
features/employers/cobra.feature
features/employers/cobra_sole_source.feature
features/employers/employer_attestation.feature
features/employers/employer_attestation_sole_source.feature
features/step_definitions/employers_steps.rb
spec/controllers/employers/plan_years_controller_spec.rb
spec/factories/plans.rb
spec/helpers/application_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Revert 24030 22699

---

config/environments/production.rb

This reverts commit 15e97da8803d22859d45ccc21d4f02580b1abdde.
* (Required!)
* ()
* ()
```
```
*
---
---

Revert "Uglifier now has experimental ES6 support"

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21304](https://devops.dchbx.org/redmine/issues/21304) |

21304: Prod - Minimum Requirement Bar Incorrect

---

app/models/plan_cost_decorator.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24303](https://devops.dchbx.org/redmine/issues/24303) |

24303: Production Rates don't match calculator values

---

features/step_definitions/reset_password_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

changing back to last.click

---

components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/templates/templates/default.js

* (Required!)
* ()
* ()
```
```
*
---
---

typo while resolving the conflicts

---

spec/views/general_agencies/_show.html.erb_spec.rb
spec/views/general_agencies/edit.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

master spec fix general agency

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

removing the DC website_name from MA

---

app/models/concerns/authorization_concern.rb
spec/models/user_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18725](https://devops.dchbx.org/redmine/issues/18725) |
| Ticket Author | @ymhari |

18725: QA and UAT  - Reset Password -->  Error message  for invalid email address is displaying Incorrectly

---

app/models/benefit_group.rb
spec/models/benefit_group_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24328](https://devops.dchbx.org/redmine/issues/24328) |
| Ticket Author | Lindsay Obrien |

24328: "We're Sorry" message when click on Congressional ERs

---

app/views/insured/consumer_roles/docs_shared/_citizenship_number.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24467](https://devops.dchbx.org/redmine/issues/24467) |
| Ticket Author | Sarah Bagge |

24467: Immigration status doc field labels

---

app/notices/notice.rb
app/views/notices/ivl/enrollment_notice.html.erb
app/views/notices/shared/_address.html.erb
app/views/notices/shared/_date.html.erb
app/views/notices/shared/_paragraph_with_headers.html.erb
app/views/notices/shared/_unordered_list.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24504](https://devops.dchbx.org/redmine/issues/24504) |

24504: DC IVL_ENR has the MA Health Connector footer

---

app/data_migrations/change_renewing_plan_year_aasm_state.rb
lib/tasks/migrations/change_renewing_plan_year_aasm_state.rake
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24346](https://devops.dchbx.org/redmine/issues/24346) |
| Ticket Author | Julie Manuszak |

24346: Transition 6/1 plan year from renewing_published_pending to renewing_enrolling

---

lib/tasks/hbx_reports/employer_roster_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24188](https://devops.dchbx.org/redmine/issues/24188) |
| Ticket Author | @ap-dc |

24188: ER Roster Report broken due to DC/MA code merge

---

config/cucumber.yml
features/employers/add_plan_year_for_employer.feature

Disable add plan year cucumbers

---

app/assets/javascripts/employers_general_agency.js.erb
app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_employers.html.erb
components/sponsored_benefits/app/models/effective/datatables/broker_agency_employer_datatable.rb
components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb
spec/views/broker_agencies/profiles/_employers.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24049](https://devops.dchbx.org/redmine/issues/24049) |

24049: Get checkbox functionality on broker agency and employer data tables

---

config/settings.yml
features/employers/add_plan_year_for_employer.feature

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24523](https://devops.dchbx.org/redmine/issues/24523) |

24523: Shift ER Shopping Start_Date to 5/23

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24068](https://devops.dchbx.org/redmine/issues/24068) |
| Start Date | 04/24/2018 |
| Due Date | 05/01/2018  |
| Ticket Author | Rory Connell |

24068: 7/1/18 Monthly Conversion Data

---

app/data_migrations/cancel_plan_years_group.rb
lib/tasks/migrations/cancel_plan_years_group.rake
spec/data_migrations/cancel_plan_years_group_spec.rb
spec/test_data/cancel_plan_years/CancelPlanYears.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24025](https://devops.dchbx.org/redmine/issues/24025) |

24025: Transition Plan Year State to Cancel: Mid Plan Year Conversion Task

---

app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24664](https://devops.dchbx.org/redmine/issues/24664) |
| Ticket Author | @sarathpyerra |

24664: Admin Notice Tab Issue

---

config/cucumber.yml
config/settings.yml
features/employers/add_plan_year_for_employer.feature
features/employers/cobra.feature
features/employers/cobra_sole_source.feature
features/employers/employer_attestation.feature
features/employers/employer_attestation_sole_source.feature

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24083](https://devops.dchbx.org/redmine/issues/24083) |

24083: Revert ER Shopping date Change

---

spec/models/model_events/low_enrollment_notice_for_employer_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Low Enrollment notice spec

---

app/controllers/broker_agencies/inboxes_controller.rb
spec/controllers/broker_agencies/inboxes_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24235](https://devops.dchbx.org/redmine/issues/24235) |
| Ticket Author | @harshaellanki |

24235: Broker cannot open his agency mails

---

app/models/benefit_group.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24044](https://devops.dchbx.org/redmine/issues/24044) |
| Ticket Author | Chaitra Sanders |

24044: Employer Quoting Tool "Copy Quote" Not Working

---

app/views/notices/shared/_logo.html.erb
app/views/notices/shop_employee_notices/13_employee_open_enrollment_reminder.html.erb
components/notifier/app/views/notifier/notice_kinds/_logo.html.erb
components/sponsored_benefits/spec/dummy/config/settings.yml
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24431](https://devops.dchbx.org/redmine/issues/24431) |
| Ticket Author | Jason Sparks |

24431: MA Employee's Magic URL Routes to Non-Production Domain

---

components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24066](https://devops.dchbx.org/redmine/issues/24066) |

24066: BQT - Cannot Save Quote

---

app/controllers/employers/plan_years_controller.rb
app/views/employers/plan_years/calc_offered_plan_contributions.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24002](https://devops.dchbx.org/redmine/issues/24002) |
| Ticket Author | @harshared |

24002: Inconsistencies with multiple benefit groups in MA

---

app/helpers/application_helper.rb
app/views/employers/plan_years/calc_offered_plan_contributions.js.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Fix Spaghetti PY Javascript

---

app/models/effective/datatables/employee_datatable.rb
app/models/queries/employee_datatable_query.rb
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
features/employers/step_definitions/cobra_steps.rb
features/step_definitions/employers_steps.rb
project_gems/effective_datatables-2.6.14/app/models/effective/datatable.rb
spec/views/employers/employer_profiles/my_account/_census_employees.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24544](https://devops.dchbx.org/redmine/issues/24544) |
| Ticket Author | Lindsay Obrien |

24544: Search Bar Missing from Employer Roster

---

.rspec
.rspec_parallel
config/initializers/i18n_backend.rb

Re-enable translation caching unless specifically disabled.

Re-enable translation caching.

---

Gemfile
app/models/general_agency_profile.rb
app/models/notice_trigger.rb
components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/templates/templates/default.js
components/notifier/app/helpers/notifier/application_helper.rb
components/notifier/app/models/notifier/application_event_mapper.rb
components/notifier/app/models/notifier/builders/broker_profile.rb
components/notifier/app/models/notifier/builders/employee_profile.rb
components/notifier/app/models/notifier/builders/employer_profile.rb
components/notifier/app/models/notifier/builders/general_agency.rb
components/notifier/app/models/notifier/builders/plan_year.rb
components/notifier/app/models/notifier/merge_data_models/employee_profile.rb
components/notifier/app/models/notifier/merge_data_models/employer_profile.rb
components/notifier/app/models/notifier/merge_data_models/general_agency.rb
components/notifier/app/models/notifier/merge_data_models/plan_year.rb
components/notifier/app/models/notifier/notice_builder.rb
components/notifier/app/models/notifier/notice_kind.rb
components/notifier/app/views/notifier/notice_kinds/header_with_page_numbers.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20345](https://devops.dchbx.org/redmine/issues/20345) |
| Ticket Author | @harshared |

20345: MA Refactor ticket # - Implement Notice Engine in DC

---

app/data_migrations/remove_plan_offerings_for_er.rb
lib/tasks/migrations/remove_plan_offerings_for_er.rake
spec/data_migrations/remove_plan_offerings_for_er_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24103](https://devops.dchbx.org/redmine/issues/24103) |

24103: Remove Tufts from Plan Offerings - 	Mulligan Appliance Repair Service, Inc	

---

lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24771](https://devops.dchbx.org/redmine/issues/24771) |
| Ticket Author | @blackeaglejs |

24771: Add Open Enrollment Start/End and Carrier and Plan Selection to Outstanding Monthly Enrollment Reports

---

app/models/effective/datatables/family_data_table.rb
features/step_definitions/admin_pundit_authorization_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24359](https://devops.dchbx.org/redmine/issues/24359) |

24359: Turn On Manual Term/Cancel for Admin

---

components/notifier/app/models/notifier/notice_builder.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25482](https://devops.dchbx.org/redmine/issues/25482) |

25482: need to include  `include Notifier::ApplicationHelper` in notice_builder.rb

---

app/models/effective/datatables/family_data_table.rb
features/step_definitions/admin_pundit_authorization_steps.rb
features/step_definitions/integration_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25058](https://devops.dchbx.org/redmine/issues/25058) |

25058: Turn On SEP Dashboard

---

app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
features/employers/roster.feature
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25495](https://devops.dchbx.org/redmine/issues/25495) |

25495: Missing "Bulk Action" Button on the Roster

---

app/controllers/employers/employer_profiles_controller.rb
spec/controllers/employers/employer_profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25549](https://devops.dchbx.org/redmine/issues/25549) |

25549: Invoice Download Issue 

---

app/reports/hbx_reports/shop_enrollment_report.rb
lib/tasks/hbx_reports/shop_enrollment_report.rake
spec/reports/hbx_reports/shop_enrollment_report_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25370](https://devops.dchbx.org/redmine/issues/25370) |

25370: SHOP Enrollment Recon Report

---

app/helpers/config/site_helper.rb
app/views/insured/employee_roles/privacy.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25277](https://devops.dchbx.org/redmine/issues/25277) |

25277: Employee - Enrolling - View Privacy Act Statement link - Error 

---

features/brokers/create_broker_agency_profiles_individual_disabled.feature
features/step_definitions/brokers_steps.rb
features/step_definitions/integration_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21364](https://devops.dchbx.org/redmine/issues/21364) |
| Ticket Author | @Kevin-Wei |

21364: fix this cucumber from flickering 

---

components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/broker_agency_profile.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/commission_statement_service.rb
lib/tasks/nfp_broker_commissions.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26041](https://devops.dchbx.org/redmine/issues/26041) |

26041: Broker Commission statements not displaying in New Model

---

app/reports/hbx_reports/edi_enrollment_termination_report.rb

code refactor complete

---

app/models/hbx_enrollment_member.rb
app/views/events/hbx_enrollment/_policy.xml.haml
app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml
script/write_enrollment_files.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26274](https://devops.dchbx.org/redmine/issues/26274) |
| Ticket Author | Saadi Mirza |

26274: MPY Enrollments that failed to process

---

app/data_migrations/components/fix_employer_attestation.rb
lib/tasks/migrations/components/fix_employer_attestation.rake
spec/data_migrations/components/fix_employer_attestation_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26412](https://devops.dchbx.org/redmine/issues/26412) |

26412: ER Attestation - Migration State

---

script/cobra_enrollment_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26065](https://devops.dchbx.org/redmine/issues/26065) |

26065: Refactor Cobra Enrollment

---

lib/tasks/employers_failing_minimum_participation.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25983](https://devops.dchbx.org/redmine/issues/25983) |

25983: Refactor Minimum Participation Report

---

app/models/queries/policy_aggregation_pipeline.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26064](https://devops.dchbx.org/redmine/issues/26064) |

26064: Refactor - oustanding shop policies to pull

---

app/views/events/v2/employers/_benefit_group.xml.haml
lib/v2_group_xml_generator.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26709](https://devops.dchbx.org/redmine/issues/26709) |
| Ticket Author | Sai Sriramoju |

26709: Unable to generate V2 XML.

---

lib/tasks/hbx_reports/employer_poc_pending_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26507](https://devops.dchbx.org/redmine/issues/26507) |

26507: POC Report Research

---

app/helpers/application_helper.rb
app/views/ui-components/v1/cards/_metal_level_select.html.slim
components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/forms/benefit_application_form.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_service.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/submit_application.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
components/benefit_sponsors/spec/models/benefit_sponsors/forms/benefit_application_form_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26047](https://devops.dchbx.org/redmine/issues/26047) |
| Ticket Author | GoutamReddy Singireddy |

26047: Plan Year is not transferring  from Draft to Publish Pending

---

db/migrate/20180430172054_extract_county_zips_for_ma.rb
db/migrate/20180430181820_extract_rating_areas_for_ma.rb
db/migrate/20180503145357_cca_carrier_profiles_migration.rb
db/migrate/20180515171830_migrate_ma_service_areas.rb
db/migrate/20180515181450_generate_benefit_market_catalogs.rb
db/migrate/20180718162736_update_ma_list_bill_pricing_model.rb
db/seedfiles/cca/fixtures/pricing_model_5b044e499f880b5d6f36c788.yaml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26697](https://devops.dchbx.org/redmine/issues/26697) |

26697: EE Receives Error Message - HBX 108941

---

script/set_bs_employer_profile_id_on_staff_role.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26190](https://devops.dchbx.org/redmine/issues/26190) |

26190: MYC ER Account Creation Error

---

app/models/census_employee.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_benefit_applications_benefit_application.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_benefit_sponsorships_benefit_sponsorships.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_general_organizations.rb
script/disable_bga_for_imported_py_when_myc_exists.rb
script/fix_enrollment_benefit_packages.rb
script/set_predecessor_id_on_renewal_applications.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26807](https://devops.dchbx.org/redmine/issues/26807) |

26807: MPY SEPs purchased during renewal period for prior month get wrong benefit package

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/registrations/_sic_help.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25799](https://devops.dchbx.org/redmine/issues/25799) |

25799: SIC code selection issue

---

app/views/shared/engines/_broker_menu.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25924](https://devops.dchbx.org/redmine/issues/25924) |

25924: Families tab is not actionable - BQT

---

app/views/ui-components/v1/forms/broker_registration/_personal_information.html.slim
app/views/ui-components/v1/forms/employer_registration/_staff_role_information.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26019](https://devops.dchbx.org/redmine/issues/26019) |

26019: DOB Formatting issue with ER screener page

---

script/26760_migrate_brokers_to_new_model.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26760](https://devops.dchbx.org/redmine/issues/26760) |
| Ticket Author | Julie Harris |

26760: Broker Applied but Application Not Showing in EA

---

components/benefit_sponsors/app/models/benefit_sponsors/model_events/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/observers/benefit_application_observer.rb
components/notifier/app/models/notifier/builders/benefit_application.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27028](https://devops.dchbx.org/redmine/issues/27028) |

27028: Update MRG007 notice trigger to new model 

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26890](https://devops.dchbx.org/redmine/issues/26890) |

26890: Passive renewals should not be generated when ER no longer offering the renewal product.

---

components/benefit_sponsors/app/models/benefit_sponsors/model_events/hbx_enrollment.rb
components/benefit_sponsors/app/models/benefit_sponsors/observers/hbx_enrollment_observer.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27106](https://devops.dchbx.org/redmine/issues/27106) |

27106: Update MAE069 notice trigger to New Model

---

lib/tasks/recurring/employee_dependent_age_off_termination.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27156](https://devops.dchbx.org/redmine/issues/27156) |
| Ticket Author | @sarathpyerra |

27156: Refactor Ticket - MAE081 - Notify EE of DPT Termination due to age-off

---

components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/model_events/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/observers/benefit_application_observer.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/notice_service.rb
components/benefit_sponsors/lib/mongoid_migration_task.rb
components/benefit_sponsors/lib/tasks/modify_benefit_application.rake
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27107](https://devops.dchbx.org/redmine/issues/27107) |

27107: Refactor terminate_employer_account rake task

---

components/notifier/app/models/notifier/notice_builder.rb
components/notifier/app/views/layouts/notifier/pdf_layout.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25955](https://devops.dchbx.org/redmine/issues/25955) |

25955: MYC Notices - MPI Code on Cover Page is printing too high

---

app/data_migrations/create_renewal_plan_year_and_enrollment.rb
spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26758](https://devops.dchbx.org/redmine/issues/26758) |
| Ticket Author | SM Kelley |

26758: Datashredder--no renewal

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26022](https://devops.dchbx.org/redmine/issues/26022) |

26022: PY is Locked after looking at SBCs link from "View Summary"

---

script/fix_staff_role_reference_to_new_model_profile.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27448](https://devops.dchbx.org/redmine/issues/27448) |

27448: Repoint POC to New Model ER

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/_edit.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/edit.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25768](https://devops.dchbx.org/redmine/issues/25768) |
| Ticket Author | GoutamReddy Singireddy |

25768: when we edit draft plan year, it should be displayed as "Save Plan Year"

---

script/update_person_record_family.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26721](https://devops.dchbx.org/redmine/issues/26721) |

26721: Shop Enrollment Recon Report Update

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27563](https://devops.dchbx.org/redmine/issues/27563) |

27563: Investigate Initial Group Transmissions 

---

app/data_migrations/components/fix_organization.rb
lib/tasks/migrations/components/fix_organization.rake
spec/data_migrations/components/fix_organization_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26771](https://devops.dchbx.org/redmine/issues/26771) |

26771: Update the rake to modify on Organization instance 

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package_factory.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27532](https://devops.dchbx.org/redmine/issues/27532) |
| Ticket Author | @saimekala07  |

27532: Fix nil error when adding new benefit package.

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25286](https://devops.dchbx.org/redmine/issues/25286) |
| Ticket Author | GoutamReddy Singireddy |

25286: Error in ER Plan Year Tile

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_schedular.rb
components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27875](https://devops.dchbx.org/redmine/issues/27875) |

27875: OE Start Date Configuration Change

---

app/assets/stylesheets/ui-components/mahc-theme.scss

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25273](https://devops.dchbx.org/redmine/issues/25273) |

25273: Admin - Employer - Datable Issues

---

app/helpers/employers/employer_helper.rb
app/views/ui-components/v1/cards/_benefit_groups.html.slim
components/benefit_sponsors/spec/factories/benefit_sponsors_sponsored_benefits_sponsored_benefits.rb
spec/views/ui-components/v1/cards/_benefit_groups.html.slim_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25506](https://devops.dchbx.org/redmine/issues/25506) |

25506: Carrier text displaying wrong under PLANS BY for Benefit Package

---

app/helpers/config/site_helper.rb
components/benefit_sponsors/app/helpers/benefit_sponsors/application_helper.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25808](https://devops.dchbx.org/redmine/issues/25808) |

25808: Dates are not displaying on reload and question mark helper missing

---

app/assets/stylesheets/ui-components/cards.scss
app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/ui-components/v1/cards/_open_enrollment_ends.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/show.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25274](https://devops.dchbx.org/redmine/issues/25274) |

25274: Employer Page - UI styling Issues

---

app/views/ui-components/v1/forms/employer_registration/_employer_profile_form.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25420](https://devops.dchbx.org/redmine/issues/25420) |
| Ticket Author | Keeta Daves |

25420: Employer Account Creation Page Help Text

---

app/assets/stylesheets/ui-components/mahc-theme.scss

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25186](https://devops.dchbx.org/redmine/issues/25186) |

25186: Benefit Package - Select Your Plan Offering -  Select Your Reference Plan - UI defects

---

app/models/benefit_group_assignment.rb
app/models/eligibility/employee_benefit_packages.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/spec/dummy/app/models/benefit_group_assignment.rb
components/benefit_sponsors/spec/dummy/app/models/caches/request_scoped_cache.rb
components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
components/benefit_sponsors/spec/dummy/app/models/family.rb
components/benefit_sponsors/spec/dummy/app/models/hbx_enrollment.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
script/fix_benefit_application_for_mpy.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27044](https://devops.dchbx.org/redmine/issues/27044) |

27044: Disable the code that marks renew benefit group assignments as active

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25366](https://devops.dchbx.org/redmine/issues/25366) |

25366: Revert Plan Year Button is not Aligned

---

app/views/devise/passwords/create.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18741](https://devops.dchbx.org/redmine/issues/18741) |
| Ticket Author | @venkat31 |

18741: Repeated flash messages

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25810](https://devops.dchbx.org/redmine/issues/25810) |

25810: Publish Plan Year button should be enabled for MPYC Employer After Reverting plan year

---

Gemfile.lock
app/views/exchanges/hbx_profiles/_family_index_datatable.html.slim
project_gems/effective_datatables-2.6.14/app/assets/stylesheets/dataTables/dataTables.bootstrap.css

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25305](https://devops.dchbx.org/redmine/issues/25305) |

25305: Admin - Families - Text Alignment Issue

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25935](https://devops.dchbx.org/redmine/issues/25935) |
| Ticket Author | GoutamReddy Singireddy |

25935: Error message is different when "Plan Year failed to publish.

---

app/assets/stylesheets/insured.scss.erb
app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/layouts/application.html.erb
app/views/ui-components/v1/layouts/_footer.html.slim
spec/views/ui-components/v1/layouts/_footer.html.slim_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25457](https://devops.dchbx.org/redmine/issues/25457) |

25457: Footer Issue - Missing Email Address & FAQ link

---

app/views/shared/brokers/_applicant.html.erb
app/views/shared/brokers/_broker_fields.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25621](https://devops.dchbx.org/redmine/issues/25621) |

25621: Broker UI Issues

---

script/policies_for_simulated_renewals.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Skip employers that dont have an appropriate benefit application

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_commission_statements.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28071](https://devops.dchbx.org/redmine/issues/28071) |
| Ticket Author | Brian Schwartz |

28071: Broker Commissions Statements - No Clickable Links to Open/View/Download the Statements in MA Prod

---

app/assets/stylesheets/custom.scss.erb
app/assets/stylesheets/new.scss.erb
app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/employers/census_employees/_cobra_fields.html.erb
app/views/employers/census_employees/_form.html.erb
app/views/employers/census_employees/_member_fields.html.erb
app/views/layouts/application.html.erb
app/views/shared/_census_employee_fields.html.erb
app/views/ui-components/v1/cards/_metal_level_select.html.slim
app/views/ui-components/v1/forms/office_locations/_old_style_address.html.erb
app/views/ui-components/v1/navs/_header.html.slim
components/benefit_markets/app/views/layouts/benefit_markets/application.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_employer_broker_widget.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_employer_form.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_billing.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_employer_welcome.html.erb
components/benefit_sponsors/app/views/layouts/benefit_sponsors/application.html.slim
components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
components/sponsored_benefits/app/assets/stylesheets/sponsored_benefits/plan_design_proposal.scss
components/sponsored_benefits/app/views/layouts/sponsored_benefits/application.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27776](https://devops.dchbx.org/redmine/issues/27776) |
| Ticket Author | Heather Cloran |

27776: BQT Error - Plans Showing Horiztonal Bar Only

---

app/views/ui-components/v1/cards/_sponsor_contributions.html.slim
app/views/ui-components/v1/cards/_sponsor_contributions_shell.html.slim
components/benefit_sponsors/app/helpers/benefit_sponsors/application_helper.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25462](https://devops.dchbx.org/redmine/issues/25462) |

25462: ER Add/Edit Plan Year & Document Upload - Missing Question mark and hover-over help text

---

app/assets/stylesheets/custom.scss.erb
app/assets/stylesheets/new.scss.erb
app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/devise/passwords/create.js.erb
app/views/employers/census_employees/_cobra_fields.html.erb
app/views/employers/census_employees/_form.html.erb
app/views/employers/census_employees/_member_fields.html.erb
app/views/exchanges/hbx_profiles/_family_index_datatable.html.slim
app/views/layouts/application.html.erb
app/views/shared/_census_employee_fields.html.erb
app/views/ui-components/v1/cards/_metal_level_select.html.slim
app/views/ui-components/v1/forms/office_locations/_old_style_address.html.erb
app/views/ui-components/v1/navs/_header.html.slim
components/benefit_markets/app/views/layouts/benefit_markets/application.html.slim
components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_employer_broker_widget.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_employer_form.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_billing.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_employer_welcome.html.erb
components/benefit_sponsors/app/views/layouts/benefit_sponsors/application.html.slim
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
components/sponsored_benefits/app/views/layouts/sponsored_benefits/application.html.erb
project_gems/effective_datatables-2.6.14/app/assets/stylesheets/dataTables/dataTables.bootstrap.css
spec/views/events/v2/employers/updated.xml.haml_spec.rb

This reverts commit 4ccd9b44d0c5174b0029415fbb4826e99bc94987, reversing
changes made to b387e557d1f5d6f7f3847b847719ffc6c25f25b8.
* (Required!)
* ()
* ()
```
```
*
---
---

Revert "Merge branch 'bug-25682' into ma_preprod"

---

app/views/employers/census_employees/_enrollment_details.html.erb
app/views/insured/plan_shoppings/_coverage_information.html.slim
spec/views/employers/census_employees/enrollment_details.html.erb_spec.rb
spec/views/insured/plan_shoppings/coverage_information.html.slim_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25380](https://devops.dchbx.org/redmine/issues/25380) |

25380: Per member premium display

---

components/notifier/app/models/notifier/notice_builder.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25929](https://devops.dchbx.org/redmine/issues/25929) |

25929: Duplicate Invoice Availability Message in ER Account after Invoice Generation in PVT 2

---

Gemfile.lock

* (Required!)
* ()
* ()
```
```
*
---
---

commit gemfile.lock

---

app/helpers/employers/premium_statement_helper.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_coverage_reports.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/coverage_reports.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/coverage_reports.js.erb
components/benefit_sponsors/spec/models/benefit_sponsors/concerns/employer_profile_concern_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25832](https://devops.dchbx.org/redmine/issues/25832) |

25832: Enrollment Report Does Not Show Renewal Enrollment at Effective Date

---

app/controllers/employers/plan_years_controller.rb
app/helpers/application_helper.rb
app/helpers/insured/group_selection_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
app/views/employers/plan_years/_form.html.erb
app/views/insured/group_selection/new.html.erb
app/views/shared/_signup_progress.html.haml
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_employees.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_form.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_proposal_info.html.erb
config/routes.rb
config/settings.yml
features/step_definitions/employers_steps.rb
spec/controllers/employers/plan_years_controller_spec.rb
spec/factories/plans.rb
spec/helpers/application_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24228](https://devops.dchbx.org/redmine/issues/24228) |

24228: July Q3 Carriers being pulled in

---

components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
components/sponsored_benefits/app/assets/stylesheets/sponsored_benefits/plan_design_proposal.scss
components/sponsored_benefits/app/views/layouts/sponsored_benefits/application.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/office_locations/_office_location_fields.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_organizations/_entity_name_and_type_fields_autofill.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_organizations/_form.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_carrier_options.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/carriers/_carriers_list.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_selections/_carrier_options.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plans/_plans.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28120](https://devops.dchbx.org/redmine/issues/28120) |

28120: BQT Plan Selection Radio Buttons Missing

---

app/controllers/employers/plan_years_controller.rb
app/helpers/application_helper.rb
app/helpers/insured/group_selection_helper.rb
app/models/employer_profile.rb
app/models/plan.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
app/views/employers/plan_years/_form.html.erb
app/views/insured/group_selection/new.html.erb
app/views/shared/_signup_progress.html.haml
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_employees.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_form.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_proposal_info.html.erb
config/routes.rb
config/settings.yml
features/step_definitions/employers_steps.rb
spec/controllers/employers/plan_years_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24456](https://devops.dchbx.org/redmine/issues/24456) |

24456: BQT-Late Rates Issue

---

app/views/insured/plan_shoppings/show.html.slim
app/views/ui-components/v1/filters/_plan_filters.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25773](https://devops.dchbx.org/redmine/issues/25773) |
| Ticket Author | Lindsay Obrien |

25773: Filter Reset Doesn't Work in EE Plan Shopping

---

app/views/employers/employer_attestations/_edit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25527](https://devops.dchbx.org/redmine/issues/25527) |

25527: Admin Employer List Page - Employer filters and Attesation document alignment 

---

app/assets/javascripts/ui-components/forms.js.erb
app/views/ui-components/v1/forms/office_locations/_address.html.slim
app/views/ui-components/v1/forms/office_locations/_office_location_fields.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25806](https://devops.dchbx.org/redmine/issues/25806) |

25806: Address issue on Employer registering submission page

---

app/assets/stylesheets/ui-components/mahc-theme.scss
app/controllers/products/qhp_controller.rb
app/views/insured/plan_shoppings/show.html.slim
app/views/shared/_comparison.html.erb
app/views/shared/plan_shoppings/_sbc_link.html.erb
app/views/ui-components/v1/cards/_plan_details.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25774](https://devops.dchbx.org/redmine/issues/25774) |
| Ticket Author | Lindsay Obrien |

25774: "Compare" Functionality EE Plan Shopping Page Doesn't Work

---

app/assets/stylesheets/ui-components/mahc-theme.scss
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25588](https://devops.dchbx.org/redmine/issues/25588) |

25588: ER Benefits UI Issues

---

app/data_migrations/update_initial_invoice_title.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/documents/document.rb
components/benefit_sponsors/app/models/benefit_sponsors/model_events/document.rb
components/notifier/app/models/notifier/notice_builder.rb
lib/tasks/migrations/update_initial_invoice_title.rake
spec/data_migrations/update_initial_invoice_title_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25944](https://devops.dchbx.org/redmine/issues/25944) |

25944: New Sale/Initial Employer - First Invoice Missing .pdf extension

---

app/controllers/insured/plan_shoppings_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25989](https://devops.dchbx.org/redmine/issues/25989) |

25989: EE Plan Shopping - Plan List - Wrong Default Sort Order (Should be Premium Lowest to Highest)

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb

This reverts commit 4e1c240625373d8fe1aec7f76a841f7abc3097df, reversing
changes made to 03fe46e2a9b2f766013d680353afc24314d34f3a.

Revert "Merge branch 'bug-26154' into ma_preprod"

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25809](https://devops.dchbx.org/redmine/issues/25809) |

25809: Contributions Dont Store When Changing Plan Type 

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25976](https://devops.dchbx.org/redmine/issues/25976) |

25976:  Network Notes - Help Icon text Issue

---

components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25927](https://devops.dchbx.org/redmine/issues/25927) |

25927: Issues with Employers Roster Filters

---

components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25946](https://devops.dchbx.org/redmine/issues/25946) |

25946: Binder Paid Filter is not working

---

app/models/plan_year.rb
spec/helpers/events_helper_spec.rb
spec/models/plan_year_publishing_spec.rb

This reverts commit 69f134299ca917209270448f799160c294b6fc5e, reversing
changes made to a985794d3974d834c3406e49a277d931baae39c8.
* (Required!)
* ()
* ()
```
```
*
---
---

Revert "Merge branch 'bug-22519' into ma_preprod"

---

app/data_migrations/update_employee_role_id.rb
lib/tasks/migrations/update_employee_role_id.rake
spec/data_migrations/update_employee_role_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28172](https://devops.dchbx.org/redmine/issues/28172) |
| Ticket Author | Karmala Thomas |

28172: Error message received when selecting user account-Benjamin Day(129021)

---

app/data_migrations/components/fix_office_location_address_kind.rb
lib/tasks/migrations/components/fix_office_location_address_kind.rake
script/fix_office_location_address_kind.rb
spec/data_migrations/components/fix_office_location_address_kind_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25819](https://devops.dchbx.org/redmine/issues/25819) |

25819: Group DBA Name changes are triggering the wrong event

---

app/data_migrations/update_subject_for_messages.rb
lib/tasks/update_subject_for_messages.rake
spec/data_migrations/update_subject_for_messages_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26677](https://devops.dchbx.org/redmine/issues/26677) |
| Ticket Author | SM Kelley |

26677: TerminationOfMaHealthLinkParticipation 

---

app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/exchanges/hbx_profiles/_invoice.html.slim

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25592](https://devops.dchbx.org/redmine/issues/25592) |

25592: Employers-Source Kind box is too large 

---

app/data_migrations/components/fix_organization.rb
lib/tasks/migrations/components/fix_organization.rake
spec/data_migrations/components/fix_organization_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27300](https://devops.dchbx.org/redmine/issues/27300) |

27300: FEIN Correction: Rigali Roofing

---

components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26772](https://devops.dchbx.org/redmine/issues/26772) |

26772: update the rake to modify on benefit application instance

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27537](https://devops.dchbx.org/redmine/issues/27537) |
| Ticket Author | Chad Morton |

27537: MASSACHUSETTS July 2018 Termination / Cancellation for non-payment

---

components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/cca_composite_tier_precalculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/cca_shop_list_bill_pricing_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/shop_simple_list_bill_pricing_calculator.rb
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/pricing_calculators/cca_composite_tier_precalculator_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/pricing_calculators/cca_shop_list_bill_pricing_calculator_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/pricing_calculators/shop_simple_list_bill_pricing_calculator_spec.rb
db/seedfiles/cca/fixtures/benefit_market_catalog_5b3e401a9f880b598f04ffd5.yaml
db/seedfiles/cca/fixtures/benefit_market_catalog_5b3e401d9f880b598f050320.yaml
db/seedfiles/cca/fixtures/pricing_model_5b044e499f880b5d6f36c788.yaml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29403](https://devops.dchbx.org/redmine/issues/29403) |
| Ticket Author | @Ckellem |

29403: CPR-Rating all children under 21 when only the three oldest should be rated.

---

app/data_migrations/update_broker_agency_details.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/broker_management_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/invitation_email_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/invitation_emails_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/update_broker_agency_service.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/update_broker_agency_service_spec.rb
lib/tasks/migrations/broker_agency/update_broker_agency_profile.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26782](https://devops.dchbx.org/redmine/issues/26782) |

26782: Update the Rake to add/remove/update broker agency  instance

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29186](https://devops.dchbx.org/redmine/issues/29186) |
| Ticket Author | @Ckellem |

29186: 10/1 ER Configuration Update

---

lib/object_builders/qhp_rate_builder.rb
spec/lib/object_builders/qhp_rate_builder_spec.rb
spec/test_data/plan_data/rates/SHOP_RATES_BCBS_TEST.xml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27672](https://devops.dchbx.org/redmine/issues/27672) |
| Ticket Author | @vineelsonnathi |

27672: Refactor - QHP Rate Builder

---

app/assets/stylesheets/employer.scss.erb
app/assets/stylesheets/new.scss.erb
components/sponsored_benefits/app/assets/stylesheets/new.scss

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28504](https://devops.dchbx.org/redmine/issues/28504) |

28504: Benefits Package Missing 4th Rating Tier on Benefits tab

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29792](https://devops.dchbx.org/redmine/issues/29792) |

29792: Revert OE Start_on Configuration Change

---

app/data_migrations/update_predecessor_id_on_bp.rb
lib/tasks/migrations/update_predecessor_id_on_bp.rake
spec/data_migrations/update_predecessor_id_on_bp_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29691](https://devops.dchbx.org/redmine/issues/29691) |
| Start Date | 08/31/2018 |
| Due Date | 08/31/2018  |

29691: Unable to Shop For Renewal Coverage - undefined method `sponsored_benefit_for' for nil:NilClass

---

components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/lib/tasks/modify_benefit_application.rake
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29782](https://devops.dchbx.org/redmine/issues/29782) |
| Start Date | 08/31/2018 |
| Due Date | 08/31/2018  |
| Ticket Author | Julie Manuszak |

29782: Transition 9/1 initial group 

---

app/controllers/insured/employee_roles_controller.rb
spec/controllers/insured/employee_roles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29702](https://devops.dchbx.org/redmine/issues/29702) |
| Ticket Author | Mary Jenkins |

29702: Rehired EE Unable to Link to ER

---

app/models/benefit_group_assignment.rb
app/models/family.rb
app/models/hbx_enrollment.rb
components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30098](https://devops.dchbx.org/redmine/issues/30098) |

30098: Provide ability to extend open enrollment for both initial and renewal employers

---

app/controllers/insured/employee_roles_controller.rb
app/data_migrations/products/mapping_to_correct_hios_id.rb
app/models/benefit_group_assignment.rb
app/models/census_employee.rb
app/models/eligibility/employee_benefit_packages.rb
app/models/factories/enrollment_factory.rb
app/models/family.rb
app/models/hbx_enrollment.rb
components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_policy_action.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
lib/tasks/products/mapping_to_correct_hios_id.rake
spec/data_migrations/products/mapping_to_correct_hios_id_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Latest master

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb
components/benefit_sponsors/spec/dummy/app/models/family.rb
components/benefit_sponsors/spec/dummy/config/settings.yml
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/aca_shop_benefit_sponsorship_service_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30521](https://devops.dchbx.org/redmine/issues/30521) |

30521: Close open enrollment for enrollment extended applications

---

components/notifier/app/models/notifier/builders/offered_product.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29450](https://devops.dchbx.org/redmine/issues/29450) |
| Due Date | 09/20/2018  |

29450: 9/1 New sale invoices switched ER and EE contributions

---

components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30818](https://devops.dchbx.org/redmine/issues/30818) |
| Ticket Author | Karmala Thomas |

30818: Transition MA 9/1/2018 group to "Renewing_enrolling"- CUSTOMWORKS CONTRACTING LLC.

---

app/data_migrations/update_product_package_rates.rb
lib/tasks/migrations/update_product_package_rates.rake
spec/data_migrations/update_product_package_rates_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29936](https://devops.dchbx.org/redmine/issues/29936) |
| Ticket Author | Julie Harris |

29936: MA Plans Not Loading for New Employee. 

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30078](https://devops.dchbx.org/redmine/issues/30078) |
| Ticket Author | Sai Sriramoju |

30078: Wrong ER landing page for Conversion ER's

---

app/controllers/insured/plan_shoppings_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [31266](https://devops.dchbx.org/redmine/issues/31266) |
| Ticket Author | Bobby Jones |

31266: Master Ticket: MA Plans Not Loading for New Employee

---

app/data_migrations/update_super_group.rb
lib/tasks/update_super_group.rake
spec/lib/tasks/update_super_group_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28106](https://devops.dchbx.org/redmine/issues/28106) |

28106: Please load 2017 Supergroup ID for HIOS ID: 41304MA0041055-01

---

components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [31109](https://devops.dchbx.org/redmine/issues/31109) |

31109: Select Brokers unable to view commission statements

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36974](https://devops.dchbx.org/redmine/issues/36974) |
| Ticket Author | Bobby Jones |

36974: GLOBAL FIX: Rehired EE Unable to Link to ER

---

app/data_migrations/update_employee_role_id.rb
lib/tasks/migrations/update_employee_role_id.rake
spec/data_migrations/update_employee_role_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37321](https://devops.dchbx.org/redmine/issues/37321) |
| Ticket Author | Sai Sriramoju |

37321: Error with respect to the EE : 102561

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37863](https://devops.dchbx.org/redmine/issues/37863) |

37863: EDI Automation date deadline changes due to holiday schedule

---

app/helpers/config/site_helper.rb
app/mailers/user_mailer.rb
app/views/user_mailer/broker_application_confirmation.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37062](https://devops.dchbx.org/redmine/issues/37062) |

37062: Broker Email Change #1

---

app/helpers/config/site_helper.rb
app/mailers/user_mailer.rb
app/views/user_mailer/broker_invitation_email.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37063](https://devops.dchbx.org/redmine/issues/37063) |

37063: Broker Email Change #2

---

components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_policy_action.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37558](https://devops.dchbx.org/redmine/issues/37558) |
| Due Date | 11/15/2018  |
| Ticket Author | Marcus Tinnin |

37558: Dental - 2/1 Conversion Data

---

app/helpers/config/aca_helper.rb
app/views/ui-components/v1/cards/_metal_level_select.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/_sponsored_benefit.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/new.html.slim
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_selections/_carrier_options.html.erb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37766](https://devops.dchbx.org/redmine/issues/37766) |

37766: ER Portal Plan Model Selection - Change Help Text

---

components/benefit_markets/spec/factories/benefit_markets_products_product_packages.rb
features/admin/open_enrollment_button.feature
features/employers/benefit_applications/active/admin_active_enrollment_extension.feature
features/employers/benefit_applications/draft/admin_draft_enrollment_extension.feature
features/employers/benefit_applications/enrolling/admin_enrolling_enrollment_extension.feature
features/employers/benefit_applications/enrollment_closed/admin_enrollment_closed_enrollment_extension.feature
features/employers/benefit_applications/enrollment_eligible/admin_enrollment_eligible_extension.feature
features/employers/benefit_applications/enrollment_extended/admin_enrollment_extended_extension.feature
features/employers/benefit_applications/expired/admin_expired_enrollment_extension.feature
features/employers/benefit_applications/extend_open_enrollment_steps.rb
features/employers/benefit_applications/imported/admin_imported_enrollment_extension.feature
features/employers/benefit_applications/terminated/admin_terminated_enrollment_extension.feature
features/employers/benefit_applications/termination_pending/admin_termination_pending_enrollment_extension.feature
features/hbx_admin/step_definitions/binder_transition_steps.rb
features/permissions/extend_open_enrollment.feature
features/step_definitions/employers_steps.rb
features/support/user_cleanup.rb
features/support/worlds/benefit_application_world.rb
features/support/worlds/benefit_market_world.rb
features/support/worlds/benefit_sponsor_world.rb
features/support/worlds/broker_agency_world.rb
features/support/worlds/employer_world.rb
features/support/worlds/permissions_world.rb
features/support/worlds/site_world.rb
features/support/worlds/user_world.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38236](https://devops.dchbx.org/redmine/issues/38236) |

38236: Extension of OE - Cucumber

---

app/models/publishers/legacy/outstanding_monthly_enrollments_report_publisher.rb
app/reports/hbx_reports/outstanding_monthly_enrollments.rb
components/transport_profiles/app/models/transport_profiles/processes/legacy/push_monthly_outstanding_enrollments_report.rb
lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake
spec/lib/tasks/hbx_reports/outstanding_monthly_enrollments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38660](https://devops.dchbx.org/redmine/issues/38660) |
| Ticket Author | Sheheryar Tariq |

38660: Enroll Outstanding Report 

---

app/helpers/config/site_helper.rb
app/views/exchanges/hbx_profiles/_force_publish.html.erb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
features/employers/benefit_applications/admin_force_publish_steps.rb
features/employers/benefit_applications/force_publish/admin_force_publish.feature

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38289](https://devops.dchbx.org/redmine/issues/38289) |

38289: MA - Publish Application After Application Submission Deadline

---

app/models/benefit_group_assignment.rb
app/models/census_employee.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
spec/models/census_employee_spec.rb
spec/models/employee_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38756](https://devops.dchbx.org/redmine/issues/38756) |

38756: 1/1 renewal plan shopping recon - undefined method `sponsored_benefit_for' for nil:NilClass

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38837](https://devops.dchbx.org/redmine/issues/38837) |

38837: Dental Enrollments Not Showing on New Sale Invoices

---

app/data_migrations/delete_single_invoice_with_fein.rb
spec/data_migrations/delete_single_invoice_with_fein_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38842](https://devops.dchbx.org/redmine/issues/38842) |

38842: Removal of Invoices

---

app/helpers/config/site_helper.rb
app/views/datatables/shared/_dropdown.html.erb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb
features/employers/benefit_applications/admin_force_publish_steps.rb
features/employers/benefit_applications/force_publish/admin_force_publish.feature

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38534](https://devops.dchbx.org/redmine/issues/38534) |

38534: MA - Force Publish Eligibility Determination

---

app/data_migrations/define_permissions.rb
features/permissions/extend_open_enrollment.feature
features/support/worlds/permissions_world.rb
lib/tasks/define_permissions.rake
spec/data_migrations/permissions_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38877](https://devops.dchbx.org/redmine/issues/38877) |

38877: Tier 3 Ability to Extend OE

---

lib/tasks/export_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38658](https://devops.dchbx.org/redmine/issues/38658) |
| Ticket Author | Heather Cloran |

38658: Employer Data Extract

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/notifier/app/models/notifier/builders/employer_profile.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38838](https://devops.dchbx.org/redmine/issues/38838) |
| Ticket Author | Candice Holloway |

38838: Invoice Pulls Total Premiums for Employees with Future Start Date: MA-Little Hands Children Center

---

app/data_migrations/update_fields_of_employee_role.rb
lib/tasks/update_fields_of_employee_role.rake
spec/data_migrations/update_fields_of_employee_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38613](https://devops.dchbx.org/redmine/issues/38613) |
| Ticket Author | Keeta Daves |

38613: Error message received when logging into user account - 108315

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38906](https://devops.dchbx.org/redmine/issues/38906) |
| Ticket Author | Keeta Daves |

38906: 1/1 renewal 13 RIVER STREET LLC

---

features/employers/benefit_applications/force_publish/admin_force_publish.feature

* (Required!)
* ()
* ()
```
```
*
---
---

update cucumber feature

---

app/data_migrations/define_permissions.rb
app/models/permission.rb
app/policies/hbx_profile_policy.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb
features/permissions/change_fein.feature
features/support/worlds/permissions_world.rb
features/support/worlds/user_world.rb
lib/tasks/define_permissions.rake
spec/data_migrations/permissions_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38323](https://devops.dchbx.org/redmine/issues/38323) |

38323: MA - Change FEIN UI + Permissions + Cucumbers

---

app/javascript/benefit_sponsors/office_locations.js
app/javascript/packs/benefit_sponsors.js
app/views/ui-components/v1/forms/office_locations/_address.html.slim
app/views/welcome/index.html.slim
features/group_selection/ee_plan_shopping.feature
features/step_definitions/employee_steps.rb
features/step_definitions/employers_steps.rb
features/step_definitions/group_selection_steps.rb
features/step_definitions/integration_steps.rb
features/step_definitions/new_hire_steps.rb
features/step_definitions/renewal_steps.rb
features/support/worlds/benefit_application_world.rb
features/support/worlds/benefit_sponsor_world.rb
features/support/worlds/employer_world.rb
features/support/worlds/form_world.rb
features/support/worlds/site_world.rb

Small update to some js, and merge of several specs.

Incremental cucumber merge 2

---

components/benefit_sponsors/spec/models/benefit_sponsors/model_events/application_coverage_selected_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Troubleshoot application coverage selected spec

---

app/assets/javascripts/glossary.js
components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/glossary.js

* (Required!)
* ()
* ()
```
```
*
---
---

Updated tooltip text for deductible definition

---

app/views/shared/_comparison.html.erb
app/views/shared/plan_shoppings/_annual_deductibles.html.erb
features/employee/employee_annual_deductible_display.feature
features/step_definitions/new_hire_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Employee plan comparison

---

app/assets/javascripts/glossary.js
app/assets/stylesheets/ui-components/mahc-theme.scss
app/views/insured/families/_enrollment.html.erb
app/views/insured/plan_shoppings/show.html.slim
app/views/ui-components/v1/cards/_plan_details.html.slim
components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/glossary.js
features/step_definitions/new_hire_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #add-dd Glossary updates for EE flow

---

app/models/group_selection_eligibility_checker.rb

* https://www.pivotaltracker.com/n/projects/2481179/stories/178300863

REFS maintenanve - Fixes group selection eligibility checker.

---

app/assets/javascripts/ajax_token_redirect.js
app/controllers/application_controller.rb
components/benefit_markets/app/controllers/benefit_markets/application_controller.rb
components/benefit_sponsors/app/controllers/benefit_sponsors/application_controller.rb
components/notifier/app/controllers/notifier/application_controller.rb
components/sponsored_benefits/app/controllers/sponsored_benefits/application_controller.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Unknown format exception

---

Gemfile.lock

* https://www.pivotaltracker.com/story/show/178266773

REFS maintenance - fixes revision of acapi gem.

---

components/benefit_sponsors/app/policies/benefit_sponsors/organizations/organization_forms/registration_form_policy.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - add safe operator to avoid calling method on nil

---

app/views/employers/employer_profiles/_file_not_attached_error.html.erb
components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - adding a try/catch to check for file in params

---

app/views/insured/plan_shoppings/show.html.slim

- https://www.pivotaltracker.com/n/projects/2481179/stories/178657299

REFS Maintenance - Fixes plan shoppings show.

---

app/models/special_enrollment_period.rb
spec/models/special_enrollment_period_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Fixes broken exception in sep model.

---

spec/controllers/products/qhp_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Fixes qhp_controller_spec

---

Gemfile
Gemfile.lock
components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/registrations_controller.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/registrations_controller_spec.rb

* https://www.pivotaltracker.com/n/projects/2481179/stories/178844741
* ()
* ()
```
```
*
---
---

New Relic MA 7/12

---

Gemfile
Gemfile.lock
app/views/insured/families/_inbox.html.erb
db/seedfiles/translations/en/cca/insured.rb

* (Required!)
* ()
* ()
```
```
*
---
---

change date to date_label

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim
components/benefit_sponsors/app/models/benefit_sponsors/forms/benefit_package_form.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/sponsored_benefit_cost_estimation_service.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/forms/benefit_package_form_spec.rb

* https://www.pivotaltracker.com/n/projects/2481179/stories/178724810

Benefit cost calculation stuff

---

app/models/census_employee.rb
app/models/person.rb
spec/controllers/employers/census_employees_controller_spec.rb

* https://www.pivotaltracker.com/n/projects/2481179/stories/178897546

add spec and fix employer validation

---

app/models/carrier_service_area.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - pass empty string instead of running regexp on null

---

app/controllers/insured/family_members_controller.rb
spec/controllers/insured/family_members_controller_spec.rb

- https://www.pivotaltracker.com/n/projects/2481179/stories/178571122

Family members fix

---

components/benefit_sponsors/app/controllers/benefit_sponsors/application_controller.rb

* https://www.pivotaltracker.com/n/projects/2481179/stories/179060839
* ()
* ()
```
```
*
---
---

Fix undefined method: root_url - 8/2/21

---

components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/sponsored_benefits/app/models/sponsored_benefits/forms/plan_design_proposal.rb
config/settings.yml
features/step_definitions/broker_employee_quote_steps.rb
lib/tasks/export_employers.rake
spec/notices/shop_employer_notices/employer_broker_fired_notice_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Rc release 5.7.22

---

app/models/listeners/mail_delivery/soa_mailer.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS maintenance - fixes soa mailer issue.

---

app/models/listeners/mail_delivery/soa_mailer.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Fix mailer

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Refs 96072 : Revert to 1st

---

components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

spec fixes

---

lib/tasks/recurring/employee_dependent_age_off_termination.rake

* (Required!)
* ()
* ()
```
```
*
---
---

refactors age off notice

---

components/benefit_markets/spec/domain/benefit_markets/operations/benefit_markets/create_benefit_sponsor_catalog_spec.rb
components/benefit_markets/spec/domain/benefit_markets/operations/products/find_spec.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/forms/benefit_package_form_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/plans_controller_spec.rb
features/hbx_admin/step_definitions/create_plan_year.rb
features/step_definitions/conversion_employee_steps.rb
features/support/worlds/benefit_application_world.rb
features/support/worlds/benefit_market_world.rb
spec/models/employee_role_integration_spec.rb
spec/models/forms/bulk_actions_for_admin_spec.rb
spec/models/sponsored_benefits/plan_design_proposals_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix date-based rspec and cucumber failures

---

system/config/templates/features/enroll_app/enroll_app.yml

* (Required!)
* ()
* ()
```
```
*
---
---

updates correct business resource link

---

features/step_definitions/conversion_employee_steps.rb
features/support/worlds/benefit_market_world.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fixes date change cuke failures

---

.github/workflows/ruby.yml
components/notifier/app/models/notifier/builders/employee_profile.rb

* (Required!)
* ()
* ()
```
```
*
---
---

adds term date in age off notice

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Change renewal date to 1st of the month

---

components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
spec/models/importers/transcripts/enrollment_transcript_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fixes spec failures

---

app/views/insured/members_selection/_coverage_household.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Add default radio check to Enroll

---

app/views/insured/members_selection/_coverage_household.html.erb
app/views/insured/members_selection/new.html.erb
features/group_selection/ee_plan_shopping.feature
features/step_definitions/integration_steps.rb

[181595757](https://www.pivotaltracker.com/n/projects/2481184/stories/181595757)

add error messages for ineligible members

---

app/views/insured/members_selection/_coverage_household.html.erb
features/support/object_model_pages/admin/admin_homepage.rb
features/support/object_model_pages/admin/families_page.rb
features/support/object_model_pages/home_page.rb
features/support/object_model_pages/shop/employee/ee_choose_coverage.rb
features/support/object_model_pages/shop/employee/ee_confirm_your_plan_selection.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb
features/support/object_model_pages/shop/employee/ee_enrollment_submitted.rb
features/support/object_model_pages/shop/employee/ee_family_members.rb
features/support/object_model_pages/shop/employee/homepage/ee_homepage.rb
spec/controllers/insured/members_selection_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

181281065 continuous shopping pom implementation

---

features/integration/employee_sign_up.feature
features/step_definitions/integration_steps.rb

[ME-181595763](https://www.pivotaltracker.com/story/show/181595763)

POM Implementation on group selection page

---

spec/models/importers/transcripts/enrollment_transcript_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

dry up date

---

app/views/insured/product_shoppings/_plan_filters.html.slim
app/views/insured/product_shoppings/show.html.slim
features/group_selection/ee_plan_shopping.feature
features/step_definitions/continuous_plan_shopping/product_filters_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb

[181727853](https://www.pivotaltracker.com/n/projects/2481184/stories/181727853)

enable plan filters in continuos shopping flow

---

features/employee/employee_plan_shopping_make_changes_button_display.feature
features/step_definitions/integration_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Cucumbers to verify shop for new plan

---

app/views/insured/product_shoppings/eligible_continuous_coverage.html.erb

[ME-181821850](https://www.pivotaltracker.com/story/show/181821850)

UI bug related to ID

---

app/views/insured/product_shoppings/eligible_continuous_coverage.html.erb
app/views/insured/product_shoppings/receipt.html.erb
db/seedfiles/translations/en/cca/insured.rb
db/seedfiles/translations/en/dc/insured.rb
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb

[ME-181281199](https://www.pivotaltracker.com/story/show/181281199)
[ME-181821850](https://www.pivotaltracker.com/n/projects/2481184/stories/181821850#)

cucumbers dental confirmation page

---

app/views/insured/product_shoppings/show.html.slim
features/step_definitions/continuous_plan_shopping/product_filters_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb

[MA-181727853](https://www.pivotaltracker.com/n/projects/2481184/stories/181727853)

fix url for filtered product select plan btn

---

app/assets/stylesheets/custom.scss.erb
app/views/insured/members_selection/_coverage_household.html.erb

[ME-181714008](https://www.pivotaltracker.com/n/projects/2481184/stories/181714008)

group selection ui fix

---

config/settings.yml

* [(Required!)](https://redmine.dchbx.org/issues/98320)
* ()
* ()
```
```
*
---
---

98320: Update renewal date

---

app/views/insured/product_shoppings/receipt.html.erb
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb

[MA-181595777](https://www.pivotaltracker.com/n/projects/2481184/stories/181595777)

add cucumber for waive some members

---

app/controllers/insured/members_selection_controller.rb
app/interactors/build_json_payload_for_shopping.rb
app/views/insured/members_selection/_coverage_household.html.erb
app/views/insured/members_selection/new.html.erb
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb
spec/data_migrations/adding_employee_role_spec.rb
spec/interactors/build_json_payload_for_shopping_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Update to waiver logic

---

app/models/group_selection_eligibility_checker.rb
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_choose_coverage.rb

[MA-182067640](https://www.pivotaltracker.com/n/projects/2481184/stories/182067640)

add check for child over 25 to coverage select

---

app/controllers/insured/product_shoppings_controller.rb
spec/controllers/insured/shop/product_shoppings_controller_spec.rb
spec/interactors/assign_params_for_checkout_spec.rb
spec/interactors/assign_shop_attributes_to_enrollments_spec.rb
spec/interactors/check_eligibility_for_new_enrollment_spec.rb
spec/interactors/persist_enrollment_and_assign_to_assignments_spec.rb
spec/shared_context/setup_shop_families_enrollments.rb

* (Required!)
* ()
* ()
```
```
*
---
---

CPS controller specs v1

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

98424: Update renewal date to 26

---

spec/models/plan_selection_spec.rb

* N/A
* ()
* ()
```
```
*
---
---

plan_selection spec fix

---

app/views/insured/members_selection/_coverage_household.html.erb
app/views/insured/members_selection/new.html.erb
db/seedfiles/translations/en/cca/insured.rb
db/seedfiles/translations/en/dc/insured.rb
features/employee/employee_plan_shopping_make_changes_button_display.feature
features/group_selection/ee_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_choose_coverage.rb

[98636](https://redmine.dchbx.org/issues/98636)

update wording on choose coverage page

---

app/views/insured/members_selection/new.html.erb
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_enroll_in_a_plan.rb

[RM-98625](https://redmine.dchbx.org/issues/98625)

Add UI Error Message when Primary is not an enrolee

---

app/views/insured/members_selection/eligible_coverage_selection.html.erb

RM-[98625](https://redmine.dchbx.org/issues/98625)

Updates to Eligible member selection page

---

app/controllers/concerns/config/site_concern.rb
app/controllers/users/registrations_controller.rb
app/helpers/config/aca_helper.rb
app/helpers/config/site_helper.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
components/benefit_sponsors/spec/dummy/app/helpers/config/site_helper.rb
spec/controllers/users/registrations_controller_spec.rb

* https://redmine.dchbx.org/issues/98845
* ()
* ()
```
```
*
---
---

activate captcha

---

app/views/insured/families/_employer_panel.html.erb

[RM-98955](https://redmine.dchbx.org/issues/98955)
* ()
* ()
```
```
*
---
---

display Confirm your selections for new hires

---

app/views/insured/members_selection/new.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

display confirm your selections button for all cases

---

app/views/insured/members_selection/new.html.erb
app/views/insured/product_shoppings/show.html.slim

* (Required!)
* ()
* ()
```
```
*
---
---

Bug 99027 2

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Change renewal date

---

app/controllers/concerns/config/site_concern.rb
app/controllers/users/registrations_controller.rb
app/helpers/config/aca_helper.rb
app/helpers/config/site_helper.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
components/benefit_sponsors/spec/dummy/app/helpers/config/site_helper.rb
spec/controllers/users/registrations_controller_spec.rb

Reverted the revert commit SHA: 29efcdb47b.

Revert "Revert "activate captcha (#2280)""

---

app/helpers/insured/group_selection_helper.rb
spec/helpers/insured/group_selection_helper_spec.rb

[RM-99512](https://redmine.dchbx.org/issues/99512)

fix cps missing organizer error

---

app/helpers/insured/group_selection_helper.rb
spec/helpers/insured/group_selection_helper_spec.rb

Reverts health-connector/enroll#2300

Revert "fix cps missing organizer error"

---

features/employers/add_plan_year_for_employer.feature
features/step_definitions/conversion_employee_steps.rb

Addressing cucumbers that pass near the beginning of November but fail after the 5th

fix qle after effective month issue

---

features/step_definitions/conversion_employee_steps.rb

fix employee_plan_shopping.feature failing based on qle date selection

change qle date to end of prev month

---

features/support/worlds/benefit_market_world.rb

Cucumber fix for date setting when run in december

change initial dates settings for december runs

---

app/models/census_employee.rb
components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/sponsored_benefit.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
spec/models/census_employee_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Rc release 5.7.53

---

app/data_migrations/add_contribution_models_to_product_package.rb
features/support/worlds/benefit_market_world.rb

fixing january date based failures

fix date based failures

---

.github/workflows/ruby.yml
components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/sponsored_benefit_cost_estimation_service.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/spec/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs_spec.rb

https://www.pivotaltracker.com/story/show/183764332
https://www.pivotaltracker.com/story/show/183793900
* ()
* ()
```
```
*
---
---

adding table for employee estimated costs

---

app/views/ui-components/v1/cards/_metal_level_select.html.slim
app/views/ui-components/v1/cards/_reference_plan.html.slim
components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb
components/benefit_sponsors/app/controllers/benefit_sponsors/sponsored_benefits/sponsored_benefits_controller.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/_sponsored_benefit.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/_sponsored_benefit.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/edit.html.slim
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller_spec.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/sponsored_benefits/sponsored_benefits_controller_spec.rb
components/benefit_sponsors/spec/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs_spec.rb

https://www.pivotaltracker.com/story/show/183793836
https://www.pivotaltracker.com/story/show/184110159
* ()
* ()
```
```
*
---
---

Fix employer detailed costs in edit flow

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb

Added a back button to the details page to navigate back to the benefits page.
https://www.pivotaltracker.com/n/projects/2481184/stories/183794746

added button return to quote

---

components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/n/projects/2481184/stories/183804796

Style updates to Enroll/Waive

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb

Return to plan selection button aligned to the left.
https://www.pivotaltracker.com/n/projects/2481184/stories/183794746

button left aligned

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/_sponsored_benefit.html.slim
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_selections/_plan_selection_form.html.erb

https://www.pivotaltracker.com/n/projects/2481184/stories/184225682
https://www.pivotaltracker.com/story/show/183763786
* ()
* ()
```
```
*
---
---

Bug fixes for estimated employer details section

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/story/show/184250272
* ()
* ()
```
```
*
---
---

Add container class to employer estimated costs page

---

components/benefit_sponsors/app/models/benefit_sponsors/services/sponsored_benefit_cost_estimation_service.rb

https://www.pivotaltracker.com/n/projects/2481184/stories/184250595

added filter for metal level kind

---

components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/models/sponsored_benefits/services/plan_cost_service.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller_spec.rb

https://www.pivotaltracker.com/story/show/183763786
https://www.pivotaltracker.com/story/show/183764318
https://www.pivotaltracker.com/story/show/183764332

calculating employee estimated costs for sponsored benefits

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/story/show/184315218
* ()
* ()
```
```
*
---
---

Broker return to plan selection

---

components/sponsored_benefits/app/views/layouts/sponsored_benefits/application.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/n/projects/2481184/stories/184315196
have worked on this changes on the ticket

added header content, footer and paragraph

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb

worked on changing the position of reference product https://www.pivotaltracker.com/n/projects/2481184/stories/184250539

changed position of reference product

---

components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb

worked on export employee costs
https://www.pivotaltracker.com/n/projects/2481184/stories/183764312

added export button and pdf code

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/story/show/184325432
https://www.pivotaltracker.com/story/show/184336976
* ()
* ()
```
```
*
---
---

Add employer premium section and fix few UI issues

---

config/settings.yml

Change the renewal generation date to 25

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/sponsored_benefit_cost_estimation_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/census_employee_estimated_cost_group.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.pdf.erb
components/benefit_sponsors/spec/domain/benefit_sponsors/operations/benefit_sponsorship/estimated_employee_costs_spec.rb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/models/sponsored_benefits/services/plan_cost_service.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller_spec.rb

https://www.pivotaltracker.com/story/show/184370804

Update EE Cost table layout

---

components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_packages/benefit_packages_controller.rb

https://www.pivotaltracker.com/story/show/183764312

adding dpi, setting disposition as attachment

---

components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/benefit_groups_controller.rb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb

https://www.pivotaltracker.com/story/show/184370768
* ()
* ()
```
```
*
---
---

Display only relevant cost table for brokers

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.pdf.erb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb

https://www.pivotaltracker.com/story/show/183793882
https://www.pivotaltracker.com/story/show/183764312

export pdf fixes on broker and employer detail costs pages

---

app/views/employers/plan_years/plan_selection/_offered_plan.html.erb
app/views/employers/plan_years/plan_selection/_plan_details.html.erb
app/views/ui-components/v1/cards/_reference_plan.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/_product_choices.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/_reference_plan.slim
components/old_sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/contributions/_plan_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/contributions/_plan_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb

worked on this https://www.pivotaltracker.com/n/projects/2481184/stories/184416298# please review

Text Changes On Employee and Broker Estimated Cost Pages

---

components/sponsored_benefits/app/models/sponsored_benefits/services/plan_cost_service.rb

https://www.pivotaltracker.com/n/projects/2481184/stories/184416351

updated dental reference plan logic

---

db/seedfiles/translations/en/cca/plan.rb
spec/views/shared/_carrier_contact_information.html.erb_spec.rb

* (Required!)
* https://redmine.dchbx.org/issues/100957
* ()
* ()
```
```
*
---
---
Updated translations to reflect carrier contact email change
Fixed spec to reflect this change

Updating carrier contact email

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.pdf.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb

https://www.pivotaltracker.com/n/projects/2481184/stories/184615438#
* ()
* ()
```
```
*
---
---

Flip ee carrier name from the table

---

components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.pdf.erb
components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_proposals/plan_reviews_controller.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb

https://www.pivotaltracker.com/story/show/184607418
* ()
* ()
```
```
*
---
---

Fix broker side exporting pdf and cosmetic fixes

---

app/helpers/application_helper.rb
app/models/census_employee.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_home_tab.html.erb_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/census_employee_spec.rb
spec/views/employers/employer_profiles/my_account/_enrollment_progress_bar.erb_spec.rb
spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb

* (https://redmine.priv.dchbx.org/issues/101523)
* (https://github.com/health-connector/enroll/pull/2394)

Rc release 5.7.58

---

app/models/organization.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
components/old_sponsored_benefits/app/models/sponsored_benefits/organizations/organization.rb

* (https://github.com/health-connector/enroll/pull/2408)

Rc release 5.7.60

---

app/views/insured/families/_shop_for_plans_widget.html.erb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

* (https://redmine.priv.dchbx.org/issues/101777)
* (https://github.com/health-connector/enroll/pull/2411)

Rc release 5.7.61

---

config/settings.yml

[RM-101745](https://redmine.priv.dchbx.org/issues/101745)

Renewal generation date change to 26

---

app/models/benefit_group.rb
app/models/census_employee.rb
app/models/composite_rating_list_bill_precalculator.rb
app/models/plan.rb
app/models/plan_cost_decorator.rb
app/views/ui-components/v1/tables/_benefit_package_summary.html.slim
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/contribution_calculators/cca_shop_reference_plan_contribution_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/contribution_calculators/simple_shop_reference_plan_contribution_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/contribution_calculators/tiered_percent_contribution_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/cca_composite_tier_precalculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/cca_composite_tiered_price_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/cca_shop_list_bill_pricing_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/pricing_calculators/shop_simple_list_bill_pricing_calculator.rb
components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/estimated_employee_cost_details.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/contribution_calculators/cca_shop_reference_plan_contribution_calculator_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/contribution_calculators/simple_shop_reference_plan_contribution_calculator_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/contribution_calculators/tiered_percent_contribution_calculator_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/pricing_calculators/cca_composite_tiered_price_calculator_spec.rb
components/sponsored_benefits/app/models/sponsored_benefits/services/plan_cost_service.rb
config/settings.yml
spec/models/plan_cost_decorator_spec.rb
spec/models/plan_spec.rb

* (https://redmine.priv.dchbx.org/issues/101636)
* (https://redmine.priv.dchbx.org/issues/101599)
* (https://redmine.priv.dchbx.org/issues/101745)
* (https://github.com/health-connector/enroll/pull/2401)
* (https://github.com/health-connector/enroll/pull/2398)
* (https://github.com/health-connector/enroll/pull/2413)

Rc release 5.7.62

---

app/models/benefit_group_assignment.rb
app/models/census_employee.rb
spec/models/census_employee_spec.rb

[RM-100419](https://redmine.priv.dchbx.org/issues/100419)

Fix active benefit group assignment method to compare application status

---

config/settings.yml

[RM-102076](https://redmine.priv.dchbx.org/issues/102076)

Revert renewal date to 1st of the month

---

config/settings.yml

* (https://redmine.priv.dchbx.org/issues/102076)
* (https://github.com/health-connector/enroll/pull/2417)

Rc release 5.7.64

---

.github/test.js
.github/workflows/load-test.yml

K6 integration with GHA

---

.github/workflows/load-test.yml

testing k6 on rc branch

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb
db/seedfiles/translations/en/cca/employer.rb

[RM-102232](https://redmine.priv.dchbx.org/issues/102232)

Fix cost detail pdf display issue

---

app/controllers/employers/census_employees_controller.rb
db/seedfiles/translations/en/cca/census_employee.rb
spec/controllers/employers/census_employees_controller_spec.rb

https://www.pivotaltracker.com/story/show/185022388

adding an info flash when dependent added

---

app/controllers/employers/census_employees_controller.rb
db/seedfiles/translations/en/cca/census_employee.rb
spec/controllers/employers/census_employees_controller_spec.rb

https://www.pivotaltracker.com/story/show/185092187

add info flash on employee creation

---

app/views/exchanges/hbx_profiles/_family_index_datatable.html.slim
app/views/ui-components/v1/navs/_primary_nav.html.slim
db/seedfiles/translations/en/cca/hbx_profiles.rb
db/seedfiles/translations/en/dc/hbx_profiles.rb
features/admin/add_sep_read_and_write.feature
features/admin/add_sep_read_only.feature
features/admin/edit_aptc_csr.feature
features/admin/edit_aptc_csr_individual_disabled.feature
features/admin/edit_dob_ssn.feature
features/admin/new_employee_paper.feature
features/admin/paper_phone.feature
features/cover_all/consumer_requests_enrollment.feature
features/permissions/edit_dob_ssn_permission.feature
features/step_definitions/edit_aptc_csr_steps.rb
features/support/worlds/user_world.rb

[185021654](https://www.pivotaltracker.com/n/projects/2640061/stories/185021654)
Text update for admin Families tab

change families index label to employees

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_reviews/estimated_employee_cost_details.pdf.erb
db/seedfiles/translations/en/cca/employer.rb

* (https://redmine.priv.dchbx.org/issues/102232)
* (https://github.com/health-connector/enroll/pull/2421)

Rc release 5.7.65

---

app/views/broker_agencies/profiles/_menu.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_families.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_menu.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/profiles/broker_agency/_menu.html.erb

[185021682](https://www.pivotaltracker.com/n/projects/2640061/stories/185021682)

change broker families text to employees

---

app/views/broker_agencies/profiles/_menu.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_menu.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/profiles/broker_agency/_menu.html.erb

[185021682](https://www.pivotaltracker.com/n/projects/2640061/stories/185021682)

update title attribute with translation

---

app/views/insured/members_selection/new.html.erb

https://www.pivotaltracker.com/story/show/185021709

executing string

---

app/views/ui-components/v1/navs/_primary_nav.html.slim
features/admin/questions.feature
features/step_definitions/integration_steps.rb
system/config/templates/features/enroll_app/enroll_app.yml

[185021669](https://www.pivotaltracker.com/n/projects/2640061/stories/185021669)

add default false feature flags for admin tabs

---

app/views/ui-components/v1/navs/_primary_nav.html.slim
features/step_definitions/integration_steps.rb
system/config/templates/features/enroll_app/enroll_app.yml

[185021669](https://www.pivotaltracker.com/n/projects/2640061/stories/185021669)

remove inbox from admin config

---

app/models/organization.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/organization_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
components/sponsored_benefits/app/models/sponsored_benefits/concerns/organization_concern.rb
components/sponsored_benefits/spec/dummy/app/models/benefit_sponsors/organizations/organization.rb

[185022458](https://www.pivotaltracker.com/n/projects/2640061/stories/185022458)
[185022500](https://www.pivotaltracker.com/n/projects/2640061/stories/185022500)

add sole proprietor to entity kinds list

---

components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization_forms/registration_form.rb
components/benefit_sponsors/app/models/benefit_sponsors/serializers/staff_role_serializer.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/new_profile_registration_service.rb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_person_info_fields.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/registrations/_broker_agency_form.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/registrations/edit.html.slim
components/benefit_sponsors/app/views/benefit_sponsors/shared/_broker_agency_contact_information.html.erb
components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/registration_form_spec.rb

https://www.pivotaltracker.com/story/show/185590012
https://www.pivotaltracker.com/story/show/185021723
https://www.pivotaltracker.com/story/show/185455452

broker contact information updates

---

app/assets/javascripts/group_selection.js
features/group_selection/member_plan_shopping.feature
features/step_definitions/integration_steps.rb
features/support/object_model_pages/shop/employee/ee_choose_coverage.rb

https://www.pivotaltracker.com/story/show/185701513

enabling submit after switching from waive to enroll

---

app/assets/javascripts/group_selection.js
app/models/hbx_enrollment.rb
db/seedfiles/translations/en/cca/insured.rb
spec/controllers/insured/shop/product_shoppings_controller_spec.rb

https://www.pivotaltracker.com/story/show/185748155

verbiage updates

---

features/employers/benefit_applications/admin_reinstate_benefit_application_steps.rb
features/support/resource_registry_world.rb
system/config/templates/features/cca_shop_market/cca_shop_market.yml

* [MA-186437027](https://www.pivotaltracker.com/n/projects/2640061/stories/186437027)
* ()
* ()
```
```
*
---
---

adding feature flag keys for reinstate and revise end date

---

app/views/exchanges/employer_applications/_index.html.erb

* [MA-186446465](https://www.pivotaltracker.com/n/projects/2659995/stories/186446465)
* ()
* ()
```
```
*
---
---

removing unwanted event type names

---

app/policies/hbx_profile_policy.rb

* [MA-186171690](https://www.pivotaltracker.com/n/projects/2659995/stories/186171690)
* ()
* ()
```
```
*
---
---

fixing pundit permission for can_generate_v2_xml action

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_item.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_benefit_applications_benefit_application.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_benefit_applications_benefit_application_items.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_item_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/shared_contexts/benefit_application.rb

https://www.pivotaltracker.com/story/show/186437002
https://www.pivotaltracker.com/story/show/186437007

Introducing benefit application item & composite

---

app/models/enrollments/replicator/reinstatement.rb
app/models/hbx_enrollment.rb
app/models/importers/transcripts/enrollment_transcript.rb
app/views/datatables/employers/_bulk_actions_column.html.haml
components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_application.rb
components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_application_item.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/enrollment_eligibility/determine.rb
components/benefit_sponsors/app/domain/benefit_sponsors/validators/benefit_applications/benefit_application_contract.rb
components/benefit_sponsors/app/domain/benefit_sponsors/validators/benefit_applications/benefit_application_item_contract.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_factory.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/roster_upload_service.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb
components/benefit_sponsors/spec/dummy/app/models/hbx_enrollment.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_benefit_applications_benefit_application.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
spec/controllers/insured/group_selection_controller_spec.rb

https://www.pivotaltracker.com/story/show/186437018
https://www.pivotaltracker.com/story/show/186437023

linking composite to benefit sponsorship

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
features/support/worlds/benefit_application_world.rb
spec/controllers/insured/group_selection_controller_spec.rb
spec/domain/operations/census_members/update_spec.rb
spec/models/census_employee_spec.rb

* [MA-186443287](https://www.pivotaltracker.com/n/projects/2640061/stories/186443287)
* ()
* ()
```
```
*
---
---

updating links between employee, benefit group assignments 

---

app/views/exchanges/employer_applications/_index.html.erb
components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_application.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/enrollment_eligibility/determine.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
components/benefit_sponsors/spec/domain/benefit_sponsors/entities/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/model_events/initial_employer_open_enrollment_completed_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
spec/data_migrations/update_benefit_group_assignment_details_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/benefit_group_assignment_spec.rb
spec/models/census_employee_spec.rb
spec/models/employee_role_integration_spec.rb
spec/support/bradys_after_all.rb

https://www.pivotaltracker.com/story/show/186443289
https://www.pivotaltracker.com/story/show/186443285

er portal & workflow updates

---

app/controllers/exchanges/employer_applications_controller.rb
components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_application_item.rb
components/benefit_sponsors/app/domain/benefit_sponsors/validators/benefit_applications/benefit_application_item_contract.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_item.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_action_service.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_item_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
lib/tasks/benefit_application_terminated_list.rake
lib/tasks/migrations/terminate_benefit_application.rake
spec/data_migrations/correct_plan_year_end_date_spec.rb
spec/data_migrations/update_employee_role_id_spec.rb
spec/data_migrations/update_predecessor_id_on_bp_spec.rb
spec/data_migrations/update_product_package_rates_spec.rb
spec/features/members_selection_get_new_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/events_helper_spec.rb
spec/models/census_employee_spec.rb

https://www.pivotaltracker.com/story/show/186443356

fixing term/cancel and scheduled events

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/aca_shop_benefit_sponsorship_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb

https://www.pivotaltracker.com/story/show/186443455
update: Most of these changes are introduced as part of this project and added refactor her to remove sub-document checks with latest code.

wire in scheduled events

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_item.rb
lib/tasks/migrate_benefit_applications_to_composite.rake

https://www.pivotaltracker.com/story/show/186705676
https://www.pivotaltracker.com/story/show/186705797

handling benefit applications with same bson id

---

spec/controllers/exchanges/hbx_profiles_controller_spec.rb

https://www.pivotaltracker.com/n/projects/2640061/stories/186443334

plan year create spec for termination pending state

---

features/employers/benefit_applications/admin_reinstate_benefit_application_steps.rb
features/employers/benefit_applications/admin_revise_end_date_ben_app_steps.rb
features/employers/benefit_applications/reinstate/admin_enable_reinstate_benefit_application_permission.feature
features/employers/benefit_applications/reinstate/admin_reinstate_benefit_application.feature
features/employers/benefit_applications/revise_end_date/admin_enable_revise_end_date_ben_app_permission.feature
features/employers/benefit_applications/revise_end_date/admin_revise_end_date_benefit_application.feature

* [reinstate-186711657](https://www.pivotaltracker.com/n/projects/2640061/stories/186711657)
* ()
* ()
```
```
*
---
---

adding cucumbers for revise and reinstate admin tools

---

app/models/importers/transcripts/enrollment_transcript.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/queries/coverage_reports_query.rb

https://www.pivotaltracker.com/n/projects/2640061/stories/186713796

fixed scopes to fetch correct records

---

components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186443371

block PY to reinstate if overlapping coverage exists

---

app/controllers/exchanges/employer_applications_controller.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/revise.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/revise_spec.rb
system/config/templates/features/cca_shop_market/cca_shop_market.yml

https://www.pivotaltracker.com/story/show/186443389

admin action to revise end date

---

app/controllers/exchanges/employer_applications_controller.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186443366

fixing reinstate and revise for retroactive canceled plan year

---

app/controllers/exchanges/employer_applications_controller.rb
app/helpers/config/aca_helper.rb
app/views/exchanges/employer_applications/_index.html.erb
app/views/exchanges/employer_applications/application_history.html.erb
app/views/exchanges/employer_applications/index.js.erb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_action_service.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_action_service_spec.rb
db/seedfiles/translations/en/cca/exchange.rb

https://www.pivotaltracker.com/story/show/186693229

validate end date on termination and passing json for cancel and terminate

---

app/controllers/exchanges/employer_applications_controller.rb
app/helpers/config/aca_helper.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186566579

adding reinstate restrictions

---

components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186443371

check overlap with initial effective period of the benefit application

---

app/models/hbx_enrollment.rb
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb

https://www.pivotaltracker.com/story/show/186834566

fixing tools for multiple enrollments

---

app/helpers/application_helper.rb
app/views/exchanges/employer_applications/_index.html.erb
app/views/exchanges/employer_applications/confirmation_details.html.erb
app/views/exchanges/employer_applications/index.js.erb
db/seedfiles/translations/en/cca/exchange.rb
features/employers/benefit_applications/admin_reinstate_benefit_application_steps.rb
spec/helpers/application_helper_spec.rb

https://www.pivotaltracker.com/story/show/186443428

disable admin actions for 24 hours after an action is taken

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb

https://www.pivotaltracker.com/story/show/186880557

blocking duplicate transition events

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
lib/tasks/migrate_benefit_applications_to_composite.rake

https://www.pivotaltracker.com/story/show/186892302

fixing migrations and queries

---

components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186908079

reinstating dental without waiver reason/product as waivers

---

components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb

https://www.pivotaltracker.com/story/show/186986538

handling future effective enr on reinstate

---

app/models/hbx_enrollment.rb
app/views/events/hbx_enrollment/_policy.xml.haml
components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
components/benefit_sponsors/spec/domain/benefit_applications/operations/reinstate_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
script/shop_sep_query.rb

https://www.pivotaltracker.com/story/show/186985891

updates to reinstate term events

---

components/notifier/app/models/notifier/template.rb
components/notifier/spec/models/notifier/notice_kind_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Rc release 5.7.81

---

app/controllers/insured/plan_shoppings_controller.rb
app/models/broker_role.rb
app/policies/hbx_enrollment_policy.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/broker_agency_profile.rb
spec/controllers/insured/plan_shoppings_controller_spec.rb

https://www.pivotaltracker.com/n/projects/2640063/stories/187338871

authorize plan shopping controller actions

---

app/controllers/documents_controller.rb
app/views/shared/plan_shoppings/_sbc_link.html.erb
components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_package_service.rb
db/seedfiles/translations/en/cca/exchange.rb
spec/controllers/documents_controller_spec.rb

https://www.pivotaltracker.com/story/show/187476058
[RM105965](https://redmine.priv.dchbx.org/issues/105965)
* ()
* ()
```
```
*
---
---

fixing sbc links on bqt & ER portal

---

app/controllers/documents_controller.rb
system/config/templates/features/enroll_app/enroll_app.yml

https://redmine.priv.dchbx.org/issues/106195
* ()
* ()
```
```
*
---
---

update key to file name

---

.gitignore
Gemfile
Gemfile.lock
bin/rails
bin/rake
bin/setup
config/boot.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/application_controller_renderer.rb
config/initializers/assets.rb
config/initializers/content_security_policy.rb
config/initializers/cors.rb
config/initializers/filter_parameter_logging.rb
config/initializers/new_framework_defaults_6_0.rb
config/locales/en.yml
config/puma.rb

https://www.pivotaltracker.com/story/show/186963187
* ()
* ()
```
```
*
---
---
* Update config files to be compatible with Rails 6

update config files to be compatible with rails 6

---

app/controllers/users/passwords_controller.rb
app/helpers/l10n_helper.rb
components/benefit_sponsors/spec/dummy/app/helpers/l10n_helper.rb
components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
components/sponsored_benefits/spec/dummy/app/helpers/l10n_helper.rb
spec/rails_helper.rb

* https://redmine.priv.dchbx.org/issues/109852
* ()
* ()
```
```
*
---
---
This fixes download PDF option under BQT and fixes [translations issue](https://ideacrew.slack.com/archives/C05QYMMBKFF/p1728502218275619?thread_ts=1728501074.349399&cid=C05QYMMBKFF)

fix download PDF BQT and translations

---

config/mongoid.yml
script/push_date.rb

fix for faulty piece of https://www.pivotaltracker.com/n/projects/2663780/stories/188414342#

fix bad yaml indents

---

app/helpers/application_helper.rb
app/views/datatables/employers/_bulk_actions_column.html.haml
app/views/employers/employer_attestations/_edit.html.erb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/aca_shop_cca_employer_profile.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb

[IC-188797336](https://www.pivotaltracker.com/n/projects/2481184/stories/188797336#)

Employer Index optimization and filter alignment fix

---

lib/tasks/notices/shop_employer_notice_for_all_inputs.rake
spec/lib/tasks/notices/shop_employer_notice_for_all_inputs_spec.rb

[IC-188810487](https://www.pivotaltracker.com/n/projects/2481184/stories/188810487)

Fix employer notice rake

---

components/benefit_sponsors/app/models/benefit_sponsors/organizations/aca_shop_cca_employer_profile.rb
components/benefit_sponsors/spec/models/benefit_sponsors/organizations/aca_shop_cca_employer_profile_spec.rb
spec/helpers/application_helper_spec.rb

[IC-188797336](https://www.pivotaltracker.com/n/projects/2481184/stories/188797336)

add employer attestation index

---

components/benefit_sponsors/app/views/benefit_sponsors/shared/inboxes/_message.html.erb

[IC-188813397](https://www.pivotaltracker.com/n/projects/2481184/stories/188813397)

Notices not opening in new tab bug fix
